### ISSUE TITLE
Not creating wanted list

### ISSUE THREAD

**Issue by vidjya** [evilhero/mylar#2209] opened 2019-02-20 14:34 UTC
Mylar is not creating my pull/wanted list for the second week running. Items appear in the Upcoming box below the wanted list, but new issues do not appear in the wanted section. Here's a debug log of trying to create the wanted list from Manage>Jobs, then trying to recreate from This Week>Recreate Pull List, then simply refreshing a single issue.

https://pastebin.com/VGAWAi46

None of these seemed to populate the pull list in "Wanted", though items do appear in red in "This Week". Before this I updated to the most recent version of the dev branch.

**Comment by barbequesauce** [comment] 2019-02-20 14:45
Usually when you see this it's because ComicVine hasn't updated their issue data yet - They dont start until Tuesday late night or Wednesday morning, and last week some stuff didn't get updated until Friday. You can see it yourself if you search for those issue numbers on CV... Without that data Mylar really has a hard time matching things, so we just have to wait.

**Comment by evilhero** [comment] 2019-02-20 15:02
This is a duplicate of #2143 - so there's no need to create a duplicate issue (altho I just closed #2143). Like @barbequesauce said, this is out of the control of Mylar as we use CV data when populating the series information. It's just not there yet, and patience is required.

**Comment by vidjya** [comment] 2019-02-20 15:11
OK. @barbequesauce mentioned in #2143 to open a new issue with the debug log, so that's what I did. Generally they start to populate Tuesday night, so I was surprised not to see anything in there Wednesday. Looking through comicvine's new comic section, I do see that my titles haven't begun to populate yet. If it drifts into Thursday and nothing's appearing without forcing it, I will update.

**Comment by evilhero** [comment] 2019-02-20 15:19
As long as you leave Mylar running, Mylar will check against the API site every 4 hours and update any issue information at that point if it's available. Once your client receives the updated pull-list with the new information changes, it will force a refresh of each series that it then knows has the new information - and at that point they will get moved into the Wanted section whereby they can/will be searched for.  

So again, if there's no issue information on CV - there's not much we can do in relation to populating the information at this point in time (so if it's not there on Thursday, it's not gonna change anything I'm afraid). Typically in the past it's been late Tuesday that things start getting populated on CV, however the last couple weeks it's been more like late Wednesday/Thursday and Friday even.

**Comment by WedgeSparda** [comment] 2019-04-18 07:54
Hi, I saw a strange behaviour related to this.

My wanted list wasn't updated for some comics, so I followed these steps:

- Entered in one of those comics details page and click  on "Refresh Comics"
- The new issue of the comics then appears on the comic details page and the Wanted list, but with date 0000-00-00
- Entered in the "This Week" list and cliick on "Recreate Pull list".
- Then the date of the comics changes from 0000-00-00 to the real date.
- Now I can force a check for the new issues.

Is this the normal behaviour?

**Comment by barbequesauce** [comment] 2019-04-18 12:22
Yes, that is what happens behind the scenes. There are scheduled jobs to take each of these actions, and normally you wouldn’t have to step through them... all of your series are refreshed once a week - spaced out over a week so as not to hammer CV; the pulllist is regenerated every four hours by default.

**Closed** 2021-01-01 21:03 UTC
