### ISSUE TITLE
Can't Download from 32p

### ISSUE THREAD

**Issue by BenBeyond** [evilhero/mylar#1785] opened 2017-11-25 00:12 UTC
Since the recent batch of updates, Mylar has been unable to download any comics.  I only use 32p, so that is the only source that I can confirm that it doesn't work.  
Here is the debug log trying to manual search for Lumberjanes #43, which I can confirm through the web is definitely on 32p:

2017-11-24 19:05:22 | DEBUG | Could not find issue doing a manual search via : api
-- | -- | --
2017-11-24 19:05:22 | INFO | Could not find Issue 43 of Lumberjanes (2014) using 32P [api]
2017-11-24 19:05:22 | DEBUG | [FAILED_DOWNLOAD_CHECKER] [32P] Marked as a bad download : 57138
2017-11-24 19:05:22 | INFO | [FAILED_DOWNLOAD_CHECKER] continuing search for another download.
2017-11-24 19:05:22 | INFO | [FAILED_DOWNLOAD_CHECKER] result has a status of FAIL which indicates it is not a good choice to download.
2017-11-24 19:05:22 | INFO | prov : 32P[57138]
2017-11-24 19:05:22 | DEBUG | link given by: 32P
2017-11-24 19:05:22 | INFO | Found Lumberjanes (2017) issue: 43 using 32P
2017-11-24 19:05:22 | DEBUG | issues match!
2017-11-24 19:05:22 | DEBUG | nzbname used for post-processing:Lumberjanes.v0.#43
2017-11-24 19:05:22 | DEBUG | integer value of issue we have found : 43000
2017-11-24 19:05:22 | DEBUG | issue we found for is : 43
2017-11-24 19:05:22 | DEBUG | integer value of issue we are looking for : 43000
2017-11-24 19:05:22 | DEBUG | issue we are looking for is : 43
2017-11-24 19:05:22 | DEBUG | this should be a match!
2017-11-24 19:05:22 | DEBUG | it's a go captain... - we matched 100.0%!
2017-11-24 19:05:22 | DEBUG | Match to series : 100.0 %.
2017-11-24 19:05:22 | DEBUG | splitit-len:1
2017-11-24 19:05:22 | DEBUG | scount:1
2017-11-24 19:05:22 | DEBUG | word matched on : lumberjanes
2017-11-24 19:05:22 | DEBUG | 0 Comparing: lumberjanes .to. lumberjanes
2017-11-24 19:05:22 | DEBUG | scount : 0
2017-11-24 19:05:22 | DEBUG | splitit: lumberjanes
2017-11-24 19:05:22 | DEBUG | Watchlist-length: 1
2017-11-24 19:05:22 | DEBUG | search-length: 1
2017-11-24 19:05:22 | DEBUG | length match..proceeding
2017-11-24 19:05:22 | DEBUG | len-watchcomic : 1
2017-11-24 19:05:22 | DEBUG | splitst : 1
2017-11-24 19:05:22 | DEBUG | ['lumberjanes'] watchlist word count: 1
2017-11-24 19:05:22 | DEBUG | ['lumberjanes', '43'] nzb series word count: 1
2017-11-24 19:05:22 | DEBUG | adjusting from: lumberjanes 43 to: 43
2017-11-24 19:05:22 | DEBUG | adjusted nzb comic and issue: lumberjanes 43
2017-11-24 19:05:22 | DEBUG | original nzb comic and issue: lumberjanes 43
2017-11-24 19:05:22 | DEBUG | We matched on versions...v0
2017-11-24 19:05:22 | DEBUG | SCVersion: 2014
2017-11-24 19:05:22 | DEBUG | DCVersion: 1
2017-11-24 19:05:22 | DEBUG | FCVersion: 1
2017-11-24 19:05:22 | DEBUG | 32P torrent discovery. Posting date (Thu, 23 Nov 2017 07:10:25) is after store date (2017-10-18), forcing volume label to be the same as series label (0-Day Enforcement): v1 --> v2014
2017-11-24 19:05:22 | DEBUG | vers4vol: v0
2017-11-24 19:05:22 | DEBUG | vers4year: no
2017-11-24 19:05:22 | DEBUG | version found: v0
2017-11-24 19:05:22 | DEBUG | watch comicversion is None
2017-11-24 19:05:22 | DEBUG | volume detection commencing - adjusting length.
2017-11-24 19:05:22 | DEBUG | Year not given properly formatted but Version detected.Bypassing Year Match.
2017-11-24 19:05:22 | DEBUG | ComVersChk : 0
2017-11-24 19:05:22 | DEBUG | UseFuzzy is : None
2017-11-24 19:05:22 | DEBUG | Comic: lumberjanes 43
2017-11-24 19:05:22 | DEBUG | 0. Bracket Word: lumberjanes 43
2017-11-24 19:05:22 | DEBUG | Cleantitle: lumberjanes 43
2017-11-24 19:05:22 | DEBUG | Newly finished reformed cleantitle (with NO volume label): lumberjanes 43
2017-11-24 19:05:22 | DEBUG | [Vx] Version detected as v0
2017-11-24 19:05:22 | DEBUG | Cleantitle: lumberjanes v0 43
2017-11-24 19:05:22 | DEBUG | Entry: Lumberjanes v0 #43
2017-11-24 19:05:22 | DEBUG | Thu, 23 Nov 2017 07:10:25 is after store date of 2017-10-18
2017-11-24 19:05:22 | DEBUG | size given as: 77.5 MB
2017-11-24 19:05:22 | DEBUG | sub:Lumberjanes v0 #43
2017-11-24 19:05:22 | DEBUG | checking search result: Lumberjanes v0 #43
2017-11-24 19:05:22 | DEBUG | 32P direct match to issue # : 43
2017-11-24 19:05:22 | INFO | successfully retrieved 1 search results.
2017-11-24 19:05:21 | INFO | payload: {'action': 'groupsearch', 'issue': u'43', 'id': u'9191'}
2017-11-24 19:05:21 | DEBUG | Unable to properly verify reference on 32P - will update the 32P reference point once the issue has been successfully matched against.
2017-11-24 19:05:21 | INFO | 1 series match the tile being searched for on 32P...
2017-11-24 19:05:21 | INFO | dataset: [{'series': u'Lumberjanes', 'id': u'9191'}]
2017-11-24 19:05:21 | INFO | Exact series ID already discovered previously. Setting to :Lumberjanes[9191]
2017-11-24 19:05:21 | INFO | publisher search set to : Boom! Studios
2017-11-24 19:05:21 | DEBUG | [32P-AUTHENTICATION][LOGIN SUCCESS] Now preparing for the use of 32P keyed authentication...
2017-11-24 19:05:21 | DEBUG | [32P-AUTHENTICATION] Session key-based login was good.
2017-11-24 19:05:21 | INFO | inkdrops: {u'status': u'success', u'results': [{u'inkdrops': u'428745.3583', u'userid': 29299}]}
2017-11-24 19:05:20 | DEBUG | [32P-AUTHENTICATION] Session cookie found. Attempting to load...
2017-11-24 19:05:20 | DEBUG | calpha/cnumber: None / None
2017-11-24 19:05:20 | INFO | Shhh be very quiet...I'm looking for Lumberjanes issue: 43 (2017) using 32P
2017-11-24 19:05:20 | DEBUG | Initiating Search via : api
2017-11-24 19:05:20 | DEBUG | Could not find issue doing a manual search via : rss
2017-11-24 19:05:20 | INFO | Could not find Issue 43 of Lumberjanes (2014) using 32P [rss]
2017-11-24 19:05:20 | DEBUG | Wed, 23 Nov 2016 19:28:50 +0000 is before store date of 2017-10-18. Ignoring search result as this is not the right issue.
2017-11-24 19:05:20 | DEBUG | size given as: 42.9 MB
2017-11-24 19:05:20 | DEBUG | sub:Lumberjanes vol0 #32 (Son of Ultron-Empire)
2017-11-24 19:05:20 | DEBUG | checking search result: Lumberjanes vol0 #32 (Son of Ultron-Empire)
2017-11-24 19:05:20 | DEBUG | Wed, 09 Nov 2016 19:00:44 +0000 is before store date of 2017-10-18. Ignoring search result as this is not the right issue.
2017-11-24 19:05:20 | DEBUG | size given as: 31.2 MB
2017-11-24 19:05:20 | DEBUG | sub:Lumberjanes/Gotham Academy vol0 #3 (Minutemen-Faessla)
2017-11-24 19:05:20 | DEBUG | checking search result: Lumberjanes/Gotham Academy vol0 #3 (Minutemen-Faessla)
2017-11-24 19:05:20 | DEBUG | Wed, 09 Nov 2016 22:28:27 +0000 is before store date of 2017-10-18. Ignoring search result as this is not the right issue.
2017-11-24 19:05:20 | DEBUG | size given as: 256.7 MB
2017-11-24 19:05:20 | DEBUG | sub:Lumberjanes/Gotham Academy vol0 #1-6 (Son of Ultron-Empire)
2017-11-24 19:05:20 | DEBUG | checking search result: Lumberjanes/Gotham Academy vol0 #1-6 (Son of Ultron-Empire)
2017-11-24 19:05:20 | DEBUG | titleend: vol0 32 (son of ultron empire)
2017-11-24 19:05:20 | DEBUG | matched on series title: Lumberjanes
2017-11-24 19:05:20 | DEBUG | matched to : Lumberjanes vol0 #32 (Son of Ultron-Empire)
2017-11-24 19:05:20 | DEBUG | 11 - formatrem_seriesname :lumberjanes
2017-11-24 19:05:20 | DEBUG | 42 - formatrem_torsplit : lumberjanes vol0 32 (son of ultron empire)
2017-11-24 19:05:20 | DEBUG | tor-Title: Lumberjanes vol0 #32 (Son of Ultron-Empire)
2017-11-24 19:05:20 | DEBUG | titleend: gotham academy vol0 3 (minutemen faessla)
2017-11-24 19:05:20 | DEBUG | matched on series title: Lumberjanes
2017-11-24 19:05:20 | DEBUG | matched to : Lumberjanes/Gotham Academy vol0 #3 (Minutemen-Faessla)
2017-11-24 19:05:20 | DEBUG | 11 - formatrem_seriesname :lumberjanes
2017-11-24 19:05:20 | DEBUG | 53 - formatrem_torsplit : lumberjanes gotham academy vol0 3 (minutemen faessla)
2017-11-24 19:05:20 | DEBUG | tor-Title: Lumberjanes/Gotham Academy vol0 #3 (Minutemen-Faessla)
2017-11-24 19:05:20 | DEBUG | titleend: gotham academy vol0 1 6 (son of ultron empire)
2017-11-24 19:05:20 | DEBUG | matched on series title: Lumberjanes

Mylar Version: development
-- git build 6754ad0b8b6e0d4c9f5b13c7ab0ed1946792c77e.
Python Version : 2.7.12

**Comment by evilhero** [comment] 2017-11-25 02:19
It's finding it properly, it just can't send it to your torrent option for some reason, or wasn't able to in the past and because it failed sending it it marked it as a Failed entry and won't retry it again.

If you go into the Manage tab and then the Manage Issues option, you'll can select Failed status from the dropdown and it will show you all the issues that are in a Failed status. Then just checkmark the ones you want, and select Clear Failed from the dropdown and you should be able to retry them again without the problem occuring (at the very least it won't trigger a Failed mark initially and you can see where the true problem might lie thereafter).

**Comment by tombs007** [comment] 2017-11-25 02:37
Seeing similar issues as well


2017-11-24 21:33:07 | INFO | Could not find Issue 21 of Postal (2015) using 32P [api]
-- | -- | --
2017-11-24 21:33:07 | ERROR | Unable to send torrent - check logs and settings (this would be marked as a BAD torrent if Failed Handling was enabled)
2017-11-24 21:33:07 | ERROR | [RSS] Unable to sign-on to 32P to validate settings and initiate download sequence. Please enter/check your username password in the configuration.
2017-11-24 21:33:07 | INFO | matched on Postal
2017-11-24 21:33:07 | INFO | Found Postal (2017) issue: 21 using 32P within a pack containing issues: 1-22
2017-11-24 21:33:07 | INFO | Issue Number 21 exists within pack. Continuing.

If I go to settings -> Search Providers and perform a test connection it returns successful.

**Comment by evilhero** [comment] 2017-11-25 02:53
@tombs007 : yours might be a different issue - as the OP can authenticate properly he just can't send to the client due to it being in a Failed status. Yours is that you can't even authenticate properly even after the test connection succesfully does. Can you confirm what branch/commit you're running?

You might want to go into the /cache folder and delete the .32p_cookies.dat file which holds all the user information (or at least move it into a different location initially). Then start Mylar up and go do the Test Connection - it should return proper signon information. The cookies files lasts somewhere btwn 6-9 months I believe, so if you had changed your password somewhere inbetween there/recently, it might just be getting confused about certain things. Deleting the cookies file forces Mylar to use your user/password to sign on and validate things, and then save the new session to the cookies for another 6-9 months.

It might also help, if the above doesn't work, to enable debug logging prior to searching so that I can try and follow the workflow as to where it might be failing.

**Comment by tombs007** [comment] 2017-11-25 12:11
I started from scratch again using the master branch instead of development.

Was still seeing the same issue as noted above.

It seems like copy and paste of my password was not being accepted properly. The test would always pass but Inkdrops didn't get pulled.

After a few tries of entering the password it finally started working again.

**Comment by LordJay23** [comment] 2017-11-25 12:46
Tom's issue sounds like mine.  Right after Mylar starts up, do you see an entry in the log about 32p authentication failing?

**Comment by evilhero** [comment] 2017-11-25 13:20
@tombs007 did your passwd have any special characters in it - and were you saving and trying or saving and restarting (it shouldn't matter in development, but just wanted to ask)

@LordJay23 i had thought your 32P issues were all fixed up from last time we talked?

**Comment by tombs007** [comment] 2017-11-25 13:54
It does indeed. In master it works fine, in development I get an error.
Workflow:
-Select Torrents -> Enable 32P -> Auth mode
-Provide creds
-Click Test Connection
-Successful, and shows accurate Inkdrops count.
-Click Save Changes and it says "There was an error."

Log snippet:

2017-11-25 08:46:12 | DEBUG | [32P-AUTHENTICATION][LOGIN SUCCESS] Now preparing for the use of 32P keyed authentication...
-- | -- | --
2017-11-25 08:46:12 | DEBUG | [32P-AUTHENTICATION] Session key-based login was good.
2017-11-25 08:46:12 | INFO | inkdrops: {u'status': u'success', u'results': [{u'inkdrops': u'<sanitized>', u'userid': <sanitized>}]}
2017-11-25 08:46:12 | DEBUG | [32P-AUTHENTICATION] Session cookie found. Attempting to load...
2017-11-25 08:45:07 | DEBUG | If you read this message, debug logging is available

When I refresh and go back to Settings -> Download Settngs -> Torrents is not checked

**Comment by evilhero** [comment] 2017-11-25 13:57
Can I ask what the special character(s) are? The development branch has the new config changes so its possible its messing up on the save handling the characters for some reason. So it can't save the information properly, thus why you can't sign on thereafter (I'm guessing)

**Comment by tombs007** [comment] 2017-11-25 14:00
&%*^ are the specials, beginning and end characters are alphanumeric.

**Comment by BenBeyond** [comment] 2017-11-25 16:00
For what it is worth, what Evilhero told me to be fixed my original problem (clean failed links in the manage area of Mylar), but I will leave the issue open cuz other people seem to still need help

**Comment by evilhero** [comment] 2017-11-25 16:21
@BenBeyond Thanks for coming back and saying it's working for ya ;)  

@tombs007 I can confirm now that the problem is with the config parser not being able to handle the '%' in your password. Apparently, and I wasn't aware of this until I just read it, use of the % in a config value tells the parser to perform interpolation on it, so it's actually trying to substitute another variable in lieu of the %.....I'm working on this atm, but simply removing the % from a password saved the config fine.

**Comment by tombs007** [comment] 2017-11-25 16:30
@evilhero I took the % out my password for the time being. Thanks

**Comment by evilhero** [comment] 2017-11-25 18:17
@tombs007 newest development commit should fix your problems with the % symbol being in any variable now, regardless of it being in the .ini already or added via the GUI.

**Comment by tombs007** [comment] 2017-11-25 22:19
Awesome thanks again!

**Comment by evilhero** [comment] 2017-11-25 22:22
Glad to hear it worked for you 👍  And I'm pretty sure @LordJay23's problems stem from the same problem in our discussions. But he'll let me know otherwise once he can fix his other problems....

**Closed by evilhero** 2017-11-25 22:22 UTC
