### ISSUE TITLE
Story Arc in Mylar differs from Comicvine

### ISSUE THREAD

**Issue by skywayskase** [evilhero/mylar#1095] opened 2015-07-29 03:51 UTC
I've noticed one or two story arcs that I add in Mylar list different issues and sometime different orders than what is listed in Comicvine.
For example, I just added the 2007 run of Civil War. When I lookup Civil War on Comicvine the arc starts with the Road to Civil War comics, but in mylar the first three issues I see are the first few Civil War: Young Avengers & Runaways (2006) issues and the next three are Friendly Neighborhood Spider-Man (2005) issues. This also seems to be the case with the Original Sin arc from last year.
Also, in the case of Civil War, I don't see a first issue in the arc, it starts right at 2 for some reason. 
Is anyone else seeing this same thing happen?

**Comment by evilhero** [comment] 2015-07-29 14:23
I'll look into this today and try and see what's going on.  The problem is that comicvine doesn't actually track the reading order, it lists them in an order of somekind so mylar just pulls them down in sequence and assigns a reading order # based on that.

The original plan was for mylar to be able to take a cbl file (comic rack reading order basically) and assign the reading order numbers within mylar based on that, as the exact series, issue#s, comic id's,  and issue id's are all known - but just taking in the reading list by itself which was done at one point, messes up the matching to such a huge extent it's more trouble that it was worth.

**Comment by evilhero** [comment] 2015-07-29 18:49
Ok, is now fixed and will be in the next development commit. As you can see, the order is correct now starting with the Road to Civil War (Spider-Man):

![image](https://cloud.githubusercontent.com/assets/909424/8966679/a16af4aa-3600-11e5-8fd8-34c1c4c4b762.png)
and the Young Avengers & Runaways have all 4 issues in the correct spots now : 

![image](https://cloud.githubusercontent.com/assets/909424/8966705/cd15f67c-3600-11e5-9d87-17e1034dc486.png)

**Comment by weidercs** [comment] 2015-07-29 18:54
I'm assuming a delete/re-add will be necessary to re-sequence existing arcs?

**Comment by evilhero** [comment] 2015-07-29 19:13
Nope just a refresh of the arc .. no readding required.

**Closed** 2017-08-25 02:37 UTC
Labels: BUG, Support, WIP
