### ISSUE TITLE
ascii encoding issue

### ISSUE THREAD

**Issue by yongbi85** [evilhero/mylar#1304] opened 2016-06-11 18:23 UTC
Hello,

I'm running latest Mylar build on a Synology 5.2 5644 and i ran into this error when i tryed to import my comic collection.

Mylar Version: master
-- git build fba18e28656339dc2c195a2a91df782ec366e964.
Python Version : 2.7.11
OS : Synology 5.2 5644 Update 3

2016-06-11 20:07:31 ERROR   [IMPORT] Unable to complete the scan: 'ascii' codec can't encode character u'\xf1' in position 3: ordinal not in range(128)
2016-06-11 20:07:31 INFO    [IMPORT-CBZ] Successfully retrieved some tags. Lets see what I can figure out.
2016-06-11 20:07:31 INFO    issueinfo: [{'publisher': u'Marvel', 'letterer': u'Rus Wooton', 'title': u'Between Life and Death', 'webpage': u'http://comicvine.gamespot.com/arana-heart-of-the-spider-4-between-life-and-death/4000-106141/', 'series': u'Ara\xf1a: Heart of the Spider', 'notes': 'None', 'writer': u'Fiona Avery', 'summary': u'Spider-Man makes his first featured appearance, as part of April\u2019s Spider-Man Month! After her disastrous fight with a teen assassin leaves Anya up the creek without a paddle, it\u2019s up to Spidey to lend a hand to the new kid in town! Maybe he can give her tips on how to deal with members of the press \u2013 especially when they happen to be your investigative reporter dad tracking your new identity! Meanwhile, the harsh reality of collateral damage hits Anya like a ton of bricks\u2026and lands one of her teammates in Intensive Care. Enough with the destiny stuff already! It\u2019s time for Anya to take her fate into her own hands\u2026even if that means paying a terrible price.', 'volume': u'2005', 'penciller': u'Roger Cruz', 'issue_number': u'4', 'pagecount': u'24', 'colorist': u'UDON', 'year': u'2005', 'cover_artist': u'Mark Brooks', 'IssueImage': 'cache/temp.jpg?1465668451.9', 'month': u'6', 'inker': u'Victor Olazaba', 'day': 'None', 'editor': u'Axel Alonso, Jennifer Lee, Joe Quesada'}]
2016-06-11 20:07:31 INFO    [IMPORT-CBZ} Attempting to read tags present in filename: /volumeUSB3/usbshare/Reorg/Marvel/Araña - Heart of the Spider (2005)/Araña - Heart of the Spider 004 (2005).cbz

**Comment by evilhero** [comment] 2016-06-14 02:41
Yeah it looks like the importer is dying on importing tags that contain Unicode - I have it partially fixed on my local repo, but need to finish working thru the work flow to get it working properly. Not sure exactly when it stopped, but I'm using the exact filename you provided during my testing. 

Hopefully will have a fix out in a day or two.

**Comment by yongbi85** [comment] 2017-03-20 18:21
For your information (bumping an old topic) but the error is still there...
I've decided to change my folders for comics to new disposition so i wiped all the database and did a full import.
Got error on character like Araña or ½

**Comment by evilhero** [comment] 2017-03-20 18:30
I've tested specifically against Arana as an import title, and it imports fine. 

Make sure you're running an up to date branch of mylar, as like I did above I imported both the Arana series and various issues with different Unicode characters without any problems.

**Comment by yongbi85** [comment] 2017-03-20 18:37
I think it might be that as i also encounter the issue with couchpotato, do you have any idea where i can find this information on a synology ? (under linux command)

**Comment by evilhero** [comment] 2017-03-20 18:40
If you're in a Linux command, type in just 'python' to get the python cli. 
Then do the following:
```
import locale
locale.getdefaultlocale() 
```
And it should return your locale and your encoding. I'm just guessing that the encoding is non-UTF8

**Comment by yongbi85** [comment] 2017-03-20 18:41
UTF-8 is in there :
('en_US', 'UTF-8')

**Comment by evilhero** [comment] 2017-03-20 18:47
Can you run mylar in verbose mode, and do an import against the one series directory you're having problems with so I can see the error you're receiving? 

And can you confirm the branch / commit of mylar you're running as well.

**Comment by yongbi85** [comment] 2017-03-20 19:01
Mylar Version: master
-- git build 3fa3cfe032f0b567af34f902c3348da4f287222f.
Python Version : 2.7.13

If it is not verbose enought i will look at config.ini

Log for ASCII character (it directly shows there was a error) :


Timestamp	Level	Message
2017-03-20 19:59:54	INFO	Initiating mass import.
2017-03-20 19:59:49	INFO	Successfully scanned in directory. Enabling the importResults button now.
2017-03-20 19:59:49	INFO	[IMPORT-BREAKDOWN] Files that caused errors during the import: 0
2017-03-20 19:59:49	INFO	[IMPORT-BREAKDOWN] Files that were unable to be parsed: 0
2017-03-20 19:59:49	INFO	[IMPORT-BREAKDOWN] Files that had to be parsed: 1
2017-03-20 19:59:49	INFO	[IMPORT-BREAKDOWN] Files with ComicIDs successfully extracted: 0
2017-03-20 19:59:49	INFO	[IMPORT] Attempting to import 1 files into your watchlist.
2017-03-20 19:59:49	INFO	[IMPORT] Parsing/Reading of files completed!
2017-03-20 19:59:49	DEBUG	[IMPORT-CBZ] CVINFO_COMICID attached : 26671
2017-03-20 19:59:49	DEBUG	[IMPORT-CBZ] impid: 6757194
2017-03-20 19:59:49	DEBUG	[IMPORT-CBZ] Adding Spider-Man & Araña Special to the import-queue!
2017-03-20 19:59:49	DEBUG	[IMPORT-CBZ] Successfully retrieved CV IssueID for Spider-Man & Araña Special #1 [159841]
2017-03-20 19:59:49	DEBUG	[IMPORT-CBZ] Notes: Tagged with the ninjas.walk.alone fork of ComicTagger 1.20.0 using info from Comic Vine on 2016-06-20 23:11:02. [Issue ID 159841]
2017-03-20 19:59:49	DEBUG	[TRY]issue volume is: v1
2017-03-20 19:59:49	DEBUG	issue number SHOULD Be: 1
2017-03-20 19:59:49	DEBUG	[IMPORT-CBZ] Issue Number: 1
2017-03-20 19:59:49	DEBUG	Dynamic-ComicName: Spider|Man|ArañaSpecial
2017-03-20 19:59:49	DEBUG	[IMPORT-CBZ] Series Name: Spider-Man & Araña Special
2017-03-20 19:59:49	INFO	[IMPORT-CBZ] Successfully retrieved some tags. Lets see what I can figure out.
2017-03-20 19:59:49	INFO	issueinfo: [{'publisher': u'Marvel', 'letterer': u'Randy Gentile', 'title': u'The Hunter Revealed', 'webpage': u'http://comicvine.gamespot.com/spider-man-arana-special-1-the-hunter-revealed/4000-159841/', 'series': u'Spider-Man & Ara\xf1a Special', 'notes': u'Tagged with the ninjas.walk.alone fork of ComicTagger 1.20.0 using info from Comic Vine on 2016-06-20 23:11:02. [Issue ID 159841]', 'writer': u'Tania del Rio', 'summary': u'It all ends and begins right here! Ara\xf1a learns what the future of the Wasp/Spider-Clan battle holds, and what it means for her destiny as the Hunter! Sides are chosen, lives are lost and Ara\xf1a will never be the same!', 'volume': u'1', 'penciller': u'Jonboy Meyers, Tania del Rio, Jonboy Meyers, Tania del Rio', 'issue_number': u'1', 'pagecount': u'41', 'colorist': u'Guru-eFX', 'year': u'2006', 'cover_artist': u'Guru-eFX, Jonboy Meyers', 'IssueImage': 'cache/temp.jpg?1490036389.04', 'month': u'05', 'inker': u'Jim Royal, Mark Irwin, Tania del Rio', 'day': u'01', 'editor': u'Joe Quesada, Mark Paniccia, Nate Cosby'}]
2017-03-20 19:59:49	DEBUG	Extracting primary image P00001.jpg as coverfile for display.
2017-03-20 19:59:49	DEBUG	Extracting ComicInfo.xml to display.
2017-03-20 19:59:48	DEBUG	CBZ file detected. Checking for .xml within file
2017-03-20 19:59:48	INFO	[IMPORT-CBZ} Attempting to read tags present in filename: /volume1/RAID Proliant/Comic/Spider-Man & Arana Special (2006)/Spider-Man & Arana Special 001 (2006).cbz
2017-03-20 19:59:48	DEBUG	[IMPORT-CBZ] Metatagging checking enabled.
2017-03-20 19:59:48	INFO	CVINFO file located within directory. Attaching everything in directory that is valid to ComicID: 26671
2017-03-20 19:59:48	INFO	comlocation: /volume1/RAID Proliant/Comic/Spider-Man & Arana Special (2006)
2017-03-20 19:59:48	INFO	cvscanned_loc: ['/volume1/RAID Proliant/Comic/Spider-Man & Arana Special (2006)']
2017-03-20 19:59:48	INFO	comfilename: Spider-Man & Arana Special 001 (2006).cbz
2017-03-20 19:59:48	DEBUG	Analyzing : Spider-Man & Arana Special 001 (2006).cbz
2017-03-20 19:59:48	INFO	Successfully loaded 834 series from your watchlist.
2017-03-20 19:59:48	INFO	loading in the watchlist to see if a series is being watched already...
2017-03-20 19:59:48	DEBUG	[]
2017-03-20 19:59:48	INFO	[ERRORS] I have encountered 0 file-scanning errors during the scan, but have recorded the necessary information.
2017-03-20 19:59:48	INFO	However, 0 out of the 0 files are in a cbz format, which may contain metadata.
2017-03-20 19:59:48	INFO	I have not been able to determine what 0 files are
2017-03-20 19:59:48	INFO	I have successfully discovered & parsed a total of 1 files....analyzing now
2017-03-20 19:59:48	DEBUG	[PARSE-SUCCESS][SERIES: Spider-Man & Arana Special][ISSUE YEAR: 2006][ISSUE #: 001]
2017-03-20 19:59:48	DEBUG	series title possibly: Spider-Man & Arana Special
2017-03-20 19:59:48	DEBUG	issue verified as : 001
2017-03-20 19:59:48	DEBUG	issue_position: 4
2017-03-20 19:59:48	DEBUG	possible_issuenumbers: [{'position': 4, 'validcountchk': False, 'number': '001', 'mod_position': -1}]
2017-03-20 19:59:48	DEBUG	highest_series_position: 5
2017-03-20 19:59:48	DEBUG	year verified as: 2006
2017-03-20 19:59:48	DEBUG	year verified as : 2006
2017-03-20 19:59:48	DEBUG	sctd: 2017
2017-03-20 19:59:48	DEBUG	datecheck: [{'date': '2006', 'position': 5, 'mod_position': -1}]
2017-03-20 19:59:48	DEBUG	date: 2006
2017-03-20 19:59:48	DEBUG	checking date : 2006
2017-03-20 19:59:48	DEBUG	Comic: Spider-Man & Arana Special 001 (2006).cbz [/volume1/RAID Proliant/Comic/Spider-Man & Arana Special (2006)/Spider-Man & Arana Special 001 (2006).cbz] - 12980802 bytes
2017-03-20 19:59:48	DEBUG	CVINFO found: /volume1/RAID Proliant/Comic/Spider-Man & Arana Special (2006)
2017-03-20 19:59:48	INFO	Scanning comic directory: /volume1/RAID Proliant/Comic
2017-03-20 19:59:48	INFO	forcescan is: 0

**Comment by evilhero** [comment] 2017-03-20 19:06
I don't see any errors in the that log. Do you see the import Results Management button appear in the lower right side of the page after the scan was completed?

**Comment by yongbi85** [comment] 2017-03-20 19:06
Yes and when i push the mass import button it directly shows a popup "There was a error" without further infos

**Comment by evilhero** [comment] 2017-03-20 19:08
Which mass import button - the one on the import results page? 

Have you tried just doing one series to see if that works as intended?

**Comment by yongbi85** [comment] 2017-03-20 19:15
I'm currently trying.
It failed before when i used the mass import button on top right on the import results page when mixed with other series.
With manual button 



Timestamp	Level	Message
2017-03-20 20:14:10	ERROR	Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/mylar/share/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/volume1/@appstore/mylar/share/mylar/mylar/importer.py", line 601, in addComictoDB
moveit.movefiles(comicid, comlocation, imported)
File "/volume1/@appstore/mylar/share/mylar/mylar/moveit.py", line 30, in movefiles
renameit = helpers.rename_param(comicid, imported['ComicName'], impr['issuenumber'], orig_filename)
File "/volume1/@appstore/mylar/share/mylar/mylar/helpers.py", line 511, in rename_param
logger.fdebug('Series: ' + str(series))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf1' in position 16: ordinal not in range(128)
2017-03-20 20:14:10	DEBUG	Publisher: Marvel
2017-03-20 20:14:10	DEBUG	Issue Year : 2006
2017-03-20 20:14:10	DEBUG	Pretty Comic Issue is : 001
2017-03-20 20:14:10	DEBUG	Zero level supplement set to 00x. Issue will be set as : 001
2017-03-20 20:14:10	DEBUG	issue detected less than 10
2017-03-20 20:14:10	DEBUG	Zero Suppression set to : 00x
2017-03-20 20:14:10	DEBUG	issueno:1
2017-03-20 20:14:10	DEBUG	iss:1
2017-03-20 20:14:10	DEBUG	issueid is now : 159841
2017-03-20 20:14:10	DEBUG	annualize is None
2017-03-20 20:14:10	DEBUG	issueid:None
2017-03-20 20:14:10	DEBUG	issue#: 1
2017-03-20 20:14:10	DEBUG	comicid: 26671
2017-03-20 20:14:10	DEBUG	Renaming files according to configuration details : $Series $VolumeY $Issue ($Year)
2017-03-20 20:14:10	DEBUG	original comicname is : Spider-Man & Araña Special
2017-03-20 20:14:09	DEBUG	comlocation is : /volume1/Comics/Marvel/Spider-Man & Arana Special/V2006
2017-03-20 20:14:09	INFO	Mass import - Move files
2017-03-20 20:14:09	INFO	Updating complete for: Spider-Man & Araña Special
2017-03-20 20:14:09	DEBUG	initiating issue updating - info & status
2017-03-20 20:14:09	INFO	Now adding/updating issues for Spider-Man & Araña Special
2017-03-20 20:14:09	DEBUG	Finshed Annual checking.
2017-03-20 20:14:09	DEBUG	there are 0 search results...
2017-03-20 20:14:06	DEBUG	Default search mode - this will match on ALL search words
2017-03-20 20:14:06	DEBUG	[IMPORTER-ANNUAL] - No results, removing the year from the agenda and re-querying.
2017-03-20 20:14:06	DEBUG	there are 0 search results...
2017-03-20 20:14:02	DEBUG	Default search mode - this will match on ALL search words
2017-03-20 20:14:02	DEBUG	[IMPORTER-ANNUAL] - Annual Year:2006
2017-03-20 20:14:02	DEBUG	checking annual db
2017-03-20 20:14:02	DEBUG	issuetype: None
2017-03-20 20:14:02	DEBUG	latestissueinfo: None
2017-03-20 20:14:02	DEBUG	issuechk: None
2017-03-20 20:14:02	DEBUG	calledfrom: None
2017-03-20 20:14:02	DEBUG	comicissues:1
2017-03-20 20:14:02	DEBUG	comicname:Spider-Man & Araña Special
2017-03-20 20:14:02	DEBUG	comicid:26671
2017-03-20 20:14:02	DEBUG	issuedata call references...
2017-03-20 20:14:02	INFO	Sucessfully retrieved issue details for Spider-Man & Araña Special
2017-03-20 20:14:02	DEBUG	querying range from 0 to 100
2017-03-20 20:14:02	DEBUG	there are 1 search results...
2017-03-20 20:13:59	INFO	previous version detected as None - seeing if update required
2017-03-20 20:13:59	DEBUG	Successfully changed ownership and permissions [admin:administrators] / [0777 / 0777]
2017-03-20 20:13:58	DEBUG	comic image retrieval status code: 200
2017-03-20 20:13:57	INFO	Attempting to retrieve the comic image for series
2017-03-20 20:13:55	DEBUG	Successfully changed ownership and permissions [admin:administrators] / [0777 / 0777]
2017-03-20 20:13:55	INFO	[DIRECTORY-CHECK] Creating comic directory (0777) : /volume1/Comics/Marvel/Spider-Man & Arana Special/V2006
2017-03-20 20:13:55	WARNING	[DIRECTORY-CHECK] Could not find comic directory: /volume1/Comics/Marvel/Spider-Man & Arana Special/V2006
2017-03-20 20:13:55	DEBUG	new folder format: $Publisher/$Series/$VolumeY
2017-03-20 20:13:55	DEBUG	No version # found for series, removing from folder format
2017-03-20 20:13:55	INFO	Sucessfully retrieved details for Spider-Man & Araña Special
2017-03-20 20:13:55	INFO	2006
2017-03-20 20:13:55	INFO	Now adding/updating: Spider-Man & Araña Special
2017-03-20 20:13:55	DEBUG	{'ComicIssues': u'1', 'ComicName': u'Spider-Man & Ara\xf1a Special', 'ComicVersion': 'None', 'FirstIssueID': u'159841', 'ComicPublisher': u'Marvel', 'ComicYear': u'2006', 'ComicImageALT': u'http://comicvine.gamespot.com/api/image/scale_small/833315-34291_20070228014958_large.jpg', 'ComicURL': u'http://comicvine.gamespot.com/spider-man-arana-special/4050-26671/', 'Type': 'Print', 'ComicImage': u'http://comicvine.gamespot.com/api/image/scale_large/833315-34291_20070228014958_large.jpg', 'Aliases': 'None'}
2017-03-20 20:13:55	DEBUG	comic[ComicVersion]:None
2017-03-20 20:13:55	DEBUG	vari is set to: no
2017-03-20 20:13:55	DEBUG	number of issues CV says it has: 1
2017-03-20 20:13:55	DEBUG	number of issues I counted: 1
2017-03-20 20:13:52	INFO	[IMPORT] Initial Import complete (I might still be populating the series data).
2017-03-20 20:13:52	INFO	Attempting to add directly by ComicVineID: 26671
2017-03-20 20:13:52	INFO	now adding...
2017-03-20 20:13:46	INFO	There is only one result...automagik-mode enabled for Spider-Man & Araña Special :: 26671

**Comment by yongbi85** [comment] 2017-03-20 19:17
Python 2.7.9 (default, Apr  1 2016, 11:53:29)
[GCC 4.6.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getdefaultlocale()
('en_US', 'UTF-8')

**Comment by evilhero** [comment] 2017-03-20 19:19
That's a problem with the logging in the renamer, not so much the importer... The str references should have all been removed - not sure how that got missed. 

I'll try and push a commit out shortly to fix that.

**Comment by yongbi85** [comment] 2017-03-20 19:20
Thanks a lot again for your free work.
Your app is really amazing.

**Comment by yongbi85** [comment] 2017-03-20 20:54
Also, not sure if i should open a new issue but since it has to do with the renamer... whenever i try to rename some comic with MU, INH etc. in it i would get an error on the renaming and the following message in debug


Timestamp	Level	Message
2017-03-20 21:51:51	DEBUG	ALPHANUMERIC EXCEPTION : [INH]
2017-03-20 21:51:51	DEBUG	issueid is now : 442923
2017-03-20 21:51:51	DEBUG	annualize is None
2017-03-20 21:51:51	DEBUG	issueid:None
2017-03-20 21:51:51	DEBUG	issue#: 20.INH
2017-03-20 21:51:51	DEBUG	comicid: 53725


Nothing else written in the log, it just stops there and doesnt rename.

**Comment by evilhero** [comment] 2017-03-20 21:02
It depends on how you are doing it since post-processing, importing and manual renaming all use different rename functions (although I think that the import & manual rename use the same function). 

Create a separate issue for the rename problem and attach the same log so that I can track it easier. Since it doesn't have anything to do with ascii encoding, it should be in it's own issue on github.

**Comment by yongbi85** [comment] 2017-04-02 12:48
Sadly i have to bump this topic again... still got an issue with ascii characters

Mylar Version: master
-- git build 32134e796e267cf7aa3004abe4626e4fd61c644a.
Python Version : 2.7.13

OS : Synology 5.2

2017-04-02 14:37:26	DEBUG	[MANUAL META-TAGGING] Unable to write metadata successfully - check mylar.log file.
2017-04-02 14:37:26	WARNING	[META-TAGGER][COMIC-TAGGER][CBR-TO-CBZ] Failed to convert cbr to cbz - check permissions on folder : /usr/local/mylar/var/cache and/or the location where Mylar is trying to tag the files from.
2017-04-02 14:37:26	DEBUG	[META-TAGGER] Absolute path to script: /usr/local/mylar/env/bin/python
2017-04-02 14:37:26	DEBUG	[META-TAGGER] Executing command: ['/usr/local/mylar/env/bin/python', '/usr/local/mylar/share/mylar/comictagger.py', '-e', '--delete-rar', u'/usr/local/mylar/var/cache/mylar_8BIvj9/Fantastic Four v3 \xbd (1998).cbr']
2017-04-02 14:37:26	DEBUG	[META-TAGGER] Enabling ComicTagger script: ['/usr/local/mylar/env/bin/python', '/usr/local/mylar/share/mylar/comictagger.py'] with options: ['-e', '--delete-rar', u'/usr/local/mylar/var/cache/mylar_8BIvj9/Fantastic Four v3 \xbd (1998).cbr']
2017-04-02 14:37:26	DEBUG	[META-TAGGER] CR Tagging enabled.


Also this is how the name shows if i connect in ssh and look into the cache folder of mylar

mylar_77UWu_/Fantastic Four v3 Â½ (1998).cbr


And in the original comic folder

-rwxrwxrwx    1 admin    users     10414557 Apr  2 14:35 Fantastic Four v3 Â½ (1998).cbr

But on windows samba share it does shows like Fantastic Four v3 ½ (1998).cbr


There is no permission issue by the way, everything is admin:users and mylar is run by admin user and all the other comics are successfully metatagged.

**Comment by evilhero** [comment] 2017-04-02 13:32
Please open this as a different issue. The error presented is different than the one which started the issue, so it requires a separate issue. 

This error relates to comictagger, which is a 3rd party app that's been included within mylar and modified by myself in order to use with mylar. This is dealing with comictagger and it's ability to handle unicode filenames or how it's being passed to it. Since comictagger isn't supported anymore, I'll have to delve into the code and see what's happening.

**Comment by yongbi85** [comment] 2017-04-02 13:33
You got it sir, i'm opening a separate thread for that one.

**Closed** 2019-05-09 13:02 UTC
Labels: BUG, FIX (needs verification), Support
