### ISSUE TITLE
local variable 'comicid' referenced before assignment

### ISSUE THREAD

**Issue by gsemet** [evilhero/mylar#1607] opened 2017-03-28 16:58 UTC
Exception in post process (api call by sabnzbd post processor)

```
Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/PostProcessor.py", line 1083, in Process
renamed_file = helpers.rename_param(comicid, comicname, issuenumber, dfilename, issueid=issueid, arc=sarc)
UnboundLocalError: local variable 'comicid' referenced before assignment
```

Logs before:
```
2017-03-28 18:29:03	INFO	[POST-PROCESSING] Could not detect as a standard issue - checking against annuals.
2017-03-28 18:29:03	INFO	[POST-PROCESSING] issuenzb not found.
2017-03-28 18:29:03	INFO	[POST-PROCESSING] One-off STORYARC mode enabled for Post-Processing for STORYARCNAME
2017-03-28 18:29:03	INFO	[POST-PROCESSING] Story Arc Directory set to : /comics/StoryArcs/STORYARCNAME
2017-03-28 18:29:03	INFO	[POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /comics/StoryArcs/STORYARCNAME
```

Seems related because I wanted the story arc alone without "wanting" the album. I though the issues would be automatically downloaded

**Comment by evilhero** [comment] 2017-03-28 20:59
Well they get searched for when you click on the search for missing - I believe I have the comicid fixed on my local repo, but I honestly had forgotten about it until I saw this. 

I'll push out a fix later today for it that should fix the problem you're experiencing when post-processing.

**Comment by Stibbons** [comment] 2017-04-08 15:16
Maybe this can help, but it seems to occurs when I look for a story arc and add issue without having added the issue in the main view in the first place. I basically look for story arc with issues I don't have yet. 
I expect only to have the story arc folder filled up, and if needed the comics directory automatically added, which does not seems the case. This can explain why there is no comicid, because the comic itself has been added in the db. Wanted comics in "Story Arc Management" page does not appear in the "Comic details page".

ComicRN works fine for the same comic but when I download it from the comic page (/comicDetails?ComicID=XXXX).

**Comment by evilhero** [comment] 2017-04-08 15:23
When mylar populates the arc it reverse look up's all the issueids in the arc in order to get the relevant comicids. I've tested doing what you're doing (do a grab from the arc detail page) and it pulls it down and auto-processes into the arc directory with no issues. 

Do you have the story arc directory option enabled and what are you choosing to do (copy/move/link) with the files?

**Comment by Stibbons** [comment] 2017-04-08 16:25
Yes, story arc directory set, with a name set to `$arc ($spanyears)` (this folder is well created with a cvinfo in it). I see there is also an empty folder create with only the arc name (like it was `$arc`). I have set to hardlinking the issue, I am switching to copy. Hardlinking is supposed to work fine on Linux.

**Comment by evilhero** [comment] 2017-04-08 16:43
Hardlinking will not work across different partitions - it's looking to hardlink from your post-processing location to your story arc folder (since you're said you don't have these issues on your watchlist). So if  your download folder is located on a diff partition, hard links aren't going to work (ie. Do a ```df -h``` from the cli if you want to see all the different partitions / file systems you have)

**Comment by Stibbons** [comment] 2017-04-08 16:58
no they are on the same partition. Comics a put in `/document/comics/` and story arc in `/document/comics/StoryArcs`. I have the same issue with "copy". I may have incompatible options that result in getting code path in `PostProcessor.py` where `comicid` is never set... I strongly suspect the `One-off STORYARC mode`, it results in an `issuearcid` and not a `comicid`, if you see the logs:

```
08-Apr-2017 18:32:27 - DEBUG   :: Post-Processing : [POST-PROCESSING] nzb name: The.Comic.Name
08-Apr-2017 18:32:27 - DEBUG   :: Post-Processing : [POST-PROCESSING] nzb folder: /downloads/complete/The.Comic.Name
08-Apr-2017 18:32:27 - DEBUG   :: Post-Processing : [NZBNAME]: The.Comic.Name
08-Apr-2017 18:32:27 - DEBUG   :: Post-Processing : [NZBNAME] nzbname (remove chars): The.Comic.Name
08-Apr-2017 18:32:27 - DEBUG   :: Post-Processing : [NZBNAME] nzbname (remove extensions, double spaces, convert underscores to spaces): The Comic Name
08-Apr-2017 18:32:27 - DEBUG   :: Post-Processing : [POST-PROCESSING] After conversions, nzbname is : The.Comic.Name
08-Apr-2017 18:32:27 - DEBUG   :: Post-Processing : [POST-PROCESSING] Issueid: S42233_8125
08-Apr-2017 18:32:27 - INFO    :: Post-Processing : [POST-PROCESSING] Could not detect as a standard issue - checking against annuals.
08-Apr-2017 18:32:27 - INFO    :: Post-Processing : [POST-PROCESSING] issuenzb not found.
08-Apr-2017 18:32:27 - INFO    :: Post-Processing : [POST-PROCESSING] One-off STORYARC mode enabled for Post-Processing for Comic Name
08-Apr-2017 18:32:27 - INFO    :: Post-Processing : [POST-PROCESSING] Story Arc Directory set to : /comics/StoryArcs/Comic Name
08-Apr-2017 18:32:27 - DEBUG   :: Post-Processing : [POST-PROCESSING] issuearcid:42233_8125
08-Apr-2017 18:32:27 - DEBUG   :: Post-Processing : [META-TAGGER] dirName:/downloads/complete/The.Comic.Name
08-Apr-2017 18:32:27 - DEBUG   :: Post-Processing : ComicTagger Path location for internal comictagger.py set to : /app/mylar/comictagger.py
08-Apr-2017 18:32:27 - DEBUG   :: Post-Processing : [META-TAGGER] Filename is : The Comic Name 01 (1991).cbr
08-Apr-2017 18:32:27 - WARNING :: Post-Processing : [META-TAGGER] Unable to create temporary directory to perform meta-tagging. Processing without metatagging.
08-Apr-2017 18:32:27 - DEBUG   :: Post-Processing : [POST-PROCESSING] Unable to write metadata successfully - check mylar.log file. Attempting to continue without metatagging...
08-Apr-2017 18:32:27 - INFO    :: Post-Processing : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /comics/StoryArcs/Comic Name
08-Apr-2017 18:32:27 - ERROR   :: Post-Processing : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/mylar/mylar/PostProcessor.py", line 1083, in Process
    renamed_file = helpers.rename_param(comicid, comicname, issuenumber, dfilename, issueid=issueid, arc=sarc)
UnboundLocalError: local variable 'comicid' referenced before assignment
```

**Comment by evilhero** [comment] 2017-04-08 17:13
```WARNING :: Post-Processing : [META-TAGGER] Unable to create temporary directory to perform metatagging. Processing without metatagging.```
It can't create the temp directory in order to perform the metatagging. It  needs to copy the cbr/cbz to the cache/mylar_xxxxx/ location and then does it's conversion therein. Make sure the user running mylar has full permissions in the cache folder to perform this. 

Keep in mind too that you can't hard link a cbr to a cbz (meaning metatagging would work, but linking would fail because the files are different after conversion)

**Comment by Stibbons** [comment] 2017-04-08 18:35
I just tested by disabling the metatagging. cache folder has plenty of `mylar_*` and a bunch of nzb, so i don't think there is an permission issue. Disk space is ok too.

So, I tested by downloading the same comic without metatagging, copy (no hardlink). When there is no story arc found, only added in my wanted list. It works. When it appears in one of the story arc, it fails with the same issue than before:
```
08-Apr-2017 20:29:24 - INFO    :: CP Server Thread-3 : ComicRN.py version: 1.01 -- autoProcessComics.py version: 1.0
08-Apr-2017 20:29:24 - INFO    :: CP Server Thread-3 : Starting postprocessing for : The.Comic.Name.01.1991
08-Apr-2017 20:29:24 - DEBUG   :: Post-Processing : [POST-PROCESSING] nzb name: The.Comic.Name.01.1991
08-Apr-2017 20:29:24 - DEBUG   :: Post-Processing : [POST-PROCESSING] nzb folder: /downloads/complete/The.Comic.Name.01.1991
08-Apr-2017 20:29:24 - DEBUG   :: Post-Processing : [NZBNAME]: The.Comic.Name.01.1991
08-Apr-2017 20:29:24 - DEBUG   :: Post-Processing : [NZBNAME] nzbname (remove chars): The.Comic.Name.01.1991
08-Apr-2017 20:29:24 - DEBUG   :: Post-Processing : [NZBNAME] nzbname (remove extensions, double spaces, convert underscores to spaces): The Comic Name 01 1991
08-Apr-2017 20:29:24 - DEBUG   :: Post-Processing : [POST-PROCESSING] After conversions, nzbname is : The.Comic.Name.01.1991
08-Apr-2017 20:29:24 - DEBUG   :: Post-Processing : [POST-PROCESSING] Issueid: S12345_6789
08-Apr-2017 20:29:24 - INFO    :: Post-Processing : [POST-PROCESSING] Could not detect as a standard issue - checking against annuals.
08-Apr-2017 20:29:24 - INFO    :: Post-Processing : [POST-PROCESSING] issuenzb not found.
08-Apr-2017 20:29:24 - INFO    :: Post-Processing : [POST-PROCESSING] One-off STORYARC mode enabled for Post-Processing for Comic Name
08-Apr-2017 20:29:24 - INFO    :: Post-Processing : [POST-PROCESSING] Story Arc Directory set to : /comics/StoryArcs/Comic Name
08-Apr-2017 20:29:24 - DEBUG   :: Post-Processing : [POST-PROCESSING] issuearcid:42233_8125
08-Apr-2017 20:29:24 - INFO    :: Post-Processing : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /comics/StoryArcs/Comic Name
08-Apr-2017 20:29:24 - ERROR   :: Post-Processing : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/mylar/mylar/PostProcessor.py", line 1083, in Process
    renamed_file = helpers.rename_param(comicid, comicname, issuenumber, dfilename, issueid=issueid, arc=sarc)
UnboundLocalError: local variable 'comicid' referenced before assignment
```

**Comment by evilhero** [comment] 2017-04-08 22:16
I just realized - you're running the master branch based on what you're experiencing. The fix for this error (and some other post-processing errors related to arcs) just went into development 4 days ago (specifically it was commit 2246aacc7dcb74f31db0f42f0e404fbc5a1fcc5f). It'll probably make it into master at some point this week, but it was a fairly involved commit and I need feedback if it's working or not as intended before I push it into master (in case it makes things worse)...

**Comment by Stibbons** [comment] 2017-04-09 08:39
I switched to development branch to test it. Things are better indeed!

There is no problem with comics that appears in saga and in wanted comic list.

But for comics that does not belong to my wishlist, I get this error on post processing:

```
09-Apr-2017 10:29:59 - INFO    :: CP Server Thread-3 : ComicRN.py version: 1.01 -- autoProcessComics.py version: 1.0
09-Apr-2017 10:29:59 - INFO    :: CP Server Thread-3 : Starting postprocessing for : Name.Of.The.Comic.2010
09-Apr-2017 10:29:59 - INFO    :: Post-Processing : [POST-PROCESSING] Could not detect as a standard issue - checking against annuals.
09-Apr-2017 10:29:59 - INFO    :: Post-Processing : [POST-PROCESSING] issuenzb not found.
09-Apr-2017 10:29:59 - INFO    :: Post-Processing : [POST-PROCESSING] One-off STORYARC mode enabled for Post-Processing for The Arc Name
09-Apr-2017 10:29:59 - ERROR   :: Post-Processing : Uncaught exception: Traceback (most recent call last):
  File "/app/mylar/mylar/logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/app/mylar/mylar/PostProcessor.py", line 1034, in Process
    grdst = helpers.arcformat(arc['StoryArc'], helpers.spantheyears(arcdata['StoryArcID']), arcpub)
NameError: global name 'arc' is not defined
```

**Closed** 2021-01-01 21:06 UTC
