### ISSUE TITLE
Post-Processing is not working

### ISSUE THREAD

**Issue by Lusiphur** [evilhero/mylar#1454] opened 2016-11-09 20:27 UTC
Please note I did try to register for the forum but never got an activation mail.

2016-11-09 20:11:21	DEBUG	'Traceback (most recent call last):\n File "/opt/Mylar/mylar/scheduler.py", line 78, in runAction\n self.action.run()\n File "/opt/Mylar/mylar/PostProcessor.py", line 2000, in run\n result = PostProcess.Process()\n File "/opt/Mylar/mylar/PostProcessor.py", line 533, in Process\n if int(watch_issueyear) == int(watchmatch[\'issue_year\']):\nTypeError: int() argument must be a string or a number, not \'NoneType\'\n'

Version is latest development
Mylar Version: development
-- git build 7c7aef0d38d8fe58fd3d67398f888a15382c3b73.
Python Version : 2.7.12

**Comment by evilhero** [comment] 2016-11-09 21:02
The forums just moved to a new provider, so I'm working out some of the kinks. I'll look into the lack of email tho for sure. 

That should have been fixed, the error you received, as it was due to the filename not having a year present in it. 

Can you confirm the filename you're trying to post-process?

**Comment by Lusiphur** [comment] 2016-11-09 21:04
The filename was ..
Wonder_Woman_010-2017-2_covers-digital-Minutemen-Thoth-.cbz
Note, I am running on Linux so I have a script that detox's the filenames before the move.

**Comment by evilhero** [comment] 2016-11-09 21:55
Ok so what is the actual name that Mylar is trying to post-process against? The filename or the detoxed one? 
As it stands based on that filename, mylar wouldn't be able to parse it properly as using a dash in lieu of a space (or in place of brackets) causes too many gaps in the parsing logic.

**Comment by Lusiphur** [comment] 2016-11-09 21:58
Mylar is processing the detoxed name as I posted here. Simple fix is for me to detox after the move. Thanks for the help!

**Comment by evilhero** [comment] 2016-11-09 22:00
Or just use the file format function within mylar to have it do it for you during the post-processing run ;)

**Comment by haygoodhtpc** [comment] 2016-11-11 00:21
I've got the same issue. 

2016-11-10 18:19:45	ERROR	Uncaught exception: Traceback (most recent call last):
File "/app/mylar/mylar/logger.py", line 158, in new_run
old_run(*args, **kwargs)
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/app/mylar/mylar/PostProcessor.py", line 484, in Process
if int(watch_issueyear) == int(watchmatch['issue_year']):
TypeError: int() argument must be a string or a number, not 'NoneType'

It seems that the issue is with 2017 in the filename, e.g. "Marvel.Universe.Guardians.of.the.Galaxy.014.2017"

**Comment by evilhero** [comment] 2016-11-11 03:14
This has been fixed in dev, as #1438.

Im just guessing that you're either running the master branch, or you're not up to date?

**Comment by haygoodhtpc** [comment] 2016-11-11 04:20
I'm running Linuxserver.io's docker image. Let me see if I can pull from the dev branch.

**Comment by haygoodhtpc** [comment] 2016-11-11 04:31
I changed the branch in config.ini to "develop" but it's not pulling the latest commit. Must be a thing with the docker container.

**Comment by evilhero** [comment] 2016-11-11 04:34
Yes I believe the .io docker folks have said that they're locked on master amd have no intention of allowing for dev change. 

I should be able to merge dev to master either tonight / tomorrow. Just need to make sure one thing is working correctly before I put it into master.

**Comment by evilhero** [comment] 2016-11-11 16:55
dev merged into master just moments ago. Should be good to go now on the master branch.

**Closed** 2021-01-01 21:06 UTC
