### ISSUE TITLE
SUGGESTION: clickable index/alphabet at top/bottom of page

### ISSUE THREAD

**Issue by kingfenix** [evilhero/mylar#1988] opened 2018-06-14 18:27 UTC
How hard would it be to add a quick easy way to jump to a certain letter at top/bottom of the page? For example currently if I want to get to Marvel two-in-one in my collection sorted by title, then I have to hit next many many times, would be nice if I could just click on a "m" somewhere.

**Comment by LeeThompson** [comment] 2018-06-14 21:09
It would also be cool if the navigation buttons were on both the top and bottom of the page.

**Comment by kingfenix** [comment] 2018-06-14 23:59
and that their width didnt change making them jump around from page to page, lol

**Comment by barbequesauce** [comment] 2018-06-18 17:59
@kingfenix - working on the alphabetical index on the side now (assuming you want something like what Plex uses). It looks like I can only key off one column, I'm assuming SeriesName is the one you'd want to work from?

@LeeThompson - sixteen hours of code review, forum searching, and documentation diving has led me to believe that DataTables (the JS library being used) does not allow the pagination control to exist more than once for a given table. Do you have an example where this is being done with DataTables, so I can take a look at the code?

@kingfenix - the width thing is another DataTables "feature". As far as I can see they don't predetermine the width of all cells in the table, so when they load the next screen the width is recalculated...

**Comment by LeeThompson** [comment] 2018-06-18 18:01
@barbequesauce I try not to touch javascript personally so unfortunately I do not have any examples. :)

**Comment by barbequesauce** [comment] 2018-06-18 19:22
@LeeThompson Turns out I didnt search hard enough :) Check out PR #2000.

**Comment by LeeThompson** [comment] 2018-06-18 20:15
@barbequesauce awesome sauce!

**Comment by kingfenix** [comment] 2018-06-19 14:05
@barbequesauce - yes something like plex bar on the side will be AWESOME, ty for that. instead of allowing the width to be calculated on those bottom nav items, how about just making them static width and large enough to handle large numbers, then someone could leave their mouse in one place to click through pages...

**Comment by evilhero** [comment] 2018-06-19 15:08
The problem is that datatables has it's own way of handling pagination that doesn't allow for dynamic stuff like this in all situations. BBQ did the PR for the pagination at top / bottom (which I've known how to do prior, but didn't do it) - but the problem also becomes screen real-estate and a dizzying number of buttons appear in the pagination that cause f'd-up displays because it's always readjusting the page numbering (again, datatables). So making it static & large enough isn't an option, but there are some tricks that can be done to make it so that you can keep the mouse stationary and just click like a madman to go from page to page.

Also as far as as the letter navigation (which again, BBQ is working on - but the whole screen real-estate might come into factor when you're alphabetising the option) - but I'm sure based on hows things work with Mylar and our irc, we'll be chatting about this amongst ourselves as we go ;)

**Comment by kingfenix** [comment] 2018-06-19 15:11
again, thanks evil appreciate you and BBQ both!

**Comment by evilhero** [comment] 2018-06-19 17:50
Navigation should be fixed in development now (thnx for starting things bbq!) - this is only on the main/home page and the manage comics pages thus far. 

Shouldn't jump around when flipping between pages as well since I set a limit on the number of page boxes to display. Trying to get a dropdown working in conjunction with the page numbering, but not looking like it's going to work the way things are currently.

Pretty sure bbq has got a handle on the alphabetic stuff, so I'll leave that in his capable hands (although he knows how to find me if he wants some help).

**Comment by kingfenix** [comment] 2018-06-19 18:47
thanks guys! Hopefully it wont take long to hit master as I run mylar from UNRAID docker...unable to get development there.

**Comment by barbequesauce** [comment] 2018-07-20 00:42
Added to development, although there’s a bug regarding secondary sorts I’ll still working through...

**Comment by barbequesauce** [comment] 2019-12-31 21:22
Think we can close this out now :)

**Closed** 2021-01-01 21:05 UTC
Labels: enhancement
