### ISSUE TITLE
bug on adding comics in mass

### ISSUE THREAD

**Issue by Nonobis** [evilhero/mylar#919] opened 2015-01-11 18:32 UTC
Hi, 

Sometime, when i add many new comics i have this error.

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/volume1/@appstore/mylar/share/mylar/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/volume1/@appstore/mylar/share/mylar/mylar/webserve.py", line 73, in home
    comics = helpers.havetotals()
  File "/volume1/@appstore/mylar/share/mylar/mylar/helpers.py", line 1147, in havetotals
    elif 'present' in comic['ComicPublished'].lower() or ( today()[:4] in comic['LatestDate']):
TypeError: argument of type 'NoneType' is not iterable

i am on "development" branch on synology.
thx

**Comment by evilhero** [comment] 2015-01-12 02:06
How are you adding the comics into mylar?  

Was there any errors when any of the  series were added?

**Comment by Nonobis** [comment] 2015-01-12 15:55
for each comics, i open a new tab in firefox from weekly pull list.

**Comment by evilhero** [comment] 2015-01-12 16:51
Are you waiting for each series to get fully added before you start adding ?

If you were to add a series on one tab, then flip back to a previous tab (or any of the other tabs) and then refresh the main page (where it lists all the series you have) - you'll get that error because it's trying to load in the data for one of the series still and hasn't fully populated the data that's required for it to be listed on the home page properly.

I'll look into a fix - but in the meantime, you just have to refresh the page once you get that error and it will load up fine.

**Comment by Nonobis** [comment] 2015-01-13 08:50
i switch between tabs, but i don't think i have refreshed the pull list. i open a series and then add x sub-series on detail screen, then i wait than x tab are completely loaded.

i don't known python (.Net programmer ...sorry ) but maybe you can the load the data in a separate thread every time someone click on import series ?

**Comment by evilhero** [comment] 2015-01-13 12:41
For every request to add a series, a new thread is created. Like I said, it's not the threading that's causing the issue, but the fact that the information hasn't fully loaded yet. 

I was able to reproduce the exact same error by opening up two tabs off the weekly pull/add series links and then flipping back to the initial pull tab and clicking on the mylar icon. Fix will be in the next development commit.

**Comment by MoOx** [comment] 2015-01-18 08:01
I've tried to import a folder with some comics & now I'm getting this error again, but this time it doesn't go away with time (like in #923).
BTW since I won't be able to do an update from mylar itself, is there a way to update mylar from cli ? (I have installed mylar on a synology nas)

**Comment by evilhero** [comment] 2015-01-18 08:28
If you're importing a folder, I'd have to see the mylar.log file to see what's going on - or if there are any errors therein that are logged.

Currently there isn't a way to update via the cli (it's on the hitlist). Is there a reason why you can't update from within Mylar itself ? If you installed via the synopackage - are you running the most current version of Mylar (and on the development branch ?

**Closed** 2017-08-25 00:59 UTC
Labels: BUG, FIX (needs verification), Verified bug
