### ISSUE TITLE
looping error message in logs "no file found where it should ...- is there another script that moves things after completion

### ISSUE THREAD

**Issue by johntruongstn** [evilhero/mylar#1816] opened 2017-12-15 06:50 UTC
When i check my logs, i get this running every millisecond..

How do i clear this error? I tried going into history and deleting everything but still doesn't work.

Thank you,

2017-12-14 23:47:41 | INFO | found matching completed item in history. Job has a status of Completed
-- | -- | --
2017-12-14 23:47:41 | INFO | no file found where it should be @ E:\Finished\The.Flash.036.2018 - is there another script that moves things after completion ?
2017-12-14 23:47:41 | INFO | found matching completed item in history. Job has a status of Completed
2017-12-14 23:47:41 | INFO | no file found where it should be @ E:\Finished\The.Flash.036.2018 - is there another script that moves things after completion ?

**Comment by evilhero** [comment] 2017-12-15 12:45
Which version / commit of mylar are you running?

Do you have completed download handling enabled for either sab/nzbget?

Do you have some script that runs after the job completes  that alters the final location / name of the file or folder (ie. Did you remove comicRN.py or any other script that runs on completion that's assigned to your comics category)?

**Comment by BanditBanditBandit** [comment] 2019-03-08 04:16
I am having an exact same issue as this one, hope you dont mind that I necro this thread since its still open instead of opening a new one. I have the import script running from the nzbtomedia for both my torrent client and the sabnzbd. It spits out the files into the /downloads/#CompletedComic folder and returns a success back to sabnzbd and does some stuff with the API for mylar and all that goodness.

`

2019-03-07 20:13:51 | INFO | no file found where it should be @ - is there another script that moves things after completion ?
-- | -- | --
2019-03-07 20:13:51 | DEBUG | [CONV] Thu, 22 Mar 2018 00:55:57 +0000 is after store date of 2017-04-19
2019-03-07 20:13:51 | INFO | found matching completed item in history. Job has a status of Running
2019-03-07 20:13:51 | DEBUG | usedate: 2017-04-19
2019-03-07 20:13:51 | INFO | no file found where it should be @ - is there another script that moves things after completion ?
2019-03-07 20:13:51 | DEBUG | date used is : 2017-04-19
2019-03-07 20:13:51 | INFO | found matching completed item in history. Job has a status of Running
2019-03-07 20:13:51 | DEBUG | store date used is : 2017-04-19
2019-03-07 20:13:51 | INFO | no file found where it should be @ - is there another script that moves things after completion ?
2019-03-07 20:13:51 | DEBUG | size given as: 33.6 MB
2019-03-07 20:13:51 | INFO | found matching completed item in history. Job has a status of Running
2019-03-07 20:13:51 | DEBUG | comsize_b: 35248000
2019-03-07 20:13:51 | INFO | no file found where it should be @ - is there another script that moves things after completion ?
2019-03-07 20:13:51 | DEBUG | sub:Harley.Quinn.040.2018.2.covers.Digital.Zone-Empire
2019-03-07 20:13:51 | INFO | found matching completed item in history. Job has a status of Running
2019-03-07 20:13:51 | DEBUG | checking search result: Harley.Quinn.040.2018.2.covers.Digital.Zone-Empire
2019-03-07 20:13:51 | INFO | no file found where it should be @ - is there another script that moves things after completion ?
2019-03-07 20:13:51 | DEBUG | 2017 - not right - years do not match
2019-03-07 20:13:51 | INFO | found matching completed item in history. Job has a status of Running
2019-03-07 20:13:51 | DEBUG | year looking for: 2017
2019-03-07 20:13:51 | INFO | no file found where it should be @ - is there another script that moves things after completion ?
2019-03-07 20:13:51 | DEBUG | year detected: 2018

`

I cleared the history and put everything back to wanted and it just keeps looping this error.
One of the main things that is an issue is not being able to see the que of ddl that is happening in the background, or be able to cancel them if they are causing issues?

**Comment by BanditBanditBandit** [comment] 2019-03-08 04:26
is this an incompatibility with having both post processing enabled in the settings? trying that and will reply with more information.

**Comment by barbequesauce** [comment] 2019-03-08 04:32
Thanks for this, but the same questions apply -

Do you have both Completed Download Handling and ComicRN enabled? Can you provide the actual debug log (not a C&P from the log page)?

Which version / commit of mylar are you running?

Do you have some script that runs after the job completes that alters the final location / name of the file or folder (ie. Did you remove comicRN.py or any other script that runs on completion that's assigned to your comics category)?

There’s a lot of variables out there to match before we say you have the exact same issue....

**Comment by BanditBanditBandit** [comment] 2019-03-08 05:17
OK thanks, I will try to clarify.
I had post processing turned on because it was my understanding that my other script was putting the files with proper formating in the completedcomic folder they would have downloaded into otherwise.
[mylar.zip](https://github.com/evilhero/mylar/files/2944430/mylar.zip)
I just grabbed this off github a few days ago. 

Mylar Version: master
-- source build None
Python Version : 2.7.15
Language : en_US.cp1252

**Comment by BanditBanditBandit** [comment] 2019-03-08 05:24
Now that I have post processing turned off the DDL files will not complete any longer.

**Comment by evilhero** [comment] 2019-03-08 05:25
Turn off CDH (Completed Download Handling) in Mylar if you're using nzb2media, as that changes the final  location where Mylar thinks things are which results in the error. However, leave Post-processing enabled as that's required for nzb2media to make calls to Mylar to post-process items.

Nzb2media is akin to ComicRN in that neither can be used if you have CDH enabled within Mylar.

**Comment by BanditBanditBandit** [comment] 2019-03-08 06:41
thank you very much for the input. Not only has this fixed this issue but it stopped the program from spiking cpu usage. it was consistantly reaching 15-30% cpu.

**Comment by BanditBanditBandit** [comment] 2019-03-08 08:11
[mylar.zip](https://github.com/evilhero/mylar/files/2944889/mylar.zip)
seems other issues popped up regarding post processing.
`                for fl in filelist['comiclist']:
`

**Comment by evilhero** [comment] 2019-03-08 14:28
Unfortunately there's nothing in that log that is of any benefit in troubleshooting a post-processing related problem, especially since it's just INFO level logging.

I'm going to close this issue, since the current issue was resolved. If you're having post-processing something, please create a new issue indicating what the problem is and make sure to include debug level logs in order to help assist us.

**Closed by evilhero** 2019-03-08 14:28 UTC

**Comment by BanditBanditBandit** [comment] 2019-03-08 17:11
thanks, will do
