### ISSUE TITLE
Comic Tagging not working

### ISSUE THREAD

**Issue by partymike** [evilhero/mylar#1230] opened 2016-03-12 10:52 UTC
Hi, comics are downloaded and post processed into the correct folder & renamed as per the software settings but no comic tags are being written, I am having to use tagging in comic rack instead.
## I cannot see any errors in the log, other than a "blank" where maybe there should be something?

12-Mar-2016 10:25:04 - INFO    :: Post-Processing : [POST-PROCESSING] [1/1] Starting Post-Processing for **_. issue: 1
12-Mar-2016 10:25:05 - INFO    :: Post-Processing : Archive exported successfully to: ***_. 001 (2016) (Digital) (Zone-Empire).cbz (Original deleted) 

12-Mar-2016 10:25:05 - INFO    :: Post-Processing : None
12-Mar-2016 10:25:05 - INFO    :: Post-Processing : [META-TAGGER] ComicRack tagging meta-tagging processing started.
12-Mar-2016 10:25:11 - INFO    :: Post-Processing : 
12-Mar-2016 10:25:11 - INFO    :: Post-Processing : None
12-Mar-2016 10:25:11 - INFO    :: Post-Processing : [META-TAGGER][COMIC-TAGGER] Successfully wrote ComicRack tagging [C:\Mylar\cache/mylar_ld0ouf***. 001 (2016) (Digital) (Zone-Empire).cbz]
## 12-Mar-2016 10:25:11 - INFO    :: Post-Processing : [POST-PROCESSING] Sucessfully wrote metadata to .cbz (****. 001 (2016) (Digital) (Zone-Empire).cbz) - Continuing..

to check I had the correct configparser I ran "python ./comictagger.py --version", and received:

"ComicTagger 1.20.0 [ninjas.walk.alone / SHURIKEN]
Modified version of ComicTagger....etc"

So that looks ok but there are no comic tags, as when I run the comicvine add-on in comicrack it successfully adds the correct info.

I recently implemented nginx with reverse proxy which game me post processing issues with mylar & sabnzb (IP issues...) which I resolved by going over to NZBget.

Not sure if related, any ideas?

PS Thanks for an awesome project :-)

**Comment by evilhero** [comment] 2016-03-12 16:14
What version of python are you running mylar against? 

It might  be related to nzbget and the post-processing script -  have you tried to do a manual post-processing on some issues to see if they get tagged properly or not?

**Comment by partymike** [comment] 2016-03-17 09:58
Hi There, yes have done a manual post process and no the issues are still not tagging....so running the process through comicrack at the mo. In the logs post processing seems to indicate its correctly written the tags but it doesn't:

17-Mar-2016 09:33:44 - INFO    :: Thread-14 : [POST-PROCESSING] Sucessfully wrote metadata to .cbz (*** 004 (2016) (digital) (Son of Ultron-Empire).cbz) - Continuing..

Any ideas...I cannot see a debug.log is this something to set in the config file?

Cheers

**Comment by evilhero** [comment] 2016-03-17 18:11
If you look in your cache directory within the mylar directory, and find those mylar_XXXX folders, do the cbz files within there have metatagging or are they empty as well?

Verbose (debugging) can be enabled on startup with the -v option, or if you go into the Logs tab in the GUI, click on the button in the upper right to turn on verbose logging and then try post-processing/meta-tagging again.

**Comment by partymike** [comment] 2016-03-31 11:53
Hi, I think I now know the issue...where I thought it wasn't tagging - it is! But I use the option in comictagger - comicvine - "use series start date as volume". As Mylar doesn't have this option it either leaves the series date blank or puts V1 etc...in there. The problem being is that comicrack then sees that as a different issue so you end up with newer comics being synced than you have read.

Any way of adjusting the behavior of Mylar in this respect?

**Comment by evilhero** [comment] 2016-03-31 16:32
The problem with that option is that it's not available in the CLI of comictagger. I know that Mylar does write the Volume tag into the metadata, granted how it's written in is dependent on how the volume label is within Mylar (if it's 'v2', or 'v2014', etc).

I'm assuming what you're wanting is to have a customized entry for the Volume entry within the comicinfo.xml file - which would be fairly easy to do since CT allows for custom fields, and mylar already has all the information available (starting year, issueid, etc). I guess the only question I really have then is how to display the value within the xml - should the value for Volume be stored as 'v2014' or '2014' ?

**Comment by partymike** [comment] 2016-04-01 07:47
Hi, thanks for the quick response the format is "V...." so for example a new comic would be tagged "V2016" :-)

**Comment by partymike** [comment] 2016-05-18 14:26
Did you have any thoughts on this?

**Comment by evilhero** [comment] 2016-05-18 17:29
It's coming - other items took precedence the past week or two as it involves a big backend change for mylar.  Expect this one probably in a  day or two, pending other things blowing up lol...

**Comment by evilhero** [comment] 2016-06-06 01:45
This has been rolled out in the latest dev commit - just set: cmtag_start_year_as_volume = 1

**Comment by partymike** [comment] 2016-06-06 08:25
Fantastic! Thanks for this, but....although in the log it shows as a successful tag:

06-Jun-2016 09:18:04 - INFO    :: Post-Processing : [POST-PROCESSING] Sucessfully wrote metadata to .cbz

In comicrack it shows as having no metadata....if I change the 1 to 0 (cmtag_start_year_as_volume = 1) then it adds metadata as normal, but no VOL info.

Any ideas?

**Comment by evilhero** [comment] 2016-06-06 13:07
I'll have to recheck the logic again, it was a quick fix so I might have missed something simple.  Will check it out shortly and get back to you on this.

**Comment by jimbojnr81** [comment] 2016-06-25 22:30
I'm getting the similar issue to this. Setting cmtag_start_year_as_volume to 0 and the meta data saves to the comic file ready to be imported into comicrack with Volume showing as V1 etc. If i change it to 1 then nothing at all gets saved. the logs show no errors and look like they are writing the meta data but nothing.  

Any ideas?

**Comment by jimbojnr81** [comment] 2016-06-25 22:30
oh and i'm on the Development branch and up to date.

**Comment by jimbojnr81** [comment] 2016-06-25 22:33
I have noticed this line in the log 

{'LatestDate': u'2014-05-01', 'Publisher': u'Marvel', 'SeriesYear': u'2012', 'ComicVersion': u'v1', 'IsArc': False, 'Total': 20, 'ComicID': u'54112'}

showing the ComicVersion as v1. Not sure if that has anything to do with it?

[POST-PROCESSING][FILE-RESCAN] Now checking files for Indestructible Hulk (2012) in D:\Comics\Marvel\Indestructible Hulk (V2012)
2016-06-26 08:28:08	INFO	[POST-PROCESSING][UPDATER] Updating Status (Post-Processed) now complete for Indestructible Hulk issue: 1
2016-06-26 08:28:08	INFO	[POST-PROCESSING][UPDATER] Setting status to Post-Processed in history.
2016-06-26 08:28:08	INFO	[POST-PROCESSING] move successful to : D:\Comics\Marvel\Indestructible Hulk (V2012)\Indestructible Hulk 001 (February 2012).cbz
2016-06-26 08:28:08	INFO	[POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: D:\Comics\Marvel\Indestructible Hulk (V2012)
2016-06-26 08:28:08	INFO	[POST-PROCESSING] Sucessfully wrote metadata to .cbz (Indestructible Hulk 001 (2012) (digital) (Son of Ultron-Empire).cbz) - Continuing..
2016-06-26 08:28:08	INFO	[META-TAGGER][COMIC-TAGGER] Successfully wrote Comicbooklover tagging [C:\Users\Jimmy\Documents\Mylar\cache/mylar_7sb7qv\Indestructible Hulk 001 (2012) (digital) (Son of Ultron-Empire).cbz]
2016-06-26 08:28:05	INFO	[META-TAGGER] Comicbooklover tagging meta-tagging processing started.
2016-06-26 08:28:05	INFO	[META-TAGGER][COMIC-TAGGER] Successfully wrote ComicRack tagging [C:\Users\Jimmy\Documents\Mylar\cache/mylar_7sb7qv\Indestructible Hulk 001 (2012) (digital) (Son of Ultron-Empire).cbz]
2016-06-26 08:28:01	INFO	[META-TAGGER] ComicRack tagging meta-tagging processing started.
2016-06-26 08:28:00	INFO	[POST-PROCESSING] [1/1] Starting Post-Processing for Indestructible Hulk issue: 1
2016-06-26 08:28:00	INFO	[DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
2016-06-26 08:28:00	INFO	[DUPECHECK] Duplicate check for C:\Users\Jimmy\Documents\Downloads\complete\comics\Indestructible.Hulk.001.2012.digital.Son.of.Ultron-Empire\Indestructible Hulk 001 (2012) (digital) (Son of Ultron-Empire).cbr
2016-06-26 08:28:00	INFO	{'LatestDate': u'2014-05-01', 'Publisher': u'Marvel', 'SeriesYear': u'2012', 'ComicVersion': u'v1', 'IsArc': False, 'Total': 20, 'ComicID': u'54112'}
2016-06-26 08:28:00	INFO	Series_Name: indestructible hulk --- WatchComic: indestructible hulk
2016-06-26 08:28:00	INFO	I have located 1 files that I should be able to post-process. Continuing...
2016-06-26 08:28:00	INFO	[FILENAME]: Indestructible Hulk 001 (2012) (digital) (Son of Ultron-Empire).cbr

**Comment by evilhero** [comment] 2016-06-25 22:50
The v1 is just stating what's on file within mylar for a volume label. 

If you put it in verbose mode (-v on startup), it will log the actual CT command that it's tagging with so you can see what the volume label is trying to be set. 

Are you shutting down mylar with you're editing the config.ini? And that looks like a post-processing run from a download client -  an you confirm how you're running the post-processing as different types of post-processing use different pieces of code.

**Comment by jimbojnr81** [comment] 2016-06-26 03:44
I had a feeling that v1 was just related to what was on mylar. 

Yeah shutting down whenever i change the config file and restart whenever i change a setting in the gui while its running. Im using the post processing in mylar, just ticked the enable post processing in settings. I use Sabnzbd to download but never got around to figure out how to post process with it. 

here's the log with verbose mode running.

2016-06-26 13:28:10	INFO	[FILE-RESCAN] Now checking files for Spider-Man (2016) in D:\Comics\Marvel\Spider-Man (V2016)
2016-06-26 13:28:10	INFO	[MANUAL META-TAGGING] Sucessfully wrote metadata to .cbz (Spider-Man 002 ( May, 2016).cbz) - Continuing..
2016-06-26 13:28:10	INFO	[META-TAGGER][COMIC-TAGGER] Successfully wrote Comicbooklover tagging [C:\Users\Jimmy\Documents\Mylar\cache/mylar_xy2hqr\Spider-Man 002 ( May, 2016).cbz]
2016-06-26 13:28:07	DEBUG	[META-TAGGER] Absolute path to script: C:\Python27\python.exe
2016-06-26 13:28:07	DEBUG	[META-TAGGER] Executing command: ['C:\\Python27\\python.exe', 'C:\\Users\\Jimmy\\Documents\\Mylar\\comictagger.py', '-s', '-m', 'volume=2', '--cv-api-key', u'REDACTED', '-o', '--id', u'517835', '--type', 'cbl', u'C:\\Users\\Jimmy\\Documents\\Mylar\\cache/mylar_xy2hqr\\Spider-Man 002 ( May, 2016).cbz']
2016-06-26 13:28:07	DEBUG	[META-TAGGER] Enabling ComicTagger script: ['C:\\Python27\\python.exe', 'C:\\Users\\Jimmy\\Documents\\Mylar\\comictagger.py'] with options: ['-s', '-m', 'volume=2', '--cv-api-key', u'REDACTED', '-o', '--id', u'517835', '--type', 'cbl', u'C:\\Users\\Jimmy\\Documents\\Mylar\\cache/mylar_xy2hqr\\Spider-Man 002 ( May, 2016).cbz']
2016-06-26 13:28:07	INFO	[META-TAGGER] Comicbooklover tagging meta-tagging processing started.
2016-06-26 13:28:07	INFO	[META-TAGGER][COMIC-TAGGER] Successfully wrote ComicRack tagging [C:\Users\Jimmy\Documents\Mylar\cache/mylar_xy2hqr\Spider-Man 002 ( May, 2016).cbz]
2016-06-26 13:28:02	DEBUG	[META-TAGGER] Absolute path to script: C:\Python27\python.exe
2016-06-26 13:28:02	DEBUG	[META-TAGGER] Executing command: ['C:\\Python27\\python.exe', 'C:\\Users\\Jimmy\\Documents\\Mylar\\comictagger.py', '-s', '-m', 'volume=2', '--cv-api-key', u'REDACTED', '-o', '--id', u'517835', '--type', 'cr', u'C:\\Users\\Jimmy\\Documents\\Mylar\\cache/mylar_xy2hqr\\Spider-Man 002 ( May, 2016).cbz']
2016-06-26 13:28:02	DEBUG	[META-TAGGER] Enabling ComicTagger script: ['C:\\Python27\\python.exe', 'C:\\Users\\Jimmy\\Documents\\Mylar\\comictagger.py'] with options: ['-s', '-m', 'volume=2', '--cv-api-key', u'REDACTED', '-o', '--id', u'517835', '--type', 'cr', u'C:\\Users\\Jimmy\\Documents\\Mylar\\cache/mylar_xy2hqr\\Spider-Man 002 ( May, 2016).cbz']
2016-06-26 13:28:02	INFO	[META-TAGGER] ComicRack tagging meta-tagging processing started.
2016-06-26 13:28:01	DEBUG	[META-TAGGER] Absolute path to script: C:\Python27\python.exe
2016-06-26 13:28:01	DEBUG	[META-TAGGER] Executing command: ['C:\\Python27\\python.exe', 'C:\\Users\\Jimmy\\Documents\\Mylar\\comictagger.py', '-e', '--delete-rar', u'C:\\Users\\Jimmy\\Documents\\Mylar\\cache/mylar_xy2hqr\\Spider-Man 002 ( May, 2016).cbz']
2016-06-26 13:28:01	DEBUG	[META-TAGGER] Enabling ComicTagger script: ['C:\\Python27\\python.exe', 'C:\\Users\\Jimmy\\Documents\\Mylar\\comictagger.py'] with options: ['-e', '--delete-rar', u'C:\\Users\\Jimmy\\Documents\\Mylar\\cache/mylar_xy2hqr\\Spider-Man 002 ( May, 2016).cbz']
2016-06-26 13:28:01	DEBUG	[META-TAGGER] Will modify existing tag blocks even if it exists.
2016-06-26 13:28:01	DEBUG	[META-TAGGER] CBL Tagging enabled.
2016-06-26 13:28:01	DEBUG	[META-TAGGER] CR Tagging enabled.
2016-06-26 13:28:01	DEBUG	[META-TAGGER] ComicTagger 1.20.0 [ninjas.walk.alone / SHURIKEN] being used - using personal ComicVine API key supplied via mylar.
2016-06-26 13:28:01	DEBUG	[META-TAGGER] Running the ComicTagger Add-on for Mylar
2016-06-26 13:28:01	DEBUG	[META-TAGGER] comicpath : C:\Users\Jimmy\Documents\Mylar\cache/mylar_xy2hqr
2016-06-26 13:28:01	DEBUG	[META-TAGGER] sabnzbdscriptpath : C:\Users\Jimmy\Documents\Mylar
2016-06-26 13:28:01	DEBUG	[META-TAGGER] downloadpath : D:\Comics\Marvel\Spider-Man (V2016)
2016-06-26 13:28:01	DEBUG	[META-TAGGER] scriptname : Mylar.py
2016-06-26 13:28:01	DEBUG	[META-TAGGER] Paths / Locations:
2016-06-26 13:28:01	DEBUG	[META-TAGGER] Filename is : D:\Comics\Marvel\Spider-Man (V2016)\Spider-Man 002 ( May, 2016).cbz
2016-06-26 13:28:01	DEBUG	ComicTagger Path location for internal comictagger.py set to : C:\Users\Jimmy\Documents\Mylar\comictagger.py
2016-06-26 13:28:01	DEBUG	[META-TAGGER] dirName:D:\Comics\Marvel\Spider-Man (V2016)

**Comment by evilhero** [comment] 2016-06-26 04:21
Ahh OK you're using the manual metatagging option. This has been fixed and will be in the next dev commit. 

If you're wanting to post-process with sabnzbd, you can do it one of 2 ways:
-use the scripts from the post-processing subdirectory (instructions are on the main github page) 
- use folder monitoring to monitor your finished downloads folder that sab drops files into. For easier management, create a specific directory just for comics using a category within sab and then you can track things easier.

If you have any post-processing questions, feel free to start another issue and I can help you out so we don't get too far off topic from this ;)

**Comment by steffenhk** [comment] 2017-06-03 12:47
If the goal of this option is to be compatible with ComicRack/ComicVineScraper, then I don't think you should prepend 'V' to the start year when writing the Volume tag.

**Closed** 2017-08-25 01:00 UTC
Labels: enhancement, FIX (needs verification), WIP
