### ISSUE TITLE
500 Internal Server Error accessing homepage

### ISSUE THREAD

**Issue by BenBeyond** [evilhero/mylar#1609] opened 2017-03-30 19:32 UTC
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/opt/mylar/lib/cherrypy/_cprequest.py", line 645, in respond
    response.body = self.handler()
  File "/opt/mylar/lib/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/mylar/lib/cherrypy/_cpdispatch.py", line 29, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/mylar/mylar/webserve.py", line 76, in home
    comics = helpers.havetotals()
  File "/opt/mylar/mylar/helpers.py", line 1354, in havetotals
    "ComicPublished":  re.sub('(N)', '', comic['ComicPublished']).strip(),
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer
Powered by CherryPy 3.2.0

Retarting Mylar.py in the CLI "fixes" the issue for a bit, but the problem always returns, and a restart through the UI causes the same error.

**Comment by BenBeyond** [comment] 2017-03-30 19:51
Retarting Mylar.py in the CLI "fixes" the issue for a bit, but the problem always returns, and a restart through the UI causes the same error.

**Comment by evilhero** [comment] 2017-03-30 22:39
This happened to someone earlier today and the fix was to enable annual integration.. Which might not apply in this case (if you had it on, and then turned it off recently). 

It's saying that you have one series that's has an invalid publication date (the start / end range), which may have been caused when the url for CV switched to https and caused some problems for CV usage. The culprit last time was Action Comics, but you'd have to be able to delete it directly by submitting a url for it to work.

**Comment by BenBeyond** [comment] 2017-03-31 00:06
Have not messed with annuals in over a year, but they are set to NOT be integration, ie annuals are in their own series.  I recently added an old series, but I have since deleted it so not sure if that would be something.  
What is my avenue to fix the issue.  Is it happening when Mylar scans CV for any updates?

**Comment by evilhero** [comment] 2017-03-31 01:45
It has to be when it's trying to refresh a particular series during a pullist update. If you can, start mylar up in verbose mode (-v on startup), since you said you can get it running initially.. And wait for it to crap out. Shut it down at that point and the log files are in the logs subdirectory of your mylar directory. Hopefully it would have logged something indicating what's happening as I can't duplicate this at all on my end.

**Comment by DaveBrackets** [comment] 2017-03-31 10:52
Thanks for this, guys - I had the same problem, to the letter.

Shut down Mylar, flipped "annuals" in config.ini, restarted and it worked.

**Comment by macbean101** [comment] 2017-03-31 12:30
I'm seeing this as well.  

the error only shows on /home

/logs, /manage, /comicDetails(comicID), and others all work.  But any attempt to hit /home (after mylar has run for about 2 minutes) results in the error above.  

its happening on both windows and linux systems (i just took the opportunity to migrate)

I restarted it manually in verbose mode but the log shows no error messages of any sort.   I can still provide it if needed but everything looks normal in it. all entries (save 1) are info and debug for the tasks Foldermonitor and weeklycheck.  Of course then there's a few Main tasks but those are it shutting down.

The 'save 1' was an error relating to an individual comic.  I removed it, the error didn't show back up, but the /home still started giving the same errors.

**Comment by evilhero** [comment] 2017-03-31 13:05
I still can't reproduce this for whatever reason - are you guys using the alt_pull 2 method, or is it set to 1 (in your config.ini).

From what I can understand based on the comments, it's involving the publication dates of particular series, but the series it's affecting are just random series - with/without annuals.

**Comment by macbean101** [comment] 2017-03-31 13:12
my alt_pull = 2

**Comment by evilhero** [comment] 2017-03-31 13:14
Is there anyway you can pass me your mylar.db file? 

I can't reproduce this at all (I'm trying all sorts of option combinations but nothing is erroring), and I'd like to get this addressed and not being able to replicate the problem kinda stalls the process :(

**Comment by macbean101** [comment] 2017-03-31 13:23
sent you a link via PM on your forum

**Comment by evilhero** [comment] 2017-03-31 13:48
Got it - thanks, and I was able to reproduce it as well.

I'm looking at it right now, but it looks like it's a pretty involved type of bug so it might take me a bit to track down what's happening....

**Comment by evilhero** [comment] 2017-03-31 14:40
K, was messed up - not sure why it never came up before, but whatev's...

Fix is in dev now, which should address the problem. For those wondering, it only affected those individuals that had annual integration not enabled, but had a series on their watchlist that had an annual come out on the weeklypull.

**Closed** 2021-01-01 21:06 UTC
