### ISSUE TITLE
Telegram notification don't work

### ISSUE THREAD

**Issue by Bart274** [evilhero/mylar#1637] opened 2017-05-16 08:47 UTC
Hi,

Can you please check the Telegram again please?
It's been a while since I used Mylar, because of personal issues after I have created the PR.
I have enabled the Telegram notifications and let it send a test notification. This arrives on my Telegram account without any issue.
However, Mylar is snatching comics and I never get a notification, neither for the snatch or for the completed files. The post processing happens by Mylar without an issue, but I don't get notifications.

Thanks in advance.

**Comment by evilhero** [comment] 2017-05-16 14:28
I don't use telegram so I'll have to code dive in on this one. I'll see what I can figure out and give a shout back...

**Comment by Bart274** [comment] 2017-05-16 14:37
Thanks, I really appreciate it :)

**Comment by evilhero** [comment] 2017-05-16 18:20
Ok, fix is in development now - it took me way longer than humanly possible to figure out how to just set up a bot for sending to...but I figured that part out and then was able to test.

So I'm not sure if it was the fact that it wasn't verifying the https connection, or coupled with the fact that the logging statement had an invalid format to it (at least what I'm used to seeing). So fixed both, tested it and got notified on snatch & on post-processing of test item.

I can add in something to detect the user_id automatically, assuming that it's the only bot available (well I think I can), but if there's more than one bot then it wouldn't know the chat_id information.

For reference, nothing worked until I was able to submit this in an http browser to view the json and retrieve the chat_id session required:
`https://api.telegram.org/bot<bot_token>/getUpdates`
Using the above you can get the chat_id under [chat]['id']

Note that I'm not saying that you didn't do that or know of this - but I'm putting it here for my own reference in case something happens with the telegram api again ;)

**Comment by Bart274** [comment] 2017-05-16 18:23
@evilhero thanks a lot! I'll update immediately and will report back 😉

**Comment by Bart274** [comment] 2017-05-22 07:36
@evilhero just noticed Mylar found a new comic, didn't send a notification when it was postprocessed :-(

it also appears that it will always remove the 'notify on snatch' for telegram as well :-(

**Comment by Bart274** [comment] 2017-05-22 07:37
![image](https://cloud.githubusercontent.com/assets/1118630/26297231/4b388516-3ed2-11e7-9259-aec7aea5549e.png)

**Comment by Bart274** [comment] 2017-05-22 07:38
strangely enough, the log says the notification is sent, but nothing appears

when I use 'test notification' I do get my message though :-(

**Comment by evilhero** [comment] 2017-05-22 23:15
You need to save the config and restart mylar for the settings to be applied... Test connection will test the values that are loaded (meaning it won't take any changes in the config until after a save). 

Try enabling verbose mode too and doing the connection... Once I got the chat_id correct I didn't have any problems receiving notifications.

**Comment by Bart274** [comment] 2017-05-29 11:54
Hmm very strange, restarting mylar didn't restore my saved config. I disabled telegram and restarted mylar. now when I enter my bot token and chat id, it always fails to send the test notification.

**Comment by hubbcaps** [comment] 2017-05-30 07:57
Just want to report I'm also receiving the same exact issue. I've also looked over all the code related to telegram and it looks absolutely spot on so I have no idea where the disconnect is. I get the test message fine, just doesn't report on Snatch or Process of any issues.

**Comment by Bart274** [comment] 2017-05-30 09:14
I'm glad it's not just me, but it's odd we're having issues :(

**Comment by evilhero** [comment] 2017-05-30 12:02
Mylar won't notify during manual post-processing unless they were torrent snatches and you have the torrent notify option enabled (it's on the same page as the notifications in the GUI, just under miscellaneous). 

If you're using torrents, then I'd need to know the client being used (to look into the snatch notifications)

**Comment by Bart274** [comment] 2017-05-30 13:41
![image](https://cloud.githubusercontent.com/assets/1118630/26586079/5b4e4bca-454e-11e7-9307-7f6819c3e81c.png)
@evilhero I only have these options.

I'm using the BlackHole method as there is no way to verify the uTorrent connection is working, like it does for sabnzbd

**Comment by evilhero** [comment] 2017-05-30 18:31
Yeah this is weird, my test connection is failing now - but I'm receiving notifications for post-processing being completed via nzbs, but not  for on snatches....

**Comment by Bart274** [comment] 2017-05-30 18:47
Odd, and when you use torrents?
Also another thing I noticed (which is unrelated to this issue) I need to change settings and first restart before I can test them (test for notifications and for sabnzbd)

**Comment by evilhero** [comment] 2017-05-30 18:51
Only 2 notifications have been done that allow you to use the live settings as opposed to having to first save, and restart mylar and then do a test connection. Currently, NMA & Pushbullet are the only two - the remainder I still have to do, but those are the ones that I had available at the time to test the new logic against.

SAB would be the same way - all of these (SAB, notifications, providers) have to be migrated over to the use live settings method instead of the current method of saving, restarting, and testing (which sucks I know). It's coming - but each method requires a little bit of code + a bunch of testing.

I'm testing the torrent portion right now - are you using anything else in addition to just enabling the notifiers (like an on-snatch script, extra pp-script, etc) ?

**Comment by Bart274** [comment] 2017-05-30 19:00
Can I somehow privately give you the address of my installation? Then you can check yourself?

**Comment by hashmil** [comment] 2018-01-25 17:44
Hey so i'm having this issue too were i'm getting:

`Error sending test message to telegram`

What i have done so far:
- I got my userid from sending `/getid` to [@myidbot](http://t.me/myidbot)
- I then created a bot and got the API from [@BotFather](http://t.me/botfather) and sending `/newbot`. Giving it a name and username spits out the API token.
- I then 'spoke' to my bot once to make sure it was working by sending `/start`

On mylar i put in my userid and token, and then hit the 'Test Telegram' button. It just throws the error mentioned above.

I've got the notification bots working perfectly for SickRage and CouchPotato, which run on the same machine.

**Comment by evilhero** [comment] 2018-01-26 05:53
Your issue is different than the original poster. Please read his first post - he was getting test connection ok, but not other notifications made. Your post is nothing of the same. It makes things difficult to follow, and I'll just end up forgetting about them thinking they were resolved. 

Nothing has changed in the code since this issue, so I would check your settings again to ensure they're correct and or forgo the test button and see if things work anyways. 

I'm closing this issue - open a new one if the problem persists if the above doesn't work.

**Comment by Bart274** [comment] 2018-01-26 16:29
@evilhero Why did you close this? My issue still exists...

**Comment by evilhero** [comment] 2018-01-26 16:42
I closed it because the issue hasn't been touched in over 8 months as well as someone adding problems to the issue that aren't related to the current problem.

If it's still an issue, I'll reopen it but I don't use telegram so not sure when / if this will get fixed, especially since when I did use it I never had any problems. Maybe @hubbcaps can help with this one if he has some time

**Comment by MrDemous** [comment] 2018-07-05 17:23
@evilhero I'm facing the exact same problem as @Bart274 . For the past two months Mylar hasn't been sending any notifications to Telegram on snatch or after post-processing but, when I try a test notification it works just fine.

**Comment by evilhero** [comment] 2018-07-07 18:33
@MrDemous , not quite sure when things changed - at one point both test & snatch/pp notifications were working. 

I tested briefly on my install, got a traceback error immediately on a snatch. Fixed that in the latest development commit, which should actually address both of your issues (not sure if it would cause an error on post-processing, as it would never get that far since the snatch would have failed due to the notification error - but it didn't fail for me in testing now on latest dev commit).

**Comment by MrDemous** [comment] 2018-07-07 21:06
@evilhero I switched to the development branch and notifications are working again. Thanks

**Comment by Bart274** [comment] 2018-07-08 07:02
@evilhero I'm still on the development branch and updated to the latest version.
I'm still having the same issue as always: I get a notification when a comic is snatched, but after it's been downloaded, it gets postprocessed, but I don't get a notification from that.

**Comment by evilhero** [comment] 2018-07-09 05:33
@Bart274 What's your download method in mylar - torrents / nzbs? Which clients do you have enabled within mylar for your methods? Do the given issues go into a Downloaded status after the post-processing, or do they remain in a Snatched status until you do a Recheck Files/Refresh?

**Comment by evilhero** [comment] 2018-07-09 15:01
How is it post-processing - comicRN or Folder Monitor? If it's Folder Monitor, you will not get notifications as that's basically manual post-processing against a specific folder.

Completed Download Handling (CDH) will let mylar monitor your download client's queue for completion and then post-processes directly against the result, as opposed to comicRN which is an external script. 

There's no reason to be using folder monitor to pp sab/nzbget downloads when it can be done with one of the other options more reliably, and in addition receive notifications upon completion.

**Comment by Bart274** [comment] 2018-07-10 06:45
![screenshot from 2018-07-10 08-40-27](https://user-images.githubusercontent.com/1118630/42493401-322f8060-841d-11e8-9276-39aefdc59d01.png)
![screenshot from 2018-07-10 08-40-41](https://user-images.githubusercontent.com/1118630/42493402-3256260c-841d-11e8-897a-be2655065769.png)
![screenshot from 2018-07-10 08-40-57](https://user-images.githubusercontent.com/1118630/42493403-32745f46-841d-11e8-8244-ce72b80f1022.png)

@evilhero These are my current settings. On my Usenet settings I have played with the 'Enable Completed Download Handling' setting, on the Post Processing settings I have played with both the 'Enable Post-Processing' and the 'Enable Folder Monitoring' settings, but no matter what I did I always got a notification for snatched comics, but never for completed downloads and post processed comics.

**Comment by evilhero** [comment] 2018-07-10 13:29
You have your folder monitor set to monitor your sabnzbd download directory. Folder monitor will not notify of non-torrent snatches being completed. 

Either disable your folder monitor, and keep CDH enabled. Or keep CDH enabled and change your folder monitor location to something other than c:\move.

There's really nothing to play with - if you disable CDH then it won't monitor your sabnzbd queue. If you disable post-processing then it will not perform any post-processing. Turning on/off CDH and folder monitor would require a restart of mylar to ensure that the background jobs either turn on/off properly.

**Comment by Bart274** [comment] 2018-07-11 06:47
@evilhero I have disabled my folder monitoring and kept the Enable Completed Download Handling and Enable Post-Processing active like you said I should do and I restarted Mylar.
After restarting Mylar, I had a lot of comics being found and added to SABnzbd for downloading. I got notified of the snatching.
The downloads have been completed, but now they aren't post processed anymore. They remain in my c:\move directory and never get added to Mylar and moved to my O:\Comicrack directory. Any clue?

![screenshot from 2018-07-11 08-42-57](https://user-images.githubusercontent.com/1118630/42554814-958673ca-84e6-11e8-8862-881d8b583382.png)
![screenshot from 2018-07-11 08-43-03](https://user-images.githubusercontent.com/1118630/42554815-95a5e7c8-84e6-11e8-900c-87bc5b90b65d.png)

**Comment by evilhero** [comment] 2018-07-11 13:05
Did you give Mylar the full API key for sabnzbd, or just the nzb API key?
What happens when you click on the Test Connection button for sabnzbd?

Also, debug logs. Need to see debug logs showing the send to sab and anything thereafter (CDH will display stats as it's monitoring, so of you don't see that it's not working as it should)

**Comment by Bart274** [comment] 2018-07-11 14:44
@evilhero as you can see on the screenshots I'm using the right API key I think from SABnzbd and when I hit the test connection button I get 'Successfully verified API key'.
I also think everything is well set up in SABnzbd?
I have enabled DEBUG logging now and disabled the Folder Monitoring once again, I had re enabled Folder Monitoring as otherwise I didn't get any comic processed. I'll keep track of the log on when a new comic is snatched and downloaded so we can check the logs.

![screenshot from 2018-07-11 16-14-29](https://user-images.githubusercontent.com/1118630/42579786-56472144-8529-11e8-8fa8-aba4ca042781.png)
![screenshot from 2018-07-11 16-14-37](https://user-images.githubusercontent.com/1118630/42579787-567c33d4-8529-11e8-865d-52b7db0ad64f.png)

**Comment by Bart274** [comment] 2018-07-11 15:14
@evilhero Here is my log: https://pastebin.com/P7zvm8ik
I have added a new series for testing purposes. Sheena.-.Queen.of.the.Jungle.006.2018.4.covers.Digital.DR.and.Quinch-Empire and Sheena.-.Queen.of.the.Jungle.007.2018.4.covers.Digital.DR.and.Quinch-Empire have both been downloaded by SABnzbd at the time that the log was valid.
But they were never picked up as Downloaded and never got processed.

**Comment by evilhero** [comment] 2018-07-11 15:55
I haven't looked at the pastebin yet, what branch / commit of mylar are you running as your screenshot looks like it's running an older version (or maybe Master branch)

**Comment by Bart274** [comment] 2018-07-11 16:08
@evilhero I’m running the latest version of the development branch

![6c9fdd89-a4bc-40b4-8f60-42cfba4e2db4](https://user-images.githubusercontent.com/1118630/42585198-410ca4aa-8535-11e8-8473-db567afb4f0e.png)

**Comment by Bart274** [comment] 2018-07-11 16:11
![e61a85c3-6b02-4292-bb19-e6ee6860708a](https://user-images.githubusercontent.com/1118630/42585423-e414d1ea-8535-11e8-89c8-c6cca1272848.png)

**Comment by evilhero** [comment] 2018-07-12 19:15
It looks like you're running a non-English version of SABnzbd, which I'm thinking might be contributing to the problem here.

When Mylar monitors the SABnzbd queue for completion, it looks for the word ```Downloading``` or ```Idle``` to denote that the file has completed in some way. It does this for the first few times, but then it just stops monitoring the queue based on your logs as it never indicates in the log that it's finished (it should say 'File has now downloaded!') I'm guessing that when the job completes the status is changed to the language as indicated in SABnzbd so it will never trigger.

There's an easy way to test this - change your language in the SABnzbd interface to English and try to snatch something again with Mylar. I have a feeling it'll work (again just a guess)

**Comment by Bart274** [comment] 2018-07-12 19:52
@evilhero I switched everything to English and restarted SABnzbd and Mylar. I had several comics being snatched and downloaded but again they weren’t processed afterwards 😞

**Comment by evilhero** [comment] 2018-07-12 19:57
What version of SABnzbd are you running ? Do you have any other scripts or anything else running after it downloads that might alter things ? 

If you're up-to-date with SABnzbd, you might be better off using the ComicRN script attached to a specific category (ie. comics) in your SABnzbd. The problem is that for some reason it's not even returning the completed status back to Mylar even when it's being queried (you can see the timeleft/eta markers in the logs, but then nothing). At least with the ComicRN, it would run it immediately after it downloads, and do the post-process & notifications and it wouldn't rely on SAB returning any data or having to check it's history).

**Comment by Bart274** [comment] 2018-07-12 20:11
I’m running the latest version of sabnzbd 2.3.4
I’ll try the comicRN way tomorrow and will report back

**Comment by Bart274** [comment] 2018-07-13 07:40
@evilhero thanks for your suggesting. I have setup the comicRN script in SABnzbd and now I finally get my notifications :-)

![screenshot from 2018-07-13 09-37-54](https://user-images.githubusercontent.com/1118630/42678916-ac732312-8680-11e8-9c96-ec7f70a3a3cb.png)

**Closed** 2021-01-01 21:06 UTC
