### ISSUE TITLE
Error changing Annual Status

### ISSUE THREAD

**Issue by BenBeyond** [evilhero/mylar#1152] opened 2015-11-03 02:12 UTC
I have Batgirl in Mylar, with annuals inline/included with regular issues.  Any attempt to change the status from skipped to anything else would cause a "There was a error" message to pop, but nothing shows up in the log and the status will stay as skipped.

Mylar Version: development
-- git build 72065be604bc167d56ce5cb28f902626f2f0f754.
Python Version : 2.7.9
Ubuntu Version: 15.04

**Comment by evilhero** [comment] 2015-11-03 03:09
Have you restarted mylar recently? Alot of times a simple restart clears things up as an error had occurred in the background and was silent / missed and trying to run something that utilized what errored out results in an obscure error.

What status are you trying to change it to?

**Comment by BenBeyond** [comment] 2015-11-03 10:15
I restarted a couple of times before posting, just to make sure. I am trying to change the status from skipped to archived, because I want the bar the show full green on the main page (so I can quickly scan to see if anything is not downloading correctly)

**Comment by evilhero** [comment] 2015-11-03 20:15
I'm pretty sure the Archived status can only be  only assigned by mylar and not manually (as it requires the file to be in a Downloaded Status before marking as Archived as it stores the file location). You could mark it as Ignored as well and then set the config.ini value to 1 for ignore_havetotal.  (It will count ignored issues as if they were downloaded)

**Comment by BenBeyond** [comment] 2015-11-03 21:48
Just tried setting to ignore instead, but the exact same behavior happened. Just as a test, tried changing the status to each of the statuses available in the dropdown but the same thing still happens for them all....

**Comment by evilhero** [comment] 2015-11-03 23:05
Are you using the correct drop down?  There are two on the page - one for issues and one for annuals. If you use the wrong one it will cause an error as the issues selected would be in a different table.

**Comment by BenBeyond** [comment] 2015-11-04 00:30
Yep, I am using the correct dropdown.

**Comment by evilhero** [comment] 2015-11-04 15:37
Can confirm after looking at it, that the drop down is messed up for some reason. I'll be looking at it later today hopefully and figuring out what's wrong.

**Comment by Herjar** [comment] 2015-11-14 10:52
This error happens for me sometimes with normal issues too, not just annuals. Seems like there are some series the problems happens with, but not sure what the problem is ("There was an error").

**Closed** 2017-01-28 16:25 UTC
Labels: BUG, Support, WIP
