### ISSUE TITLE
Cannot Update

### ISSUE THREAD

**Issue by allkindsofralph** [evilhero/mylar#1787] opened 2017-11-25 21:33 UTC
When checking for a new update I can see the prompt to update or close in the bottom right corner. But when I click on Update and get the Mylar is Updating and the main screen will appear in 60 seconds, the update was not completed and if I check for updates again it will just say I am still behind by the same number of commits

**Comment by evilhero** [comment] 2017-11-25 21:38
How did you install it - via source or git ? 

If it's git, make sure you have the git_path pointing to the full path location of your git executable. If it's source, you'll probably have to snatch a new version from github manually - then make sure you backup your config.ini, mylar.db and cache folder. Wipe out the old directory entirely, put the new version in and then move the backup files back. Then you're on the latest.

This just came up a few days ago in regards to source installs being a problem when updating now for some reason. I'm looking into it, but haven't had as much time as I'd like to delve into things due to some other issues literally breaking Mylar (plus, with family stuff)....

**Comment by dreaganluna** [comment] 2017-11-27 08:28
same issue here. Have been using (and updating) for a very long time, never had an issue, until today, where it just keeps telling me I'm 105 commits behind.

**Comment by PCurd** [comment] 2017-11-27 09:42
And for me too - stopped working around the time of the big update (90+ commits) but can't say for sure which commit did it.

Logs show:

27-Nov-2017 09:39:50 - INFO    :: MAIN : Received signal: update
27-Nov-2017 09:39:51 - INFO    :: MAIN : Trying to gracefully shutdown the background schedulers...
27-Nov-2017 09:40:16 - INFO    :: Thread-35 : no errors on data retrieval...proceeding
27-Nov-2017 09:40:16 - INFO    :: Thread-35 : pausing for 60 seconds before continuing to avoid hammering

then after 60 or so seconds the updating page refreshes back to the main listing screen.

**Comment by DGMayor** [comment] 2017-11-27 12:25
I'm still having issues updating via the interface.  I generally have to stop python (running from source) and do a git pull manually to update.  Past few times now.

(on development)

**Comment by evilhero** [comment] 2017-11-27 23:38
If it's a git install, you should be able to just set the git_path in the config.ini to the location of your git binary and it will work (from others experience).

The source stuff I have to look more into as it has something to do with the way git changed things a few months ago. Otherwise for source installs, you'd have to do the backup, wipe, reinstall new, move back backed up

**Comment by LordJay23** [comment] 2017-11-27 23:44
Actually this sounds more like the signal issue that is causing it to not recognize signal changes, once some event happens.  I’m experiencing this fairly regularly so I can try to help you troubleshoot

**Comment by dreaganluna** [comment] 2017-11-28 07:47
setting the git_path worked for me. weird I never had to do this before.

**Comment by DGMayor** [comment] 2017-11-28 10:11
Pretty sure I was the one that figured it the gitpath thing a couple months back, but for whatever reason it stopped working for me.

**Comment by evilhero** [comment] 2017-11-28 17:14
With all the config changes on the backend that went into development recently, it's quite possible that the git_location variable in the .ini got reset. Just ensure that if you're running a git install, that the path is present, and I'm also re-adding in the original option. If you're running a MAC- this is also needed, although if your git install resides in /usr/local/git/bin/git it should default to pick it up in that location.

For the source installers, there might be an /update directory located in the root of mylar - this is where Mylar extracts the source file to, then copies files over as required. So if an update fails for whatever reason, you might have folders in there - deleting them prior to running the update might help.

Of course, in looking at this now, I just realized that when Mylar does the update from source, it will never ever delete any files that were deleted from the repository - which when we have had modules moving into different directories will cause problems as these modules will be called from the incorrect location (the bencode.py file being one of the bigger known problems was probably due to this in hindsight). This was part of the original repo, so I'll be taking care of this part - but that might be why those that use source are having problems updating....

**Comment by PCurd** [comment] 2017-11-29 09:22
My git_path has been "" for as long as I can tell (looking at backups, etc) and after the configuration updates it shows as git_path = None

I'm on Windows (10, if it matters).

**Comment by wyldphyre** [comment] 2017-11-29 12:29
Just to toss my 2 cents in, also had this problem with the update not working and then after forcing it to stop I had the git_location problem.

After updating the config.ini so that git_path = /usr/local/git/bin/git instead of 'None' I'm back up and running.

**Comment by DGMayor** [comment] 2017-11-29 12:31
Windows 10 64-bit here with Git 64-bit.  My Git install is 64-bit.  

git_path = C:\Program Files\Git\bin\git.exe


I was able to update today through the web interface, so it looks like it's working properly again.

**Comment by Nargath** [comment] 2017-11-29 12:46
Another successful fix in adding the git location to git_path

**Comment by evilhero** [comment] 2017-11-29 14:44
The git_location has been fixed in the latest development branch now.

**For git installs:**
For those still having problems, if your git executable is in your environment path (meaning you if you type 'git' on a command line, you should get back the git help, otherwise it's not in the path), you shouldn't have to do anything at this point once you're on the latest build.
If however, you're still having problems and/or your git is not in your environment path - then you need to put in the proper location to your git executable in the git_path field in the config.ini.

**For source installs:**
At this point, because Mylar (and other systems based off of it cause it's legacy headphones code at this point), it's best to do the following:
- backup you config.ini, mylar.db and entire cache folder
- wipe the mylar directory completely
- get the newest download from github for your respective branch (master/development)
- install/unzip it
- restore your backed up files into the new location
- start it back up.

This is due to how the system currently upgrades when it's a source install. It will just hammer files that already exist, but will leave other files untouched - meaning that there will never be a cleanup process so that you can have lingering files from commits from the beginning which could eventually cause problems  with incorrect references (remember the bencode problem - that was pretty much this). I'm almost done the new source based upgrade, where it will move any files that aren't in the source install into an /update/backup-update/dated folder. Thereby ensuring going forward that the source install is identical to the git and avoiding the possibility of reference problems.

There is a current problem with the update call itself, whereby if jobs are running in the background it won't end them properly or won't release to start the upgrade process - which then doesn't perform an update and keeps on doing this. @LordJay23 has offered to help, but we're unsure as to where/why it's happening - so if this is occuring please mention it.

**Comment by PCurd** [comment] 2017-11-29 16:17
I also note that I can't shutdown using the interface! When I click shutdown it goes to the shutting down screen but nothing at all shows in the logs. If I "Control+C" the batch window I get the messages below. I assume this is related to the "jobs are running in the background" problem - let me know if not and I'll make a new issue.

```
29-Nov-2017 16:15:22 - ERROR :: MAIN : Uncaught exception: Traceback (most recent call last):
  File "D:\Mylar\mylar\Mylar.py", line 282, in <module>
    main()
  File "D:\Mylar\mylar\Mylar.py", line 275, in main
    mylar.shutdown(restart=True, update=True)
  File "D:\Mylar\mylar\mylar\__init__.py", line 1146, in shutdown
    halt()
  File "D:\Mylar\mylar\mylar\__init__.py", line 1119, in halt
    SCHED.shutdown(wait=False)
  File "D:\Mylar\mylar\lib\apscheduler\schedulers\background.py", line 39, in shutdown
    super(BackgroundScheduler, self).shutdown(*args, **kwargs)
  File "D:\Mylar\mylar\lib\apscheduler\schedulers\blocking.py", line 22, in shutdown
    super(BlockingScheduler, self).shutdown(wait)
  File "D:\Mylar\mylar\lib\apscheduler\schedulers\base.py", line 176, in shutdown
    raise SchedulerNotRunningError
SchedulerNotRunningError: Scheduler is not running

Traceback (most recent call last):
  File "D:\Mylar\mylar\Mylar.py", line 282, in <module>
    main()
  File "D:\Mylar\mylar\Mylar.py", line 275, in main
    mylar.shutdown(restart=True, update=True)
  File "D:\Mylar\mylar\mylar\__init__.py", line 1146, in shutdown
    halt()
  File "D:\Mylar\mylar\mylar\__init__.py", line 1119, in halt
    SCHED.shutdown(wait=False)
  File "D:\Mylar\mylar\lib\apscheduler\schedulers\background.py", line 39, in shutdown
    super(BackgroundScheduler, self).shutdown(*args, **kwargs)
  File "D:\Mylar\mylar\lib\apscheduler\schedulers\blocking.py", line 22, in shutdown
    super(BlockingScheduler, self).shutdown(wait)
  File "D:\Mylar\mylar\lib\apscheduler\schedulers\base.py", line 176, in shutdown
    raise SchedulerNotRunningError
apscheduler.schedulers.SchedulerNotRunningError: Scheduler is not running

```

**Comment by evilhero** [comment] 2017-11-29 16:40
When you choose to shutdown - it's not an immediate effect. 

If you have jobs running in the background, Mylar tries to wait for them to finish or at least get to a point where it can end the job properly. Failing that, it will kill the job forcibly. Hitting Ctrl+C is standard for most applications that you forcibly kill while it's running mid-stream, it'll output the fact that you made things go *boom* which is what the above indicates.

It literally can take up to 60s for it to shutdown properly as it has to wait for all the scheduled jobs to finish, and then manually shut them down thereafter. But again, this might be a signal problem that a few are trying to currently track down, so if it's taking longer than 60s to shutdown then odds are it's the signal issue in full effect.

**Comment by PCurd** [comment] 2017-12-04 11:50
I didn't have a chance to test this over the weekend but now that there are some more changes to update I tried to update - same thing is happening, Mylar logs that it is starting the update but it doesn't update. I tried the Shutdown option too, and after >1hr it's still running.

**Comment by wyldphyre** [comment] 2017-12-04 11:58
Yeah, I can confirm that the updating is still not working after My,ar has been running for a while. Just doesn’t want to shut down.

If I kill it all and restart it will update then.

**Comment by evilhero** [comment] 2017-12-04 17:00
I just removed the wait option in the schedulers, so now when it does a shutdown it won't do so gracefully and wait for current jobs to finish/end. It will just end everything immediately and perform the requested action (shutdown/restart/update).

**Comment by wyldphyre** [comment] 2017-12-04 22:44
Interestingly I was able to update to the new version without the waiting this time. Mylar had only been running for about 11 hours at that point. Not sure if I just got lucky that nothing was working in the background, or if it only happens after it's been running for a certain amount of time.

**Comment by SquaTront** [comment] 2018-03-04 18:15
Having problems with updating. MacOS running Version: 8081a50d4d4301de0c4fdd667483e209cbd3c9fb (development) from a source install. No update directory and I've changed the git path to /usr/local/git/bin/git. 

Still getting: 04-Mar-2018 13:12:03 - WARNING :: MainThread : Could not get the latest commit from github

**Comment by evilhero** [comment] 2018-03-04 18:18
Make sure you update your git to the latest. If you're using an older version of git and trying to do git update it will fail due to some kind of back end changes in git. Thereafter you might also have to delete the .git folder within the mylar folder just to make sure you can update properly (I'm not 100% on this part, but a few people have had to do this before updating would work).

**Comment by SquaTront** [comment] 2018-03-10 15:33
This one is driving me crazy. I can't seem to get this to update. And the problem started about a month ago with not being able to update.
Here's my particulars:
MacOSX 10.9.5
I've updated my git to 2.16.2, configured the git path to /usr/local/bin/git in the config.ini
First I did a source install of the development branch and had no luck. On launch the gui returned an unknown version and I chose to update. I checked to see if there was a .git folder and none from the source install. CL returned:

10-Mar-2018 10:22:03 - INFO :: mylar.checkGithub.161 : MainThread : Retrieving latest version information from github
10-Mar-2018 10:22:03 - WARNING :: mylar.checkGithub.167 : MainThread : Could not get the latest commit from github

So, I thought I'd just scrap trying to install from the source and do a git install (to prove to myself that git was working properly). Installed without problem from the development branch once again.

Moved over the config.ini, cache folder and mylar.db. Checked to see if the .git folder was there and it was so I deleted it. Started up mylar and...

Same problem. Any ideas?

**Comment by SquaTront** [comment] 2018-03-10 15:42
One more thing. 
I just thought to try it without setting the git path and this was my result:
10-Mar-2018 10:40:27 - INFO :: mylar.shutdown.1177 : MAIN : Mylar is updating...
10-Mar-2018 10:40:27 - INFO :: mylar.update.230 : MAIN : Downloading update from: https://github.com/evilhero/mylar/tarball/development
10-Mar-2018 10:40:27 - ERROR :: mylar.update.233 : MAIN : Unable to retrieve new version from https://github.com/evilhero/mylar/tarball/development, can't update

**Comment by evilhero** [comment] 2018-03-10 15:42
When you install from source the git_branch variable in the config.ini is set to Master (or None can't recall exactly). So you'll get the unknown version on startup because it doesn't know the branch - caveat being if you install from source, you need to set the git_branch prior to startup.

However, I'm not sure why you're deleting the .git folder if you were able to update successfully. Do you not want to use git with mylar for some reason?

**Comment by SquaTront** [comment] 2018-03-10 15:45
You mentioned earlier in this thread to delete the .git folder as that worked for some with this update problem. I'm just trying anything.

**Comment by SquaTront** [comment] 2018-03-10 15:48
I replaced the config.ini with my previous install so the git_branch is set to development.

**Comment by evilhero** [comment] 2018-03-10 15:53
Maybe I'm 3 cups of coffee behind on this one.

You'd only have to delete the .git folder if the mylar update didn't work and after updating git.

Deleting the .git folder removes everything git from the dir. So when it goes to do the update it wouldn't find the required git info. So if you got it installed properly, not deleting the .gir folder and moving your original backed up files over should get things right. 

It does sound like you could be hitting the git limit tho for checks, the fact that it's not able to get how many commits your behind is usually a good indicator that something is amiss. The limit resets after 5 mins or something (maybe 20, I dunno), so you'd have to wait til then to check.

**Comment by SquaTront** [comment] 2018-03-10 16:16
I decided to do a totally clean install via git. Shutdown mylar, restarted the computer, did a git install of the development branch.

git clone https://github.com/evilhero/mylar.git -b development /Applications/Mylar

I moved that folder to my home directory and didn't copy over my previous cache folder, mylar.db or my config.ini file.

Started up mylar and the gui reported the version number and I thought that was a good sign.
Version: e060f37c8e64e60b36643e2bd77933f4b2a68355 (development)

Decided to push my luck and check for a new version of mylar without modifying the config.ini

10-Mar-2018 11:02:20 - INFO :: mylar.checkGithub.161 : CP Server Thread-4 : Retrieving latest version information from github
10-Mar-2018 11:02:20 - WARNING :: mylar.checkGithub.167 : CP Server Thread-4 : Could not get the latest commit from github

Shutdown mylar and changed the git_branch = development
and set my git path.

Same results. I'm not hitting git all that often but will wait a half hour and try again just to be sure I'm not hitting git check limits.

**Comment by SquaTront** [comment] 2018-03-10 17:28
Gave git a bit of time to take the git limit out of the equation. Still this error on update check:

10-Mar-2018 12:14:43 - INFO :: mylar.checkGithub.161 : CP Server Thread-11 : Retrieving latest version information from github
10-Mar-2018 12:14:44 - WARNING :: mylar.checkGithub.167 : CP Server Thread-11 : Could not get the latest commit from github

**Comment by evilhero** [comment] 2018-03-10 21:44
What happens if you do a ```git pull``` from the cli directly?
You might have local modifications that's stopping the update from going thru but the messages would be suppressed when running from within Mylar.

**Comment by SquaTront** [comment] 2018-03-11 04:55
git returns:
Already up to date.

**Comment by evilhero** [comment] 2018-03-11 15:35
Is the user running mylar the same user who issued the git pull command above?

It still sounds like it can't connect to github for some reason - is there a firewall or anything in place that might restrict access from the python program?

**Comment by SquaTront** [comment] 2018-03-11 15:41
Same user and no firewall.

**Comment by evilhero** [comment] 2018-03-11 15:50
Ok, we'll nail this down for sure. I'll commit up something in a few minutes to dev so you can get the actual error message being returned from git (it should be doing this anyways).

As of right now I haven't a clue, aside from perhaps maybe it's some SSL verification problem happening due to your OS (because it's a Mac, and this happened recently to someone else but not in regards to github).

**Comment by SquaTront** [comment] 2018-03-11 16:14
Well, it looks like I don't have SSL implemented correctly. 

11-Mar-2018 12:10:09 - INFO    :: mylar.checkGithub.161 : MainThread : Retrieving latest version information from github
11-Mar-2018 12:10:10 - WARNING :: mylar.checkGithub.167 : MainThread : [ERROR] Could not get the latest commit from github: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:581)

Any help on getting that installed correctly?

**Comment by evilhero** [comment] 2018-03-11 16:48
It has to do with the Mac not shipping the required version of OpenSSL or using LibSSL or something (can't remember exactly). I honestly haven't a clue, as I don't run a Mac - some simple google searches for the problem with your OS should give you the info you need to update...for reference, the solution for the gent that had the exact same error (but it was when he was using 32p) is [here](https://github.com/evilhero/mylar/issues/1874#issuecomment-370531931)

**Closed** 2021-01-01 21:06 UTC
