### ISSUE TITLE
Sabnzbd choking on New Avengers 31 

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#959] opened 2015-03-12 02:06 UTC
Hi

I'm sorry if I'm supposed to be doing this in one of our other Issues, but I'm a little confused about which is which now.

As I have mentioned, something about "New Avengers" causes Sab to hang up. "Running ComicRN.py" is shown. If I don't kill Sab and restart it, it will stay hung up indefinitely. 

```
Completed	2015-03-11 19:05:28
Name	New Avengers 031 (2015) (digital) (Minutemen-Midas).cbr - Running script: ComicRN.py
Size	40 MB
Status	Running script...
Category	comics
Download	Downloaded in 17 seconds at an average of 2.3 MB/s
Source	http://nzbindex.nl/download/119489499/0-Day-2015.3.11-New-Avengers-031-2015-digital-Minutemen-Midas.cbr
Repair	[New Avengers 031 (2015) (digital) (Minutemen-Midas).cbr] No par2 sets
Script	Running user script ComicRN.py
```

**Comment by AtariBaby** [comment] 2015-03-12 02:07
This is going to keep happening with the latest issue unless I tell Mylar to skip it.

**Comment by evilhero** [comment] 2015-03-12 04:47
Are these the issues that have the same names for the jpgs within the .cbr file as the actual filename itself ? (Sorry, I'm losing it abit too lately - I can't recall if this was the exact issue)

If this is the identical naming, then it has yet to be addressed - I'll see if I can hammer out a fix either later tonight or even tomorrow possibly.

**Comment by evilhero** [comment] 2015-03-12 05:39
Hmm, ok something is up - it's working for me from the exact same source (and nzb):
```
40 MB	Completed	
Completed at 01:23:37 AM on Thursday 12 March 2015 
Download: 
Downloaded in 12 seconds at an average of 3.2 MB/s
Source: 
http://nzbindex.nl/download/119489499/0-Day-2015.3.11-New-Avengers-031-2015-digital-Minutemen-Midas.cbr
Repair: 
[New Avengers 031 (2015) (digital) (Minutemen-Midas).cbr] No par2 sets
Script: 
Post Processing SUCCESSFUL! (More)
Category: 
comics
 ```

I notice in your log that you have a pre-script running? (or a script running prior to the ComicRN.py script)

Since I can't find the original post that was done - can you post the mylar.log file for that?

**Comment by AtariBaby** [comment] 2015-03-26 03:16
Sorry it's been so long since one of these incidents, I may have to wait for it to come around again.

**Comment by AtariBaby** [comment] 2015-03-26 03:33
damn it fell off the logs. New Avengers 32 of course. I'll try to make it manually happen.

BY the way i don't know what script you refer to but can send you any logs you need or tell you everything I have.

**Comment by AtariBaby** [comment] 2015-03-26 03:52
/home/misterfantastic/.mylar/logs/mylar.log

**Comment by AtariBaby** [comment] 2015-03-26 04:12
I updated the thread "unable to locate" with logs. And to answer the question, the zip files do not contain filenames identical to the zip file name. An example was posted previously in that thread.

**Comment by evilhero** [comment] 2015-03-27 00:35
K, it's not actually hanging on the post-processing, but on the file-checking of the New Avengers series:
```
25-Mar-2015 20:49:26 - DEBUG   :: Post-Processing : [POST-PROCESSING][FILE-RESCAN] temploc: v3-16.NOW
25-Mar-2015 20:49:26 - ERROR   :: Post-Processing : Uncaught exception: Traceback (most recent call last):
  File "/home/misterfantastic/.mylar/mylar/logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/misterfantastic/.mylar/mylar/PostProcessor.py", line 571, in Process
    return self.Process_next(comicid,issueid,issuenumOG)
  File "/home/misterfantastic/.mylar/mylar/PostProcessor.py", line 1025, in Process_next
    updater.forceRescan(comicid,module=module)
  File "/home/misterfantastic/.mylar/mylar/updater.py", line 771, in forceRescan
    fcdigit = helpers.issuedigits(temploc)
  File "/home/misterfantastic/.mylar/mylar/helpers.py", line 856, in issuedigits
    int_issnum = (int(issnum[:-4]) * 1000) + ord('n') + ord('o') + ord('w')
ValueError: invalid literal for int() with base 10: 'v3-16'
```

Can you verify the name of that issue? From what I can see it shouldn't be 'v3-16.NOW' but 'v3 16.NOW', the '-' is possibly throwing it off, but I need to know what the actual name of the file is before I can confirm what's going on.

**Comment by AtariBaby** [comment] 2015-03-27 04:15
the filename in my comics collection is New Avengers v3-16.NOW
Unfortunately, in sabnzbd it is so old it has fallen off the history, so I can't be sure about more details that that, unless you have a suggestion.

**Comment by evilhero** [comment] 2015-03-27 04:17
Try changing the name so it's v3 16.NOW not v3-16.NOW.. Because there's no space / break between the volume number and issue number, mylar assumes it's all the issue number. Separating them should allow it to get scanned, and post-processing should complete just fine then.

**Comment by AtariBaby** [comment] 2015-03-27 04:19
Hi

I think I’m a litte confused. This was a completed file I already had. I tried to get Mylar to search/download for it anew, but it is apparently no longer available.

**Comment by AtariBaby** [comment] 2015-03-27 04:20
Ohhh, because it’s scanning the completed files. so I should adjust that file name and then try to grab, say issue 32, again?

**Comment by evilhero** [comment] 2015-03-27 04:26
Yup it looks like it's processing the downloaded file just fine, but because it runs the file check in the series after, and fails at the 16.NOW issue it can't finish post-processing which locks it up. 

Changing it, and then even doing a file check should allow you to see if it completes the check ok (if it doesn't you'd get an error and the 16.NOW wouldn't be in a Downloaded status). Once it's OK, retrying the download should work fine at that point.

**Comment by AtariBaby** [comment] 2015-03-27 17:11
I appear to have had great success. I was going to close this, but thought maybe you should have the honor. Well done!

**Comment by evilhero** [comment] 2015-03-27 22:29
YAY! Closing!

**Closed by evilhero** 2015-03-27 22:29 UTC
