### ISSUE TITLE
Post Processing Issue - Can't Find A File That's There?

### ISSUE THREAD

**Issue by LeeThompson** [evilhero/mylar#1989] opened 2018-06-14 21:04 UTC
This is really strange, and started after today's commit.

The AUTO-COMPLETE-NZB routine is checking the download folder, sees the file size, but then says the file isn't there.  (The file is there and it is the owner of it.)

Debug log follows:

```
14-Jun-2018 13:59:26 - DEBUG   :: mylar.historycheck.133 : AUTO-COMPLETE-NZB : found matching completed item in history. Job has a status of SUCCESS/HEALTH
14-Jun-2018 13:59:26 - DEBUG   :: mylar.historycheck.135 : AUTO-COMPLETE-NZB : Plastic.Man.01.of.06.2018.2.covers.digital.Son.of.Ultron-Empire has final file size of 25MB
14-Jun-2018 13:59:26 - WARNING :: mylar.historycheck.144 : AUTO-COMPLETE-NZB : no file found where it should be @ /downloads/completed/mylar/Plastic.Man.01.of.06.2018.2.covers.digital.Son.of.Ultron-Empire - is there another script that moves things after completion ?
14-Jun-2018 13:59:26 - INFO    :: mylar.nzb_monitor.3025 : AUTO-COMPLETE-NZB : Something went wrong - maybe you should retry things. I will requeue up this item for post-processing...
14-Jun-2018 13:59:31 - INFO    :: mylar.nzb_monitor.3010 : AUTO-COMPLETE-NZB : Now loading from queue: {'status': True, 'NZBID': 2799}
14-Jun-2018 13:59:31 - DEBUG   :: mylar.processor.96 : AUTO-COMPLETE-NZB : Now checking the active queue of nzbget for the download
14-Jun-2018 13:59:31 - DEBUG   :: mylar.processor.102 : AUTO-COMPLETE-NZB : valid queue result returned. Analyzing...
14-Jun-2018 13:59:31 - WARNING :: mylar.processor.105 : AUTO-COMPLETE-NZB : Unable to locate item in active queue. Could it be finished already ?
14-Jun-2018 13:59:45 - DEBUG   :: mylar.historycheck.133 : AUTO-COMPLETE-NZB : found matching completed item in history. Job has a status of SUCCESS/HEALTH
14-Jun-2018 13:59:45 - DEBUG   :: mylar.historycheck.135 : AUTO-COMPLETE-NZB : Plastic.Man.01.of.06.2018.2.covers.digital.Son.of.Ultron-Empire has final file size of 25MB
14-Jun-2018 13:59:45 - WARNING :: mylar.historycheck.144 : AUTO-COMPLETE-NZB : no file found where it should be @ /downloads/completed/mylar/Plastic.Man.01.of.06.2018.2.covers.digital.Son.of.Ultron-Empire - is there another script that moves things after completion ?
14-Jun-2018 13:59:45 - INFO    :: mylar.nzb_monitor.3025 : AUTO-COMPLETE-NZB : Something went wrong - maybe you should retry things. I will requeue up this item for post-processing...
14-Jun-2018 13:59:50 - INFO    :: mylar.nzb_monitor.3010 : AUTO-COMPLETE-NZB : Now loading from queue: {'status': True, 'NZBID': 2799}
14-Jun-2018 13:59:50 - DEBUG   :: mylar.processor.96 : AUTO-COMPLETE-NZB : Now checking the active queue of nzbget for the download
14-Jun-2018 13:59:50 - DEBUG   :: mylar.processor.102 : AUTO-COMPLETE-NZB : valid queue result returned. Analyzing...
14-Jun-2018 13:59:50 - WARNING :: mylar.processor.105 : AUTO-COMPLETE-NZB : Unable to locate item in active queue. Could it be finished already ?
14-Jun-2018 14:00:03 - DEBUG   :: mylar.historycheck.133 : AUTO-COMPLETE-NZB : found matching completed item in history. Job has a status of SUCCESS/HEALTH
14-Jun-2018 14:00:03 - DEBUG   :: mylar.historycheck.135 : AUTO-COMPLETE-NZB : Plastic.Man.01.of.06.2018.2.covers.digital.Son.of.Ultron-Empire has final file size of 25MB
14-Jun-2018 14:00:03 - WARNING :: mylar.historycheck.144 : AUTO-COMPLETE-NZB : no file found where it should be @ /downloads/completed/mylar/Plastic.Man.01.of.06.2018.2.covers.digital.Son.of.Ultron-Empire - is there another script that moves things after completion ?
14-Jun-2018 14:00:03 - INFO    :: mylar.nzb_monitor.3025 : AUTO-COMPLETE-NZB : Something went wrong - maybe you should retry things. I will requeue up this item for post-processing...
14-Jun-2018 14:00:08 - INFO    :: mylar.nzb_monitor.3010 : AUTO-COMPLETE-NZB : Now loading from queue: {'status': True, 'NZBID': 2799}
14-Jun-2018 14:00:08 - DEBUG   :: mylar.processor.96 : AUTO-COMPLETE-NZB : Now checking the active queue of nzbget for the download
14-Jun-2018 14:00:08 - DEBUG   :: mylar.processor.102 : AUTO-COMPLETE-NZB : valid queue result returned. Analyzing...
14-Jun-2018 14:00:08 - WARNING :: mylar.processor.105 : AUTO-COMPLETE-NZB : Unable to locate item in active queue. Could it be finished already ?
```

**Comment by LeeThompson** [comment] 2018-06-14 21:08
I queued up a couple more downloads, same behavior.

**Comment by LeeThompson** [comment] 2018-06-14 21:10
If I do a manual post processing hit, it's able to find and move the files.

**Comment by evilhero** [comment] 2018-06-14 21:19
It gets the final path directly from the history of your nzbget client. If it's not in that location, then something else has moved it. If it's present but mylar says it's not there, then odds are it's a permissions issue that's stopping it from reading the file.

**Comment by LeeThompson** [comment] 2018-06-14 21:21
The files were there.  The permissions were fine (NZBget & Mylar use the same userid and group as well).   Mylar's manual post processing worked but the automatic one did not.

**Comment by LeeThompson** [comment] 2018-06-14 21:38
Hmm actually that might be it, Watcher3 has a feature you might want to add.   It calls it "Remote Mapping":
There's simply two columns, remote path and local path:

```
/downloads/completed/watcher
/download
```

In the meantime I can just change Mylar's mapped volume since it's being told that's where it is anyway.

**Comment by ryanrbrinkman** [comment] 2018-06-21 14:43
I have replicated this issue in a minimally worked example with a positive control running first in a long log file included below, in a completely fresh install (lots of debugging tried on this over last day to end up here, including finally that fresh install), followed by the same error as user above. Error occurs in latest development release and not running in Docker and everything (nzbget, mylar) 
[mylar.log.log](https://github.com/evilhero/mylar/files/2124078/mylar.log.log)
 running on same machine. 

End result is first positive control runs fine and cleans up after itself, nicely with everything where it should be. However  the error resulting process completes download and move but leaves messbehind at the end

 Thanks again for all your efforts on mylar!

**Comment by evilhero** [comment] 2018-06-21 15:04
Maybe my coffee hasn't fully kicked in yet, but I can't follow what you're trying to say exactly. 

Are you saying that the download completes fine and post-processes fine, but it doesn't clean up the directories thereafter? The error originally was due to the final download location not being accessible due to paths (basically docker restrictions) - yours obviously worked the first time, but the 2nd one it can't locate the file (which would mean either perms or path-related problems usually).

The latest dev commit was tested against v.20 of nzbget on a few different systems and they all worked without any problems.

**Comment by ryanrbrinkman** [comment] 2018-06-21 16:04
Hmmm - I was looking for that coffee fund donation page I seem to recall you having, hopefully you can help point me to that as well - you certainly deserve tips.

The error:  Downloads completes and post-processes fine  but sometimes the clean up does not occur. The test case was run into an empty download directory as a check against this being permission/path problems. First grab works ok through to clean up, second fails only at cleanup. If I ran a third grab it may or make not work, depending on the specific issue. 

Extra info I have from my own attempts are trying different things to figure this out:

Data to further support it not being a permission isssue. Mylar and nzbget are running under the same user on the same machine. Also the error occurs into a empty mylar download directory and first one completes fine as mentioned. Verified user by looking at directory structure just now as it was a late couple of nights trying to figure this out with a clean install after  trying different things to get to the minimal test case.

Metadata tagging is turned off (that was mentioned in another thread).  
The error is reproducible on the files used in the log, irrespective of order they are grabbed.
The error  occurs intermittently for some grabs,such as  in the middle of of a long pull of an entire series.

For same reason it doesn't seem to be a path related problem as first grab works (again into empty download directory).  Not sure how else to test that. 

All failed grabs (Maybe 5% occurrence, rough ballpark)  have the same error structure as this sequence:
21-Jun-2018 07:24:02 - DEBUG   :: mylar.historycheck.135 : AUTO-COMPLETE-NZB : found matching completed item in history. Job has a status of SUCCESS/HEALTH
21-Jun-2018 07:24:02 - WARNING :: mylar.historycheck.159 : AUTO-COMPLETE-NZB : no file found where it should be @ /volume1/mylar2018/New.Challengers.001.2018.digital.Son.of.Ultron-Empire - is there another script that moves things after completion ?
21-Jun-2018 07:24:02 - INFO    :: mylar.nzb_monitor.3054 : AUTO-COMPLETE-NZB : Could not find NZBID 166 in the downloader's queue. I will requeue this item for post-processing...

Here is the check to see that the file is where it says it can't be found:

 ls -l  /volume1/mylar2018/New.Challengers.001.2018.digital.Son.of.Ultron-Empire
total 28760
-rw-r--r-- 1 sc-mylar mylar 29447687 Jun 21 07:23 New Challengers 001 (2018) (digital) (Son of Ultron-Empire).cbr

As for other scripts, no other post-processing scripts (or any other scripts) are running only ComicRN

**Comment by evilhero** [comment] 2018-06-21 16:10
You can't have both comicRN and completed download handling enabled. They will both vie for control of the post-process and with one winning the other will error and say it can't find items. Which you choose is entirely up to you however (they both do the same thing with CDH allowing for direct pp against specific IDs).

Also the donation page is on the first tab of the mylar configuration. Much love for any help to feed my habit also ;)

**Comment by ryanrbrinkman** [comment] 2018-06-21 16:49
Yeah that was the issue (ha!)

Merci and happy to hopefully have helped a bit in return.

**Comment by LeeThompson** [comment] 2018-06-21 18:05
If there are options that get in each other's way you should have a warning in the config UI (or make them more compatible in the code which is more work I know).   ( If I knew Python better I'd help. )

**Comment by barbequesauce** [comment] 2018-06-21 18:08
Does this not show up for you?
<img width="268" alt="screen shot 2018-06-21 at 2 07 41 pm" src="https://user-images.githubusercontent.com/25070944/41737217-9ec68752-755c-11e8-819a-f25b1500ff1d.png">

**Comment by ryanrbrinkman** [comment] 2018-06-21 18:17
The warning to not click if using ComicRN only shows after it is selected. As a warning it might be useful to have some notice before you click -  but only saying that as an idea to help others maybe as obviously users can be idiots. No reason to suspect I would not have failed to notice a before and after message if both were there. Time is appreciated for user help, my apologies. Perhaps also in the error message pointing at a like place where this script might be coming from. Again just thoughts on how to save you from pain of other stupid users.

**Comment by LeeThompson** [comment] 2018-06-21 22:41
@barbequesauce It does not actually (I don't normally have 'rename' selected though, but I just enabled it and saved, then went to the downloader page and unchecked/rechecked, no message.)     It should also not just say "ComicRN Script", that assumes someone knows what ComicRN ("Comic Registered Nurse?") is and other than that message (going from your screenshot) the term "ComicRN" is not shown anywhere in the config so it doesn't really tell the user what option it's connect to.

![nocomicrnwarning](https://user-images.githubusercontent.com/1982261/41749109-8b859a68-7569-11e8-81b0-939461e0bc22.jpg)

**Comment by evilhero** [comment] 2018-06-21 23:02
K, you're on master. Everything is fixed in development. You're running docker locked onto master (if you don't want to, talk to the docker people).

And the comicRN thing - we could name it anything we wanted honestly. It says in the read.me included with the app exactly what it is and how to use it - the onus is on the user to actually read the file that has details about things and not literally waste time for us to explain something already documented. Sure documentation sucks for mylar, but that is documented.

If we explained everything in detail within the application  there wouldn't be any room for any of the options.

**Comment by LeeThompson** [comment] 2018-06-21 23:23
Even if I could use the development branch I wouldn't for this install, this is a 'production' installation.  (I could rebuild the image to use dev branch and save it as it's own docker image.)


As for your other comments, I very much disagree as a software developer:

The onus is on the software designer to make the UI work well, and things are clearly understood.     

Those using docker containers (or other pre-bundled applications) may not have easy access to the docs (or do but won't see where they are).   (And how many people read "readme"?)

There's absolutely ways to explain stuff in an app (even a web one) without cluttering the interface.

You can easily do tooltips like this:
`<abbr title="Tooltip Text"><img src="icon.gif"></abbr>`

You can have a link to the wiki (or github's doc files).   Even add a "Help" button on the top tab.

You can, of course, leave it all as is, that's your prerogative.    I don't really want to get into a debate on it.     If you really don't want to improve the UI so you don't get bug reports that are a result of allowing conflicting options to be selected, documentation issues, etc - I will happily help out when I have the time which I presently, do not.

**Comment by evilhero** [comment] 2018-06-21 23:48
Well I'm obviously (?) not a software developer, so I'm closing this issue as the support aspect has concluded.

**Closed** 2018-06-21 23:48 UTC
