### ISSUE TITLE
Error: "this has an alpha-numeric in the issue # which I cannot account for"

### ISSUE THREAD

**Issue by silentArtifact** [evilhero/mylar#2314] opened 2019-07-29 14:26 UTC
Heya! I've been getting repeated errors about 

> 21) this has an alpha-numeric in the issue # which I cannot account for.

Presumably it's the ")" in the issue number. I'm trying to find which series is using that, but not having much luck. Is there a better way to track it down?

**Comment by barbequesauce** [comment] 2019-07-29 14:30
Hi - without you filling in the issue template we have no idea where you are, what you're doing, etc...

**Comment by silentArtifact** [comment] 2019-07-29 15:49
Apologies, I missed the template somehow; running on 1.5 hours of sleep. 
**Describe the bug**
With the debug log on, I continuously get the error:
> 21) this has an alpha-numeric in the issue # which I cannot account for.
Although the issue number changes.

**Screenshots/Logs**
[mylar.log](https://github.com/evilhero/mylar/files/3443088/mylar.log)

**Environment (please complete the following information):**
 - OS: [e.g. Windows10]
 - Branch / commit: 68a8e77ad15a960b62106616c38e277ff0ec01cb

**Comment by evilhero** [comment] 2019-08-01 05:36
Duplicate of #2315 (even tho this came dated prior, I'm just indicating here for continuity). If you remove the brackets around the issue number it will post-process as per normal. 

Fix is done atm, and will be pushing out to development within a day or so (after some additional testing).

**Closed** 2021-01-01 21:02 UTC
