### ISSUE TITLE
Issues not being rechecked/detected

### ISSUE THREAD

**Issue by razambon** [evilhero/mylar#1030] opened 2015-05-23 05:55 UTC
Trying to move things around a bit to resolve the massive issue I keep having with everything getting set to skipped despite being set as archived repeatedly.  Now nothing's being detected.  My original name formatting was (for the example below) "Catwoman (2011) 13 (12-2012).cbz".  I changed it to the super simple format below that still seems to not be working.

23-May-2015 01:49:20 - INFO    :: Thread-12 : [FILE-RESCAN] Now checking files for Catwoman (2011) in Z:\ServerFolders\Comics\DC Comics\Catwoman (2011)
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] comic: Catwoman
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] Looking in: Z:\ServerFolders\Comics\DC Comics\Catwoman (2011)
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : there are 41 files.
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] numberinseries: False
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] decimalinseries: False
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] bracketinseries: False
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] subnm len : 3
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] subname no brackets: Catwoman 
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : as_start: 15 --- !!62345
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : as_start: 22 --- !!62345
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] Extracted comicid for given annual : 62345
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] AS_Alt : ['None', 'Catwoman Annual']
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] watchcomic:Catwoman ..comparing to found file: Catwoman
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] Complete matching list of names to this file [1] : ['Catwoman']
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] AS_Tuple : [{'AS_Alternate': 'Catwoman Annual', 'ComicID': u'62345'}]
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] Catwoman Annual comparing to Catwoman
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] Catwoman - watchlist match on : Z:\ServerFolders\Comics\DC Comics\Catwoman (2011)\Catwoman (2011) 34.cbz
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] cchk is : Catwoman
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] we should remove 0 characters
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] nonocount [0] cchk [Catwoman] length [8]
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] final jtd_len to prune [8]
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] before title removed from FILENAME [Catwoman (2011) 34.cbz]
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] after title removed from FILENAME [ (2011) 34.cbz]
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] creating just the digits using SUBNAME, pruning first [8] chars from [Catwoman]
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] after title removed from SUBNAME []
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] Invalid character found in filename after item removal - cannot find issue # with this present. Temporarily removing it from the comparison to be able to proceed.
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] JUSTTHEDIGITS []
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : Probably due to an incorrect match - I cannot determine the issue number from given issue #: 
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] final justthedigits []
23-May-2015 01:49:20 - DEBUG   :: Thread-12 : [FILECHECKER] Issue number not properly detected...ignoring.

**Comment by evilhero** [comment] 2015-05-23 07:13
The problem is that there is no clear-cut distinguished indication (from Mylar's perspective) of what is the issue year and/or what the series year in either of your formats : 
Catwoman (2011) 13 (12-2012).cbz
Catwoman (2011) 13.cbz

To denote a series year, you should be using the volume label to indicate it as such - v2011, vol2011, v4, vol4, etc. In doing so Mylar will be able to distinguish the issue year from the series year, and it's also pretty common practice to do so.

I'm also going to bet that it has a problem with the placement of the series year in the filename - the way Mylar parses the filenames is that it looks for the first occurance of brackets and works backwards - in 90% of the cases, the brackets indicate a year of some kind and is preceded by the issue number, and then the series title (in reverse order or course). So with having a year immediately after the title, mylar assumes it's the issue year (because again, there's no denotion between series year and issue year - word placement isn't enough), finds the series title just fine, but can't find the issue # so it says it cannot determine it.

I would suggest you perhaps follow a naming scheme of any of the following:

Catwoman v2011 13 (12-2012).cbz  (*not sure if the 12-2012 would be read in properly by mylar)
Catwoman v2011 13 (2012).cbz
Catwoman v4 13 (2012).cbz
Catwoman vol.4 13 (2012).cbz

**Comment by razambon** [comment] 2015-05-23 23:49
Hrm.  My original naming format was Catwoman (v2011) 13 (12-2012) and that didn't detect either.  

Doing the naming without the date and without the ()'s around the v2011 seems to have resolved it.  Thanks!

**Comment by evilhero** [comment] 2015-05-24 02:19
You could keep the date probably - well at the very least you could keep the issue year (within brackets), and mylar shouldn't have any problems scanning those files in. 

But glad you got it working. I am going to try to improve the scanning, but probably won't actually happen for a few weeks.

**Comment by razambon** [comment] 2015-05-24 02:36
Hit on one other issue - kind of unexpected.  Amazing and Uncanny X-men don't seem to detect.

23-May-2015 22:34:41 - INFO    :: Thread-12 : [FILE-RESCAN] Now checking files for Amazing X-Men (2013) in Z:\ServerFolders\Comics\Marvel/Amazing X-Men (2013)
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [FILECHECKER] comic: Amazing X-Men
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [FILECHECKER] Looking in: Z:\ServerFolders\Comics\Marvel/Amazing X-Men (2013)
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : there are 19 files.
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [FILECHECKER] Version detected as : v2013
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [FILECHECKER] numberinseries: False
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [FILECHECKER] decimalinseries: False
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [FILECHECKER] bracketinseries: False
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [FILECHECKER] subnm len : 1
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [FILECHECKER] 1: detected invalid filename - attempting to detect year to continue
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [FILECHECKER] decimal issue detected, not removing decimals
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [FILECHECKER] subname no brackets: Amazing X-Men  - 11
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [-] charpos: [9, 15]
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [FILECHECKER] - appears in series title.
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [FILECHECKER] up to - :Amazing X 
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [FILECHECKER] after -  :Men  - 11
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [FILECHECKER] new subname is : Amazing XMen  - 11
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [FILECHECKER] possible negative issue detected.
23-May-2015 22:34:41 - DEBUG   :: Thread-12 : [-] charpos: [14]

Just always shows them as skipped.  Same thing happens for Uncanny X-Men.

**Comment by evilhero** [comment] 2015-05-24 03:00
So the filenames look like :
'Amazing X-Men - 11.cbr'? 

You have to remember that if a series has multiple volumes, then it needs to be distinguished regardless of the directory it's in. So Amazing X-Men is probably fine, but the Uncanny X-Men would need to have a volume label that coincides with what mylar has for volume (on the Edit tab for the series). You can have it as v2, or v2013 or if you didn't want that you could even just put the issue year in brackets and it should pick it up. 

Can you post the filenames for each series that you're trying just so I can confirm myself if it's a problem with the checker?

**Comment by razambon** [comment] 2015-05-24 04:17
Its Amazing X-Men v2013 - 11 or any other issue number.  Same format for
Uncanny.  I'll get specific ones for you tomorrow morning.

**Comment by razambon** [comment] 2015-05-24 19:42
Uncanny X-Men v2013 - 01.cbz - All issues are numbered in that way.
Amazing X-Men v2013 - 01.cbz

Folders are 
Z:\ServerFolders\Comics\Marvel\Uncanny X-Men (2013)
Z:\ServerFolders\Comics\Marvel\Amazing X-Men (2013)

Here's the weird thing - other comics with -'s and the like in them are fine.

**Comment by evilhero** [comment] 2015-05-25 00:53
Ok, got it working so that it will displace the '-' as a separator in these cases - so long as there's a space on either side of the dash, it should work (I tested it on a bunch of different series with different variations on naming) as in the tests I did they got picked up.

Will be up in the next development commit...

**Comment by tkbott** [comment] 2015-05-26 02:02
I am having issue with library scan on the newest update.  Log below, prior to update everything updated with a recheck of files.

2015-05-25 20:47:41	INFO	[FILE-RESCAN] I have physically found 0 issues, ignored 0 issues, snatched 0 issues, and accounted for 27 in an Archived state [ Total Issue Count: 27 / 28 ]
2015-05-25 20:47:41	INFO	[FILE-RESCAN] Total files located: 0
2015-05-25 20:47:41	INFO	[FILE-RESCAN] Updated the status of 28 issues for Thief of Thieves (2012) that were not found.
2015-05-25 20:47:40	INFO	[FILE-RESCAN] Now checking files for Thief of Thieves (2012) in :Thief of Thieves (2012)
2015-05-25 20:47:39	INFO	[FILE-RESCAN] Now checking files for Thief of Thieves (2012) in \\Nas\media\comicbooks\image\skybound\Thief of Thieves (2012)

Newest issue still shows as updated.  File naming is Thief of Thieves Vol.2012 #28 (May, 2015), I have had no issues until recent update.

**Comment by evilhero** [comment] 2015-05-26 23:32
@tkbott: same as issue #1023, which is still open and should be fixed in the next development commit.

**Comment by evilhero** [comment] 2015-06-07 01:00
@tkbott: this should now be working in the latest development commit (0c1e86409960b3e235f15c36e2f7465c710690e6)

**Closed** 2021-01-01 21:08 UTC
