### ISSUE TITLE
Mylar not fetching comics - Error

### ISSUE THREAD

**Issue by arqcan** [evilhero/mylar#2156] opened 2019-01-02 09:26 UTC
When i try to search for comics i get the following error in the debug logs:

2019-01-02 08:37:24	ERROR	Git returned bad info. Are you sure this is a git installation? [fatal: ambiguous argument '%cr': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git [...] -- [...]'
]
2019-01-02 08:37:24	ERROR	Error: None
2019-01-02 08:36:46	DEBUG	If you can read this message, debug logging is now working

Mylar will download comics if i restart the program, and Mylar will update fine. This is a git install for sure. Any suggestions?

**Comment by PCurd** [comment] 2019-01-02 12:18
I also receive this error - hadn't thought to raise as an issue because everything seems to be working with updates, etc. I'm on Windows 10 with git version 2.16.2.windows.1

I don't seem to get the error on every search though, seems a bit more random for me.

**Comment by evilhero** [comment] 2019-01-03 02:56
The git error isn't related to searching at all. It's related to a call to git when you view the config page and it's trying to display the branch history on the first tab of the configuration. Can you view the configuration page and/or do you see the branch history section populated ? 

I believe the ```%cr``` option in git being used might not be supported in the newer version of git (or maybe it's usable in some other way on non-linux machines). It's working on my ubuntu machine just fine without error, but then again my setup seems to invoke some serious ju-ju or something when it comes to trying to recreate problems.

If either/both of you can confirm that you can't see your branch history (it should be blank with that particular error), I can look more into why it's failing using that option.

That specific error won't break anything in relation to updates or the like - it's just used for displaying the branch history on the config page and that's it.

There is also however a current bug with the timed search option within Mylar whereby it's locking up for some reason and not releasing it until a restart of Mylar. A few of us are currently trying to figure out why it's locking up and at one point, but have been unable to pinpoint the exact cause atm...so that's a big one we're trying to work on, but it's a lot of trial & error to get to the point we need.

**Comment by arqcan** [comment] 2019-01-03 07:48
Thanks for getting back to me, i have had a look and i can confirm that my
branch history is listed as 'None' and i am currently running on a Windows
10 PC with the most recent updates.

As for the locking error, restarting does kick everything back into action
so i will just manually restart it when i want it to grab comics. Is the
locking issue effecting all users or only a small portion?

**Comment by PCurd** [comment] 2019-01-03 09:07
Yes I also see Branch history None on the Settings page.

**Comment by evilhero** [comment] 2019-01-22 15:19
Welp, the git error was a stupid quotation problem that git apprently didn't like the single quotation marks being used on Windows systems. Tested and fixed now in the latest development build 05f3eb4

**Comment by arqcan** [comment] 2019-01-25 09:48
Thanks for getting back to me, i have updated mylar to the most recent development build and it now has fixed the github branch history issue. 

However once it has now been updated mylar on windows 10 is running very very slow. My pc running the program has jumped from about 5% cpu usage to about 30% while only running mylar.

**Comment by evilhero** [comment] 2019-01-28 17:53
It might use a bit more cpu during certain cycles depending on what it is that's going on. If it's doing a huge backlog search, it requires processing power to process all the searches. If you also have downloads going on at that time (which is what happens hopefully as a result of the above searches), then you might have queue monitoring occuring, and if not, then you'd have post-processing queueing up and being performed which requires more cpu if you have those options enabled.

We've seen slight spikes in cpu usage during rss scans and on initial startups sometimes (but usually that's only if you have the search when started option enabled). Otherwise, the spike in usage usually will  come back down to a normal level, but usually Mylar is performing some task or another at any given time.

You would need to provide more information as to what Mylar was doing when you saw the usage spikes and if they returned to normal thereafter. Otherwise, reproducing this type of problem is difficult to accomplish.

**Comment by arqcan** [comment] 2019-01-28 21:57
Here is a copy of some of the log:


2019-01-28 21:51:04 | INFO | [FOLDER-CHECK] Checking folder C:\Users\share\Downloads for newly snatched downloads
-- | -- | --
2019-01-28 21:50:23 | DEBUG | Refresh sequence set to fire every 5 minutes for 7 day(s)
2019-01-28 21:46:04 | INFO | [FOLDER-CHECK] Checking folder C:\Users\share\Downloads for newly snatched downloads
2019-01-28 21:45:23 | DEBUG | Refresh sequence set to fire every 5 minutes for 7 day(s)
2019-01-28 21:42:33 | INFO | [Auto-Search (trigger: interval[6:00:00], next run at: 2019-01-29 00:33:47 UTC)] Now force submitting job for jobid search
2019-01-28 21:41:04 | INFO | [FOLDER-CHECK] Checking folder C:\Users\share\Downloads for newly snatched downloads
2019-01-28 21:40:23 | DEBUG | Refresh sequence set to fire every 5 minutes for 7 day(s)
2019-01-28 21:39:44 | DEBUG | Comparing currently installed version [42f7e065da0addfe96fb65fe0931d4c37763ed42] with latest github version [b5e87992f821ace0ac2543c18702303c1efb83d3]
2019-01-28 21:37:33 | INFO | Verbose (DEBUG) logging is enabled
2019-01-28 21:35:52 | INFO | [FOLDER-CHECK] Finished checking for newly snatched downloads
2019-01-28 21:35:46 | INFO | [POST-PROCESSING] No matches for Manual Run ... exiting.
2019-01-28 21:35:41 | INFO | Now checking: The Punisher [112965]
2019-01-28 21:35:33 | WARNING | The Punisher [2016] is either Paused or in an Ended status with 100% completion. Ignoring for match.
2019-01-28 21:35:24 | INFO | Now checking: The Punisher [90118]
2019-01-28 21:35:23 | INFO | Update complete
2019-01-28 21:35:19 | INFO | Now checking: The Punisher [112965]
2019-01-28 21:35:11 | WARNING | The Punisher [2016] is either Paused or in an Ended status with 100% completion. Ignoring for match.
2019-01-28 21:35:06 | INFO | Now checking: The Punisher [90118]
2019-01-28 21:35:01 | INFO | Now checking: Black Widow [116493]

So from what i can read it took over 40 seconds to check for the one Punisher volume, that doesn't sound right to me.

**Comment by evilhero** [comment] 2019-01-28 22:06
Honestly I can't read that - it's just a wall of text on this side. Try pasting the log from the actual mylar.log file and enclose it around triple ``` ` ``` for formatting. 

It looks like you're trying to do folder monitoring, mylar has to check every file in the folder monitor for a match against your watchlist. That might involve refreshing of a series it thinks might be a match, but doesn't have the issue it's looking for in its watchlist as of yet. Such refreshes can take 30s-1min / series due to CV delays and/or time-delays on purpose when querying CV, as well as general workflow.

**Comment by arqcan** [comment] 2019-02-06 22:55
I think i got to the bottom of the increased CPU usage, when i enabled DDL it puts quite a bit of strain on the resources, once i turned it off everything went back to normal.

**Closed** 2021-01-01 21:03 UTC
