### ISSUE TITLE
Sorry I'm having problems: all comics in my "completed folder", mylar is downloading tons of old comics, won't start automatically, seems to quit at times

### ISSUE THREAD

**Issue by AtariBaby** [evilhero/mylar#2293] opened 2019-06-05 21:32 UTC
**Describe the bug**
Hi, firstly, I checked my completed folder and it's crazy full of comics. For example, all the issues of Superior Spider-Man 2019 are in the completed folder. The folder for these issues was created by Mylar in the destination, but it's empty.

Secondly, 

Mylar is downloading tons of comics, like going back years. Stuff that already exists and almost always was downloaded by Mylar before.

Third, Mylar doesn't start on its own anymore. And sometimes it's shut down when I go to access it. I was using the technique of naming mylar.py to Mylar.pyw and putting it in the Windows 10 startup folder. I have to manually start it a lot.

**Screenshots/Logs**
Include a DEBUG log using the log files and do not paste from the GUI log.
Do not just paste a traceback/error.

[mylar.log](https://github.com/evilhero/mylar/files/3259103/mylar.log)

![mylarscreen1](https://user-images.githubusercontent.com/97095/58991277-bc946300-879c-11e9-8255-9d6dcce6b03b.JPG)
![mylarscreen2](https://user-images.githubusercontent.com/97095/58991278-bc946300-879c-11e9-9ec9-fd26af9edd43.JPG)
![mylarscreen3](https://user-images.githubusercontent.com/97095/58991279-bd2cf980-879c-11e9-9dbe-5bd41aa2389c.JPG)
![startup](https://user-images.githubusercontent.com/97095/58991280-bd2cf980-879c-11e9-83d2-3f2a858a6ab1.JPG)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro fully updated
 - Branch / commit: 
Mylar Version: master-- git build c79cbe5a0eadd539801a5e3377fecebb852c1fe3.Python Version : 2.7.14Language : en_US.cp1252
Configuration Options
--
![options1](https://user-images.githubusercontent.com/97095/58992023-822bc580-879e-11e9-9e27-4ceb6ed71b9e.JPG)
![Options2](https://user-images.githubusercontent.com/97095/58992024-822bc580-879e-11e9-82f1-897314d23da1.JPG)
![Options3](https://user-images.githubusercontent.com/97095/58992025-822bc580-879e-11e9-9c65-a86181168954.JPG)
![Options4](https://user-images.githubusercontent.com/97095/58992026-822bc580-879e-11e9-816d-6df114b40b18.JPG)
![Options5](https://user-images.githubusercontent.com/97095/58992092-b1423700-879e-11e9-813f-e9ae383c36b2.JPG)

**Additional information**
sorry i'm having so much trouble!

**Comment by evilhero** [comment] 2019-06-06 13:03
Well, first you're quite a bit of commits behind - you're running a version from the middle of March, last push to Master was in May. So you need to get up to date.

Second, and probably most important - you have your Folder Monitor path set to monitor your Comic Location path, which is a huge no-no.  What ends up happening is that it watches your Comic Location path for any files it can post-process, then moves it back over to itself, and then either it fails during the move onto itself, or the cleanup attempts to clean up the incorrect file (since it's itself) and deletes things. 

Then you have the ```Automatically Mark all issues as Wanted``` option enabled too, which just compounds things based on the problem above. So now your files are gone, the auto-refresh of the series occurs, those files that were there before are now gone so it marks them all as Wanted and then it goes to re-download everything, again. Then it just keeps on doing this over & over.

Also, you enabled debug logging at the end of the log - the entire log is just INFO level. But I'm almost positive that your problems all stem from the Folder Monitor being incorrectly set.

**Comment by AtariBaby** [comment] 2019-06-06 14:06
okay wow.
How do I get it updating automatically again?
I unchecked monitor folder. Somehow I got confused on what that is. Makes sense now.
"Mark all issues as wanted" is good by itself, right? I thought that meant when you add a title, it marks the wanted. Is that right?
Oh, I forgot to delete the old log as part of the process. Should I repeat?

**Comment by evilhero** [comment] 2019-06-06 14:17
Try the in-app updater - if that doesn't work you'll either have to perform a ```git pull```, redownload the source or do a fresh git clone (depending on your problems).

All issues as Wanted is fine, but in these types of circumstances it's evil cause it literally marked every issue that was there (and got deleted) as Wanted on each auto-refresh of the series. If you want every issue to be automatically marked when adding a series, then yeah it's fine. Otherwise, I wouldn't use it.

No need to repeat send the logs - unless after updating, and turning off Folder Monitor doesn't work.

**Comment by AtariBaby** [comment] 2019-06-06 14:33
Okay, I'm updated, What the best way to "rehabilitate" my collection now?

**Comment by kanine** [comment] 2019-06-10 06:32
Couple points here from some things I've noticed when trying to clean up my collection (missing issues and converting everything to cbz with metadata).

The development branch seems a lot better than master, and is quite stable less/no errors flooding the command window. 

Command was (something like): git clone --single-branch --branch development <https link>

I then just transferred over the mylar.db, and started the mylar.py letting it create a new config and then just put the providers etc in again (not much config required really), the difference between my old config and the newly created one was significant but everything runs a lot better now.

I was having some 'stuck' files in the download folder, but I think it was sometimes caused by corrupted cbr files. I moved all cbr and cbz files from the subfolders into the root of another folder then forced a manual process on that folder. That helped me work out which files were causing issues, those I moved and renamed manually and then did a recheck in the appropriate comic page.

Hope that helps.

**Comment by AtariBaby** [comment] 2019-06-17 18:48
^Thank you. I can start from scratch again. Could someone one on evil heroe's team confirm I'd get better results if I go back on development? And start over, by copying the db file and carefully doing settings precisely as before?

Also, I still have the problem where mylar no longer starts automatically. Should I stop with the startup shortcut and go back to nssm?

**Closed** 2019-06-23 21:26 UTC
