### ISSUE TITLE
post processing issue

### ISSUE THREAD

**Issue by juliemars** [evilhero/mylar#2093] opened 2018-10-11 17:01 UTC
Hi 

I just moved my downloads from a Linux system to Windows, Mylar is still running on Linux so I am not sure if this is part of my problem.  I am using nzbget

I have deleted and recreated the autoProcessComics.cfg, autoProcessComics.py and ComicRN.py files.

In Nzbget the last item logged is:
Executing post-process-script ComicRN.py for COMICNAME

this then sticks and nothing happens until I delete the job. 

Looking at the logs in Mylar the only ones I have are:

`

2018-10-11 17:47:59 | ERROR | Uncaught exception: Traceback (most recent call last):  File "/opt/Mylar/mylar/logger.py", line 337, in new_run    old_run(*args, **kwargs)  File "/usr/lib/python2.7/threading.py", line 754, in run    self.__target(*self.__args, **self.__kwargs)  File "/opt/Mylar/mylar/PostProcessor.py", line 1279, in Process    self.nzb_or_oneoff_pp(tinfo=pp)  File "/opt/Mylar/mylar/PostProcessor.py", line 1697, in nzb_or_oneoff_pp    if dupthis['action'] == 'dupe_src' or dupthis['action'] == 'dupe_file':TypeError: 'NoneType' object has no attribute '__getitem__'
-- | -- | --
2018-10-11 17:47:59 | WARNING | [DUPECHECK] Make sure if you are using ComicRN, you do not have Completed Download Handling enabled (or vice-versa). Aborting
2018-10-11 17:47:59 | WARNING | [DUPECHECK] File cannot be located in location specified. Something has moved or altered the name.

`

Any ideas?

**Comment by barbequesauce** [comment] 2018-10-11 17:11
The important line is this:
`Make sure if you are using ComicRN, you do not have Completed Download Handling enabled (or vice-versa`

It sounds like you'd prefer to use ComicRN - so check to make sure that Completed Download Handling is disabled on the Download Settings tab. If it's active you'll see collisions like this.

**Comment by juliemars** [comment] 2018-10-11 17:15
thanks, the strange thing is that is already disabled.

**Comment by barbequesauce** [comment] 2018-10-11 17:18
Are you sure the paths match between NZBGet & Mylar?
Also, what branch & commit are you on?
Maybe try rerunning the snatch/postprocess with debug logging active and post that version of the log...

**Comment by juliemars** [comment] 2018-10-11 17:21
Mylar Version: development
-- git build 021dc47fae15c524f40e951dd2a6de4cd691d2be.

enabled debug logging and it worked, so no idea what is going on I will keep an eye on it over the next few grabs and see if it continues to work now that debug is disabled again.

**Comment by barbequesauce** [comment] 2018-10-11 17:22
OK thanks.

**Comment by dantreacy** [comment] 2018-10-14 02:57
I had that exact same error with the same version and branch pop up very intermittently. Doesn't seem to be any commonality in when it pops up and almost 100% of the time if you run it again it works.

**Comment by dantreacy** [comment] 2018-10-14 03:29
Funnily enough I just had this reoccur and I think it might shed a little more light on it.. 

It appears to be related to #2084 

14-Oct-2018 14:21:50 - INFO :: mylar.duplicate_filecheck.2089 : Thread-15 : [DUPECHECK] Duplicate check for /Volumes/Storage/Import/Comics/Futures End Month (One-Shots) (2014) (Digital) (Empire)/Sinestro - Futures End 001 (2014) (Digital) (Nahga-Empire).cbr
14-Oct-2018 14:21:51 - INFO :: mylar.duplicate_filecheck.2221 : Thread-15 : [DUPECHECK] Duplication detection returned no hits. This is not a duplicate of anything that I have scanned in as of yet.
14-Oct-2018 14:21:51 - INFO :: mylar.Process_next.1744 : Thread-15 : [POST-PROCESSING] [2/89] Starting Post-Processing for Sinestro issue: 1
14-Oct-2018 14:21:56 - INFO :: mylar.run.184 : Thread-15 : [META-TAGGER] ComicRack tagging meta-tagging processing started.
14-Oct-2018 14:22:02 - INFO :: mylar.run.255 : Thread-15 : [META-TAGGER][COMIC-TAGGER] Successfully wrote ComicRack tagging [/Users/dan/Mylar/cache/mylar_gL_zxk/Sinestro - Futures End 001 (2014) (Digital) (Nahga-Empire).cbz]
14-Oct-2018 14:22:02 - INFO :: mylar.run.184 : Thread-15 : [META-TAGGER] Comicbooklover tagging meta-tagging processing started.
14-Oct-2018 14:22:06 - INFO :: mylar.run.255 : Thread-15 : [META-TAGGER][COMIC-TAGGER] Successfully wrote Comicbooklover tagging [/Users/dan/Mylar/cache/mylar_gL_zxk/Sinestro - Futures End 001 (2014) (Digital) (Nahga-Empire).cbz]
14-Oct-2018 14:22:06 - INFO :: mylar.Process_next.2072 : Thread-15 : [POST-PROCESSING] Sucessfully wrote metadata to.cbz (Sinestro - Futures End 001 (2014) (Digital) (Nahga-Empire).cbz) - Continuing..
14-Oct-2018 14:22:07 - INFO :: mylar.validateAndCreateDirectory.1369 : Thread-15 : [POST-PROCESSING][DIRECTORY-CHECK] Found comic directory: /Volumes/Storage/Comics/Sinestro (2014)
14-Oct-2018 14:22:08 - INFO :: mylar.Process_next.2244 : Thread-15 : [POST-PROCESSING] move successful to : /Volumes/Storage/Comics/Sinestro (2014)/Sinestro - Futures End 001 (2014) (Digital) (Nahga-Empire).cbz
14-Oct-2018 14:22:08 - ERROR :: mylar.tidyup.275 : Thread-15 : [POST-PROCESSING] /Volumes/Storage/Import/Comics/Futures End Month (One-Shots) (2014) (Digital) (Empire) not empty. Skipping removal of directory - this will either be caught in further post-processing or it will have to be manually deleted.
14-Oct-2018 14:22:08 - INFO :: mylar.foundsearch.857 : Thread-15 : [POST-PROCESSING][UPDATER] Setting status to Post-Processed in history.
14-Oct-2018 14:22:08 - INFO :: mylar.foundsearch.914 : Thread-15 : [POST-PROCESSING][UPDATER] Updating Status (Post-Processed) now complete for Sinestro issue: 1
14-Oct-2018 14:22:08 - INFO :: mylar.Process_next.2404 : Thread-15 : [POST-PROCESSING] Post-Processing completed for: Sinestro #1
14-Oct-2018 14:22:08 - INFO :: mylar.duplicate_filecheck.2089 : Thread-15 : [DUPECHECK] Duplicate check for /Volumes/Storage/Import/Comics/Futures End Month (One-Shots) (2014) (Digital) (Empire)/Sinestro - Futures End 001 (2014) (Digital) (Nahga-Empire).cbr
14-Oct-2018 14:22:08 - WARNING :: mylar.duplicate_filecheck.2093 : Thread-15 : [DUPECHECK] File cannot be located inlocation specified. Something has moved or altered the name.
14-Oct-2018 14:22:08 - WARNING :: mylar.duplicate_filecheck.2094 : Thread-15 : [DUPECHECK] Make sure if you are using ComicRN, you do not have Completed Download Handling enabled (or vice-versa). Aborting
14-Oct-2018 14:22:08 - ERROR :: mylar.excepthook.315 : Thread-15 : Uncaught exception: Traceback (most recent call last):
  File "/Users/dan/Mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/dan/Mylar/mylar/PostProcessor.py", line 1313, in Process
    if dupthis['action'] == 'dupe_src' or dupthis['action'] == 'dupe_file':
TypeError: 'NoneType' object has no attribute '__getitem__'

Traceback (most recent call last):
  File "/Users/dan/Mylar/mylar/logger.py", line 337, in new_run
    old_run(*args, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/dan/Mylar/mylar/PostProcessor.py", line 1313, in Process
    if dupthis['action'] == 'dupe_src' or dupthis['action'] == 'dupe_file':
TypeError: 'NoneType' object has no attribute '__getitem__'

It seems to process Sinestro Futures End 001 fine, then it goes back to try and process it again and sure enough because move is on the file isn't there any more. 

Our esteemed leader suggested that he thought the issue in #2084 was that two valid issues were being matched. Seems like that might be the case here as well.

**Comment by evilhero** [comment] 2018-10-14 12:47
If your completed download handling isn't enabled in addition to using comicRN (you can't use both options), then it's probably identical to #2084, which has been problematic for me in tracking down the exact underlying code causing the problem.

And LOL @ esteemed leader ;)

**Comment by dantreacy** [comment] 2018-10-14 12:52
Yeah completed download handling is off. 

Went through and double checked that as I'd see that mentioned before as an issue.

Just a question regarding that. is that better/preferred to use rather than ComicRN?  I seem to recall vaguely that is was mentioned somewhere that it was new?? I had a system that was working (for the most part so was reticent to change it) but I've been using this for quite some time on and off with some large gaps so I might have missed some new features.

**Closed** 2021-01-01 21:04 UTC
