### ISSUE TITLE
Error On Manual Load

### ISSUE THREAD

**Issue by Nolsen84** [evilhero/mylar#1108] opened 2015-08-16 22:43 UTC
So I just setup a new instance of Mylar and I'm trying to load my existing library.  It identifies the correct number of issues I have in the library, says "Starting mass importing.... XXX records" and then I get the following error.

Uncaught exception: Traceback (most recent call last):
File "/opt/Mylar/mylar/logger.py", line 159, in new_run
old_run(_args, *_kwargs)
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(_self.__args, *_self.__kwargs)
File "/opt/Mylar/mylar/librarysync.py", line 570, in scanLibrary
logger.fdebug("comicname: " + soma_sl['comicname'].encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 16: ordinal not in range(128)

Any help would be appreciated.

**Comment by evilhero** [comment] 2015-08-16 23:14
It looks like you have some filenames with the º character within, which is obviously choking mylar (it tries to handle most, but it's not inclusive) - most likely as a degree symbol I would imagine.

If you remove the character,  or remove said filenames from the scan directory it should proceed as normal. I'll look into this but it probably won't be a quick fix for a turnaround time (unicode conversions never are).

**Comment by Nolsen84** [comment] 2015-08-16 23:20
Thanks for the help and the quick reply. I'll give it a shot in a minute here and let you know what I figure out.

**Comment by voor** [comment] 2015-12-11 18:36
@evilhero Have you considered just moving Mylar to running in UTF8 to avoid these errors?  Seems like I'm hitting `UnicodeDecodeError` fairly often on imports as well.

**Comment by evilhero** [comment] 2015-12-12 01:20
@voor: mylar actually has everything in utf8 within the db. The problem is the logger has to write the information to the .log files and in some cases where I've miswritten the logging statement it fails with the UnicodeDecodeError (ie. Usually because it's trying to convert a variable to a str (variable) and it can't do that)

**Comment by voor** [comment] 2015-12-12 01:42
So I get the following in my logs:

```
2015-12-11 20:41:23	ERROR	Uncaught exception: Traceback (most recent call last):
File "/home/media/git/mylar/mylar/logger.py", line 159, in new_run
old_run(*args, **kwargs)
File "/usr/lib64/python2.7/threading.py", line 766, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/media/git/mylar/mylar/librarysync.py", line 570, in scanLibrary
logger.fdebug("comicname: " + soma_sl['comicname'].encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 10: ordinal not in range(128)
2015-12-11 20:41:03	INFO	Starting mass importing...5875 records.
```

The problem is, I've got 5875 records (just rebuilt the computer, didn't keep mylar's old settings unfortunately), so it's a little staggering to go through all of those.  Couldn't it catch the exception on *that* entry and keep trying the other ones?

**Comment by evilhero** [comment] 2015-12-12 01:48
Yep most definitely, or like I had mentioned - even removing that line entirely should allow it to continue scanning. Ideally it would trap the error, record it and mark the given issue/series as having a problem and then continue on trucking. At the very least it should log the error and continue.

**Comment by voor** [comment] 2015-12-12 05:01
I'm not a Python programmer, but there's a lot of occurances of this kind of issue, not sure if any of this helps:

https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte

```
# encoding=utf8  
import sys  

reload(sys)  
sys.setdefaultencoding('utf8')
```

http://nedbatchelder.com/text/unipain/unipain.html#22

Possibly:
```
logger.fdebug("comicname: " + soma_sl['comicname'].encode('utf-8','ignore'))
```

**Comment by ChrisWeiss** [comment] 2016-03-13 01:28
FWIW - I'm seeing the same thing. It'd be handy if Mylar would at least ignore the error and continue, but as it is, it stops a mass import dead in it's tracks.
Here's another example:
`2016-03-12 15:11:13	ERROR	Unable to complete the scan: 'ascii' codec can't encode character u'\xbd' in position 0: ordinal not in range(128)
2016-03-12 15:11:13	INFO	Successfully retrieved some tags. Lets see what I can figure out.
2016-03-12 15:11:12	INFO	Attempting to read tags present in filename: /share/Public/Comics/Alphabetical/L/The Living Corpse (Zenescope Entertainment)/The Living Corpse V2007 #½ (July, 2007).cbz`

Obviously, it doesn't like half-issues :)

**Comment by evilhero** [comment] 2016-03-14 01:46
Yeah ideally I'd like it to subset the list into 2 portions for each issue : successful or failed, with the reason as well. Then allow the users to view the reasons why the import failed for  certain issues and be able to rectify them within mylar. 

Obviously Unicode is a pita to code against, although as an aside mylar isn't erroring out/crashing when it encounters the Unicode it can't handle, it just aborts and the user can continue using mylar. So on the plus, further trapping  of Unicode exceptions should be a pretty viable option given that notion. 

The importer is a continual WIP, almost every development commit over the last few months has had something to do with it, so I'm constantly trying to improve on things. 

I'll try and address the aborting /finish the scan regardless option over the next few commits hopefully.  I'll also try and tag this issue in the commit so you'll know it's been updated for testing.

**Comment by evilhero** [comment] 2017-08-25 02:39
The majority of unicode errors should now be trapped properly and allow for the continuation of the scan. Once the scan has completed, it will display the information for all files it wasn't able to scan in / had errors.
Closing this issue now (since it's been over a year), but if issues persist - please just open a new issue ticket.

**Closed by evilhero** 2017-08-25 02:39 UTC
Labels: BUG, Support, WIP
