### ISSUE TITLE
Downloading items already in Library

### ISSUE THREAD

**Issue by IPyandy** [evilhero/mylar#921] opened 2015-01-11 22:57 UTC
I've encountered, that when a comic is **ever** marked as **Wanted** but then manually added to the library and the volume refreshed or not. The status shows as **downloaded** and points to the correct file. But for some reason, it keeps looking for that comic and re-downloads. It's an odd behavior, since it shows as **Downloaded** in the database.

**Comment by IPyandy** [comment] 2015-01-12 02:39
Bit of an update, if those previously **Wanted** issues are marked **Skipped** then shutdown / start mylar, the issue goes away, seemingly. I can manually add those issues to the library and mylar does not check again for them.

**Comment by evilhero** [comment] 2015-01-12 17:19
If you encounter any errors between the point of marking it as Wanted (or scanned as Downloaded), and haven't restarted Mylar it's very likely it's using some stagnant values for things and the result could mean that it redownloads things (this is erratic behaviour and it's mainly due to not restarting after any type of error occurs). I would guess (at this point), that at some point between Marking it as Wanted/Downloaded and the re-search for the given issue, that an error of some kind was encountered (It's also possible it was an error prior to this point, but again the focal point is not restarting after the error).

Can you restart Mylar, and try that workflow again to see if it still occurs ? I can't seem to duplicate it on my end - which was Marking an issue Wanted, having it search then (cause that's what it does), then moving the file into the series directory, clicking on Refresh, status changed to Downloaded. Then clicking on force re-check on the Upcoming tab.

**Comment by IPyandy** [comment] 2015-01-13 00:17
I'll give it a shot and let you know.

**Comment by razambon** [comment] 2015-01-15 03:45
I just had a number of items shift to skipped from archived.  As of last week, all was setup and fine...I went through and actually manually set everything last week when going through.   

Any logs that I could provide or more info?  This seems to be related.  Or I can create other ticket.

**Comment by razambon** [comment] 2015-01-27 04:55
This happened again and expanded what's marked as not have...definitely annoying.

**Comment by evilhero** [comment] 2015-01-27 07:38
I havent' been able to reproduce this as of yet on my box to even try and garner a look at. If you have any information - which series' it re-grabbed / do you have mulitple volumes of the same series in your watchlist / were they new releases (from weeklypull) / did something initiate that kicked off the downloading ?

I'm still looking into it, but first I have to figure out how to duplicate the problem so I can try to troubleshoot things better.

**Comment by razambon** [comment] 2015-01-28 16:03
So, the workflow I did was the following:
1. Comicrack - Migrate everything to my archive directory.
2. Mylar - Go through and set every series to 'archived' as appropriate.

So, this shouldn't be occurring as far as I can tell.  It sets the status to skipped, which wouldn't be bad but the Progress/"Have" Bar shows issues missing which makes it hard to track.  

Example comics where this has occured:
- Abe Sapien
- Alien vs. Predator: Fire and Stone
- Aquaman and the Others
- Avengers
- Batman Eternal
- Captain Marvel
- Constantine
- Cyclops

I'm going to go through, reset everything to correct status and then try to track more closely.  If I can catch when this occurs I'll grab the log and post it.

**Comment by evilhero** [comment] 2015-01-29 08:30
Do you recall what the status' were before you migrated the issues out of their respective series directories ? What's supposed to happen, is if Mylar is able to set the status as Downloaded (on a successful file-check), and the files get moved out of the directory - the status is supposed to revert to Archived, since it can no longer find them. Thinking about this too, if the status was in Snatched status, I'm not sure if it would mark it as Archived or not.

**Comment by razambon** [comment] 2015-01-30 01:04
They were manually set to archived.

**Comment by evilhero** [comment] 2015-01-31 01:09
Ok, here's another question - do you guys have the 'Mark All Issues as Wanted' option enabled in the configuration ? (not the 'Mark All Upcoming Issues as Wanted' option)

**Comment by razambon** [comment] 2015-01-31 02:07
No, Mark All Issues as Wanted is unchecked.  Setting is Mark All Upcoming Issues as wanted.  Now, I DID have Mark All Issues as Wanted set before when I had this problem and I unset it and it seemed to fix it.  Then this happened again.

There is another issue that I'm thinking may be related.  Sometimes in the "This Week" list, certain Series don't get marked as the upcoming issue being wanted.  I've readded the series on them - this could cause it.  However, I definitely didn't do this on the 20+ series that I've seen the changing to skip issue occur with.

**Comment by evilhero** [comment] 2015-01-31 02:22
Yeah, I've narrowed it down to two possible things - the 'Force Update Active Comics' and the 'Refresh/Recreation of the weeklypull-list', both of which run a differing version of a Refresh Series on the existing series and takes different action depending on certain factors. I haven't figured out exactly where as of yet, but as of right now - those are the two areas that I'm focusing on and going through attempting to figure things out.

I've also figured out that if db locking occurs during one (or both) of the above actions, it can possibly nullify the existing issue data set which would erase any current Status' that exist for a given series.So far I've only been able to confirm that happening to one other individual - which resulted in the re-download of a bunch of issues because they went from Archived, to a dblock, to Skipped (because Mylar had to regenerate everything from scratch from CV in that case), then to Wanted automatically due to settings.

Again, I haven't any idea if that last one is identical to this issue - although I'm sure they're related to some degree as the symptoms seem to be the same.

Thanks for taking the time to give additional information - since I can't seem to duplicate this as of yet, it's really hard for me to troubleshoot/fix just because of the sparse amount of information coming in, mainly due to the logs rolling over while this goes on unatttended so there's no trace left as to why it's happening.

**Comment by razambon** [comment] 2015-01-31 04:24
You know - I have another issue that may be related that I may not have
realized.  Sometimes mylar's interface just stops responding.  So I kill
the service on the server and restart it.   Let me see if next time that
happens I notice this occuringor if it occurs during the next weekly update.

And keep up the great work on this.  Was just thinking the other day how I
don't know how I'd ever replace Mylar. :)

On Fri, Jan 30, 2015 at 9:22 PM, evilhero <notifications@github.com> wrote:

> Yeah, I've narrowed it down to two possible things - the 'Force Update
> Active Comics' and the 'Refresh/Recreation of the weeklypull-list', both of
> which run a differing version of a Refresh Series on the existing series
> and takes different action depending on certain factors. I haven't figured
> out exactly where as of yet, but as of right now - those are the two areas
> that I'm focusing on and going through attempting to figure things out.
>
> I've also figured out that if db locking occurs during one (or both) of
> the above actions, it can possibly nullify the existing issue data set
> which would erase any current Status' that exist for a given series.So far
> I've only been able to confirm that happening to one other individual -
> which resulted in the re-download of a bunch of issues because they went
> from Archived, to a dblock, to Skipped (because Mylar had to regenerate
> everything from scratch from CV in that case), then to Wanted automatically
> due to settings.
>
> Again, I haven't any idea if that last one is identical to this issue -
> although I'm sure they're related to some degree as the symptoms seem to be
> the same.
>
> Thanks for taking the time to give additional information - since I can't
> seem to duplicate this as of yet, it's really hard for me to
> troubleshoot/fix just because of the sparse amount of information coming
> in, mainly due to the logs rolling over while this goes on unatttended so
> there's no trace left as to why it's happening.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evilhero/mylar/issues/921#issuecomment-72300292>.
>



-- 
Robert A. Zambon, Ph.D.

**Comment by rupaschomaker** [comment] 2015-01-31 04:28
Interface locked up is a good indication that the db is experiencing
locking issues.

**Comment by IPyandy** [comment] 2015-01-31 16:22
I don't experience these interface locking issues, they're just random downloads of things already in the library if they were once marked as wanted. The only way to stop this from happening for me is, if I find the issues for some reason manually. 

1) mark the previously wanted issues as skipped
2) restart mylar
3) do a manual process

If I skip step two, then it'll continue searching for those issues even though they were already added to the library.

**Comment by evilhero** [comment] 2015-01-31 19:46
Are you making any sort of configuration change during that process? Or prior to the process even - but in either case are you restarting mylar after the configuration changes? Not restarting after configuration changes causes very weird problems until a restart happens. 

Restarting mylar in your steps would indicate it needs a reload to clear things or at least perform the startup sequence to get things back in order.

**Comment by IPyandy** [comment] 2015-01-31 20:07
no configuration changes

**Comment by razambon** [comment] 2015-02-12 16:33
Ok.  This just happened again.  Below is a portion of the log where the problem seemed to occur.  There's multiple queries/threads going on, but Batman Eternal is one of the series that had everything aligned right/marked as archived and now is half marked as skipped.  


2015-02-04 15:59:43 	INFO 	Update complete
2015-02-04 15:59:38 	INFO 	Finished grabbing what I could.
2015-02-04 15:59:38 	INFO 	Finished searching via :api. Issue not found - status kept as Wanted.
2015-02-04 15:59:38 	INFO 	Could not find Issue 44 of Batman Eternal(2014) using http://localhost:90/
2015-02-04 15:59:35 	INFO 	Shhh be very quiet...I'm looking for Batman Eternal issue: 44 (2015) using http://localhost:90/ (newznab)
2015-02-04 15:59:35 	INFO 	Could not find Issue 44 of Batman Eternal(2014) using experimental
2015-02-04 15:59:32 	INFO 	Shhh be very quiet...I'm looking for Batman Eternal issue: 44 (2015) using experimental
2015-02-04 15:59:32 	INFO 	Could not find Issue 44 of Batman Eternal(2014) using dognzb
2015-02-04 15:59:29 	INFO 	pausing for 60 seconds before continuing to avoid hammering
2015-02-04 15:58:31 	INFO 	pausing for 60 seconds before continuing to avoid hammering
2015-02-04 15:58:28 	INFO 	pausing for 60 seconds before continuing to avoid hammering
2015-02-04 15:57:30 	INFO 	pausing for 60 seconds before continuing to avoid hammering
2015-02-04 15:57:30 	INFO 	Shhh be very quiet...I'm looking for Batman Eternal issue: 44 (2015) using dognzb
2015-02-04 15:57:30 	INFO 	search provider order is ['dognzb', 'Experimental', 'newznab:http://localhost:90/']
2015-02-04 15:57:30 	INFO 	Issue Title given as : spiral
2015-02-04 15:57:30 	INFO 	Attempting to grab wanted issues for : Batman Eternal
2015-02-04 15:57:30 	INFO 	Finished checking for comics on my watchlist.
2015-02-04 15:57:28 	INFO 	Checking the Weekly Releases list for comics I'm watching...
2015-02-04 15:57:28 	INFO 	Checking this week pullist for new issues of Batman Eternal
2015-02-04 15:57:28 	INFO 	[FILE-RESCAN] I have physically found 5 issues, ignored 0 issues, snatched 0 issues, and accounted for 0 in an Archived state [ Total Issue Count: 5 / 44 ]
2015-02-04 15:57:28 	INFO 	[FILE-RESCAN] Total files located: 5
2015-02-04 15:57:28 	INFO 	[FILE-RESCAN] Updated the status of 39 issues for Batman Eternal (2014) that were not found.
2015-02-04 15:57:26 	INFO 	pausing for 60 seconds before continuing to avoid hammering
2015-02-04 15:57:26 	INFO 	Shhh be very quiet...I'm looking for The Transformers Primacy issue: 4 (2015) using dognzb
2015-02-04 15:57:26 	INFO 	Alternate Search pattern detected...re-adjusting to : The Transformers Primacy 2015[u][t][+]
2015-02-04 15:57:01 	INFO 	[FILE-RESCAN] Now checking files for Batman Eternal (2014) in :Batman Eternal (2014)
2015-02-04 15:57:00 	INFO 	[FILE-RESCAN] Now checking files for Batman Eternal (2014) in Z:\ServerFolders\Downloads\- Comics\DC Comics/Batman Eternal (2014)
2015-02-04 15:57:00 	INFO 	Updating complete for: Batman Eternal
2015-02-04 15:56:47 	INFO 	[ComicVine API] Comicvine API count now at : 10 / 400 in 5.48 minutes.
2015-02-04 15:56:26 	INFO 	pausing for 60 seconds before continuing to avoid hammering
2015-02-04 15:56:15 	INFO 	Now adding/updating issues for Batman Eternal
2015-02-04 15:56:14 	INFO 	Sucessfully retrieved issue details for Batman Eternal
2015-02-04 15:56:12 	INFO 	previous version detected as None - seeing if update required
2015-02-04 15:56:12 	INFO 	Successfully retrieved cover for Batman Eternal
2015-02-04 15:56:12 	INFO 	Image header check: jpeg
2015-02-04 15:56:12 	INFO 	Directory (Z:\ServerFolders\Downloads\- Comics\DC Comics/Batman Eternal (2014)) already exists! Continuing...
2015-02-04 15:56:10 	INFO 	Sucessfully retrieved details for Batman Eternal
2015-02-04 15:56:10 	INFO 	Now adding/updating: Batman Eternal
2015-02-04 15:56:07 	INFO 	[DIRECTORY-CHECK] Found comic directory: Z:\ServerFolders\Downloads\- Comics\DC Comics/Batman Eternal (2014)
2015-02-04 15:56:04 	INFO 	Starting update for 1 active comics
2015-02-04 15:56:04 	INFO 	Series is out of whack. Forcibly refreshing series to ensure everything is in order.

**Comment by evilhero** [comment] 2015-02-12 16:38
Can you post the mylar.log file showing the above ? There's specific lines in there that would help see what's going on (namely I put in specific issue counts and issue status' grabs prior to any changes).

**Comment by razambon** [comment] 2015-02-12 16:56
Hrm.  Where is it?  Pulled the Mylar.log.# files and it's not in there.  Showing up in the interface, but my actual files in the log directory only go back to 2/9.

**Comment by evilhero** [comment] 2015-02-12 17:42
It should be in your normal log locations - whatever you can see in the GUI log, you should have a record of somewhere in the logs files (anywhere from mylar.log to mylar.log.5)

**Comment by razambon** [comment] 2015-02-12 17:55
Hrm.  Odd.  I have all those log files, but the info doesn't seem to be in them.  Definitely in the UI.

**Comment by razambon** [comment] 2015-02-12 21:42
Are the logs cached by the UI?  I can't figure out what's up.  I do have a 1mb limit on the logs, which I can increase, but I can't see how the logs are being displayed all the way back to 2/4 (and being loaded) if they aren't stored somewhere other than the 6 text files I'm able to identify in the mylar/logs directory.

**Comment by evilhero** [comment] 2015-02-12 22:02
Nope just in the txt files that's it. If you're hitting the back button on your browser, that would be the only caching that would be happening. 

Are you running more than one instance of mylar and/or have you installed it in different locations maybe?

**Comment by razambon** [comment] 2015-02-12 22:09
Nope....I'm baffled.

I could try restarting mylar and see if it goes poof.

**Comment by evilhero** [comment] 2015-02-12 22:13
Yeah you might have to, which would only wipe out the oldest portion of the logs so it might still retain the portion that we're after. 

You're on dev right?

**Comment by razambon** [comment] 2015-02-12 22:14
So now the UI log is showing 22 lines....while the text logs still exist.  SO...that may be a different bug we just found :).

**Comment by evilhero** [comment] 2015-02-12 22:27
Do you have anything in the filter field on the logs screen? Like even a blank space?

**Comment by razambon** [comment] 2015-02-12 22:38
Nope, was nothing.  23.  Did a restart, 23 lines.  One thing - restarting almost definitely made more items popup where archive was missed.  Problem is I can't determine WHEN it happened.  I'm going to set everything as archived, delete all the logs (or, move them), then wait and see.  I've increased the log size to 10mb, so that SHOULD capture it.  

Fairly certain that the items on 2/4 were due to accidentally tripping a circuit breaker as well - restarting my server.  

I'll run a few tests later tonight (restart mylar) to see if I can force the issue.

**Comment by razambon** [comment] 2015-02-12 22:40
...interesting thing.  All the comics that are screwed up are ones that recently downloaded an issue - as within the past week or two.

**Comment by razambon** [comment] 2015-02-13 03:14
No luck.  I'll keep trying various things and tracking.  Hopefully the larger logfile size will let me actually capture the details next time.

**Comment by razambon** [comment] 2015-02-17 19:29
Still digging in.  Got the UI lockup issue and it's a database lock ( WARNING :: CP Server Thread-9 : Database Error: database is locked is one example log item).  The thing is I'm using MySQL via an XAMPP install and not SQLite.  So, not sure what's causing the lock issue.  

Only way to stop it is to kill/restart mylar.  Still working on getting a repeat of the core issue I was reporting though.

**Comment by evilhero** [comment] 2015-02-17 20:17
Well if you have python installed (most nix systems do by default), sqlite3 is packaged with it. If you only had MySQL, mylar wouldn't work as it's built for sqlite3 usage only (the db calls would be entirely different). 

The database looking I'm seeing more myself lately, so I've been spending a lot of time trying to rework things so they aren't occurring (or at least are better handled). The db locks are most likely what is causing the redownloading problems as myself and others have pretty much isolated it down to being a main culprit, if not the culprit.

**Comment by razambon** [comment] 2015-02-17 21:40
Thanks Evilhero.  If I see anything popup and can get some log info for you, I'll post it as well.

**Comment by polybius01** [comment] 2015-04-08 20:19
If I could add my problem to this report as well. I have existing comics that I add to the library. I recheck the files for that series and they all show up green and marked as Downloaded. Oddly though, Mylar seems to think that they aren't there and starts to download them but does't remove any because of duplicates (my existing ones are CBZ and the ones being downloaded are CBR).

Also, could you add an option to convert incoming comics to one format or the other? (CBZ or CBR)

By the way, this is a great program! Thanks!!

**Comment by evilhero** [comment] 2015-04-08 20:35
I'm pretty sure at this point it's a race issue with stagnant data that's causing these problems. What I mean by that is that when you do the check and it marks them as Downloaded, there's something else going on in the background (rss check or a force check search) that's using the data as it was present at the time it started to run. For example, let's say you have 100 issues on your Wanted list, the 6hr mark hits and mylar does a force search with the 100 issues in queue to check. Then the rss feed check goes off a few weeks minutes later, with the same 100 issues (because if you have more than one Newznab provider/dog/nzb.su it waits 60s between next attempts). Because the rss doesn't have the same wait-delay restrictions it flies through the 100 in queue and finds say 20 issues. It then marks them as snatched and then downloaded (if you're using sab/nzbget). The force search is still going on with the 100 less what it has gone through but the status is still of wanted because it hasn't refreshed the data (it can't at that point). So eventually, like a few hrs even after the initial grab depending in how fast or cycles through the search, it finds them again and redownloads the issues again because as far as it knows it's still in wanted status because that's what it was when it grabbed the list at the start. 

I've actually witnessed this happen first-hand when I was in  front of  the machine - I just haven't a clue as of yet how to go about solving it so it's a dynamic dataset without causing locking /stability issues. 

The cbr /cbz conversion happens automatically if you have metatagging enabled (during normal post-processing /manual post-processing), but the request for just the conversion option is in the pipe already ;)

**Comment by polybius01** [comment] 2015-04-08 20:41
Wow, fast response! Thanks!

**Closed** 2017-08-25 02:27 UTC
Labels: BUG, Cannot reproduce, Need More Info, WIP
