### ISSUE TITLE
Node.js error when accessing 32P

### ISSUE THREAD

**Issue by silentArtifact** [evilhero/mylar#2186] opened 2019-02-04 14:55 UTC
Hello!

I've started getting the following error when trying to search 32P automatically. Testing my credentials in the settings shows as successful, and there's no problems with my account. Node is installed and works fine (as far as I can tell). Ideas? Currently running on a Synology NAS through Docker, on the most recent update.

`[32P-AUTHENTICATION] Got an exception when trying to login: Missing Node.js runtime. Node is required and must be in the PATH (check with `node -v`). Your Node binary may be called `nodejs` rather than `node`, in which case you may need to run `apt-get install nodejs-legacy` on some Debian-based systems. (Please read the cfscrape README's Dependencies section: https://github.com/Anorov/cloudflare-scrape#dependencies.`

**Comment by evilhero** [comment] 2019-02-04 15:13
Pretty much what the error says I'd think. Your node version either isn't in the path accessible by mylar or its not named node.
```node - - v``` from within the docker container will tell you. If it says not found, then you need to install the legacy as indicated, or even symlink nodej to node.

**Comment by silentArtifact** [comment] 2019-02-05 00:52
It's definitely missing. So, I'm a bit... new to this. Do you know of any place with instructions on how to either install the legacy, or... well, I'm not even completely sure what it is to symlink nodej to node.

**Comment by barbequesauce** [comment] 2019-02-05 00:55
Give us a day or two, 32p has some new protections in place and we are working with them to restore access. Current tests are looking good...

**Comment by silentArtifact** [comment] 2019-02-05 12:37
> 
> 
> You can go here to download it: https://nodejs.org/en/download/
> 
> I had the same problem, and fixed this, though I'm still having problems with 32pages. Getting ready to file the bug report.

This is probably a horribly dumb question, but how did you get it to install? I've grabbed the `.pkg` file, but I'm not finding any way of getting it to actually... install, I suppose, within the container.

**Comment by Bigfireq** [comment] 2019-02-05 21:38
I'm downloading the installer, which is an .MSI executable that just runs on your Windows box.

**Comment by silentArtifact** [comment] 2019-02-05 22:15
Ah, I guess that's part of my issue, I'm running inside a docker container
on a Synology NAS. Most installers won't function at all.

**Comment by arqcan** [comment] 2019-02-06 22:12
I am having the same issue, however i am on windows and I have installed the .MSI executable and the issue is still present.

**Comment by evilhero** [comment] 2019-02-06 22:24
@silentArtifact yoi  an probably try doing a ```sudo apt-get install node``` to install it on your system.

@arqcan make sure that you've installed it with the path option enabled in their installer. If you're getting a different error other than the node error (specifically), you need to make sure you're up to date on your branch.

**Comment by arqcan** [comment] 2019-02-06 22:53
@evilhero thanks all sorted now, i'd missed the option to add to path.

**Comment by silentArtifact** [comment] 2019-02-07 05:37
@evilhero apt-get doesn't seem to work inside the container. It's also probably worth noting that node's installed on the NAS already, and that this issue only started a few weeks ago; before that, it worked just fine. I'm going to try re-installing the container from scratch.

**Comment by Xtermie** [comment] 2019-02-09 11:01
I can say i'm having the exact same issue as silentArtifact on my Synology NAS. Credentials are correct and using auth mode.

`

2019-02-09 10:54:00 | ERROR | [32P-AUTHENTICATION] [LOGIN FAILED] Disabling 32P provider until login error(s) can be fixed in order to avoid temporary bans.
-- | -- | --
2019-02-09 10:54:00 | WARNING | [32P-AUTHENTICATION] Both session key and credential-based logins failed.
2019-02-09 10:54:00 | ERROR | [32P-AUTHENTICATION]  Got an exception when trying to login: Missing Node.js runtime. Node is  required and must be in the PATH (check with `node -v`). Your Node  binary may be called `nodejs` rather than `node`, in which case you may  need to run `apt-get install nodejs-legacy` on some Debian-based  systems. (Please read the cfscrape README's Dependencies section:  https://github.com/Anorov/cloudflare-scrape#dependencies.

`

**Comment by Xtermie** [comment] 2019-02-09 11:41
Managed to fix it.

1. Under registry in Docker downloaded the latest mylar image again.
2. Stopped container running Mylar
3. Select Mylar Container, go to action and select Clear.
4. Start Mylar container again
5. Mylar gave a notification after starting up that it was an unknown build and asked to update
6. Succces, after 15min I saw snatches and downloads again.

Hope this helps someone :)

**Closed** 2021-01-01 21:03 UTC
