### ISSUE TITLE
Strange errors in log. 

### ISSUE THREAD

**Issue by z4ck38** [evilhero/mylar#999] opened 2015-04-30 19:52 UTC
I started a new thread, so as not to hijack the other one i was in. (sorry about that)

Starting this week I've been experiencing issues with mylar downloading issues. I've also been having issues with the specific pages for each comic not updating to reflect new issues. 

I saw a guy who had a similar issue (can't find thread now) but he was told that an update was going to be pushed last night and that should fix it. Well I wasn't able to do the update through the web gui and I was getting an error msg saying that git hub could not be contacted...

Odd i though. I don't know a lot about how git hub works, so i saved my db / ini files and re-installed. 

i posted an error on that other thread that was a permissions thing. I forgot to change the group owner to ztaylor:ztaylor as specified in my upstart script. This has been fixed. 

drwxrwxrwx 14 ztaylor ztaylor 4096 Apr 30 14:42 Mylar

So now what i did was manually refresh a comic so that it would show there was a missing issue and then manually tried to download that issue. no dice. 

I'm fairly new to linux (ubuntu 14.04.02 on a dell r200) and I've always try to figure out things on my own first, but i'm at a real loss here, especially since i've had this working for the last few weeks with out issue.

here is my current logfile: http://pastebin.com/y7af93Ej

I appreciate all of your help.

**Comment by ztaylor38** [comment] 2015-04-30 19:53
this is the version of the software the web gui shows me to be using: Version: b6b8c6293af8587ce03e9aeb7b74c96f95f9e111 (development)

**Comment by evilhero** [comment] 2015-04-30 20:54
First, thanks for starting a new issue. It gets really confusing (for myself) to try and follow an issue that contains more issues that unfortunately don't relate specifically to the original post. In doing so, it allows me to divide up my time abit more and can concentrate on the issues at hand instead of them being missed, or forgotten about.

Now on to your issue!

I remember someone having almost identical issues and it turned out that he was using dognzb, and because of their recent api problems the results being returned were hit and miss. This went for actual nzb files that were being retrieved as well - so when Mylar goes to retrieve the nzb file it pulls down an empty nzb file which doesn't contain anything and errors out with that exact message. I see you're using dognzb, so my first thought would be to do this. Go into your configuration screen and disable the use of dognzb. Save the changes, and restart mylar (it's required for provider changes as the provider search order gets re-generated on startup). Then try doing a manual search for the issue it's having problems with (go to the series page on your watchlist, and click on the magnifying glass - it starts an immediate search, but if it's not found it won't change the status from what it is. I'm fairly confident that in doing so, it will get the result and not have any problems.

As an aside, another fellow had said he was getting no results, and it had turned out to be his ISP DNS was blocking the site (or was having problems retrieving the site) - so it was continually searching and returning no results. Changing his DNS to use google DNS solved the problem for him.

**Comment by ztaylor38** [comment] 2015-04-30 21:06
No problem. I figured it would be easier to address separate issues in separate threads. I really appreciate the work you do for the community just by developing mylar and I especially appreciate any end-user support you're willing to give!

So I removed dognzbd - no change
log after removing dognzb: pastebin.com/WNHrweRd

i also changed the dns server on my server to that of google and restarting networking on server - no change
log after changing dns - pastebin.com/L8fjcZfC

Thanks again for your help. I had all of this working last week and hadn't changed anything, so I'm really really at a loss for what the issue could be. 

I also checked my config file to make sure there weren't any "phantom" search providers set up.

**Comment by evilhero** [comment] 2015-04-30 21:18
Ok,  so I was wrong about the dognzb thing although the results not changing means I know where it's dying off now. 

It would appear that it's an RSS caching issue of some sort. When mylar pulls down the rss feeds it caches the results into the db. In doing so it allows backlog searches to occur with the RSS option enabled and lessens the hits on the providers. The downside is that occasionally there are some incorrect urls for nzbs that filter into it (a nzb got deleted as it was incomplete or just bad, but the cache retains the results and it says it's there). 

We  came across this issue awhile ago and a gent put the code up but I hadn't committed the changes into the development branch as I couldn't reproduce the results to test it. 

Have you enabled the failed download handling option within mylar? I'm thinking if that's enabled it would mark the nzb that's causing the errors to be I  a failed status and then subsequent searching wouldn't use that result. 

Otherwise we have to find a way to get those bad entries out of your cache. Turning off rss feeds is one option but then you loose a big portion of the search function.

**Comment by ztaylor38** [comment] 2015-04-30 21:38
I don't have Failed Download Handling enabled, but I can do so if need be. 

In regards to RSS, i don't have that set up in the traditional sense of having my search provider queue up downloads into an rss feed that I've given to mylar. 

The way I've set mine up is that i just did a search from the main page for the comics that I wanted to download and then "subscribed" to that book by clicking "add this comic".

I don't know if this is pertinent, but I'm tracking like 85 series in mylar.  

I'm turning on failed download handling and trying to download something again.

Also I mentioned it before, but i wanted to mention again, I'm unable to update from github from the web gui and my attempts at updating from the CLI ended up with me re-installing...

so after turning on failed download handling it tried nzb.su and then went to nzb.geek and was sucessfull. I'm wondering if this is a nzb.su / dognzb issue since i know dog is going down tomorrow. 

here is the log now: pastebin.com/zcmRK55U

one last question, should the things marked as wanted in the this week tab be listed in the wanted tab?

**Comment by ztaylor38** [comment] 2015-04-30 21:38
the reason i ask is because i see this:
2015-04-30 16:38:27	INFO	I have copied 0 issues from this Week's pullist as requested.

**Comment by evilhero** [comment] 2015-04-30 22:01
Well the rss option is different than what you're thinking I believe. In mylar, enabling the rss option tells mylar to check all your providers for the most recent comic postings via an rss feed. You don't have to do anything, aside from providing your UID for it to be able to access the rss. 

It could be a dog/nzb.su problem as both have had major problems with their api lately so it wouldn't surprise me. 

Glad the failed handling worked!

**Comment by ztaylor38** [comment] 2015-04-30 22:13
for sure man. Thank you again for the help. I'm def going to donate when I get some extra money!

**Comment by evilhero** [comment] 2015-04-30 22:33
The items marked as Wanted in the this week tab should be listed in the Wanted tab yes - if they're not you can do a Recreate  pullist option from the Pullist tab and it will recreate the pullist and Recheck against your watchlist. 

The workflow is:
- new pullist is available 
- pulls down and checks against watchlist 
- marks any matches as Wanted on the pullist. 
- checks said issues against comicvine to see if the issue information is available yet. This is typically on Tues (sometimes Wed) for new releases. 
- If it's not available, it puts it in the Upcoming section of the Wanted tab in a Wanted status. It then checks comicvine periodically to see if the issue data is available, when it is it moves it out of the Upcoming section and into the Wanted section, and the issue will appear in the series detail page as well. 
- If it is available mylar will mark it as Wanted, and it will appear in the Wanted tab and the upcoming tab as well as in the series detail page. 
- once Thursday hits, the upcoming section gets wiped out as all issue data is available. 
- when an issue get post-processed that's on the weekly pullist there is am option on the pullist page to copy said issues into a weekly directory. Enabling this option will force mylar to copy issues as they are post-processed into this weekly folder if they are on the weekly pullist. 

Hopefully that explains things abit better :)

**Closed** 2021-01-01 21:08 UTC
