### ISSUE TITLE
Doesn't recognize newznab providers. 

### ISSUE THREAD

**Issue by MaxPower88** [evilhero/mylar#1155] opened 2015-11-07 05:57 UTC
I have two newznab providers enabled that are otherwise working (fine in sickbeard), yet I get this in the logs when I force check for wanted:

2015-11-07 06:56:10 ERROR   [WARNING] You have 0 search providers enabled. I need at least ONE provider to work. Aborting search.

**Comment by evilhero** [comment] 2015-11-07 15:17
Shutdown mylar,  edit the config.ini and delete the provider_order line entirely. Save the config.ini and start Mylar and it will start searching again.

If you don't restart mylar after a provider configuration change you'll get this error almost every time. I always tell people it's best to just restart mylar after any configuration change just to be safe.

**Comment by merlosus** [comment] 2016-09-04 02:47
I have the same problem and have deleted the line in config.ini with no success. even tried a fresh instance of mylar and only added the bare essentials and same issue.

**Comment by evilhero** [comment] 2016-09-04 03:34
You have to make sure mylar isn't running when you edit the config.ini. If you're getting that error, then the problem is the provider_order line, and it needs to be deleted.  It's caused when a user makes a provider change in the GUI (enabling/disabling), and not restarting mylar after saving the config. The provider order line only gets regenerated on startup.

**Comment by merlosus** [comment] 2016-09-04 03:49
Thanks for the prompt reply. I have shut down mylar and deleted the line, saved the file and done a restart  with the same resulting error. 
Traceback (most recent call last):
  File "C:\Users\Plex Server\mylar-master\mylar-master\mylar\logger.py", line 158, in new_run
    old_run(*args, **kwargs)
  File "C:\Python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Plex Server\mylar-master\mylar-master\mylar\search.py", line 1642, in searchforissue
    foundNZB, prov = search_init(comic['ComicName'], result['Issue_Number'], str(ComicYear), comic['ComicYear'], Publisher, IssueDate, StoreDate, result['IssueID'], AlternateSearch, UseFuzzy, ComicVersion, SARC=None, IssueArcID=None, mode=mode, rsscheck=rsscheck, ComicID=result['ComicID'], filesafe=comic['ComicName_Filesafe'])
  File "C:\Users\Plex Server\mylar-master\mylar-master\mylar\search.py", line 251, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, send_prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "C:\Users\Plex Server\mylar-master\mylar-master\mylar\search.py", line 824, in NZB_SEARCH
    issuedate_int = int(time.mktime(tm.timetuple()))
OverflowError: mktime argument out of range

Any other things that could be causing it?

**Comment by evilhero** [comment] 2016-09-04 04:00
Did the 0 provider error go away after the deletion from the config.ini? Also what nzb provider is the error getting generated from (you might have to read back through the log for it)? 

Someone else had mentioned the mktime error in the forums but the best we could come up with at that time was that the provider that was being used was returning an invalid posting date for a given search result which was causing the mktime error (mylar compares the posting date of the nzb to the publication date of the issue being searched). 

I had a quick fix that has to go into dev still, where if it encounters the mktime error it just drops the search result and continues onto the next search result. 

As long as you're on the development branch when the next commit goes up, it will be in it.

**Comment by merlosus** [comment] 2016-09-04 04:19
Yeah it did get rid of the 0 provider error. I changed out the provider from usenet-crawler to nzb.cat and it found and downloaded a comic. Thanks heaps for your help :)

**Comment by evilhero** [comment] 2016-09-04 04:23
No problem glad I could help abit. Would you happen to know what series/issue was being searched for that threw the mktime error? I haven't been able to duplicate on my end at all, and knowing the series and issue would help point me in the right direction as to what's happening.

**Comment by merlosus** [comment] 2016-09-04 05:10
it was searching The Amazing Spider-Man 1963 not sure exactly what issue sorry but I think it was multiple.

**Closed** 2021-01-01 21:08 UTC
