### ISSUE TITLE
SSL failing on indexer sites

### ISSUE THREAD

**Issue by DaveBrackets** [evilhero/mylar#1121] opened 2015-08-31 13:42 UTC
Hi guys,

I've been using Mylar for a while on my home server, but recently I've found it failing out with the sites that I use (nzb.su and omgwtfnzbs). Checked the logs and I get this:

31-Aug-2015 05:08:06 - INFO    :: SEARCH : Shhh be very quiet...I'm looking for Deadpool's Secret Secret Wars issue: 4 (2015) using nzb.su
31-Aug-2015 05:08:06 - DEBUG   :: SEARCH : calpha/cnumber: None / None
31-Aug-2015 05:08:06 - DEBUG   :: SEARCH : RSS Check: None
31-Aug-2015 05:08:06 - DEBUG   :: SEARCH : nzbprov: nzb.su
31-Aug-2015 05:08:06 - DEBUG   :: SEARCH : comicid: 82102
31-Aug-2015 05:08:06 - DEBUG   :: SEARCH : search-url: https://api.nzb.su/api?t=search&q=deadpool's%20secret%20secret%20wars%20004&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
31-Aug-2015 05:08:06 - INFO    :: SEARCH : pausing for 60 seconds before continuing to avoid hammering
31-Aug-2015 05:09:06 - WARNING :: SEARCH : Error fetching data from nzb.su: < urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

(repeat from RSS Check onwards three times...)

31-Aug-2015 05:14:09 - INFO    :: SEARCH : Could not find Issue 4 of Deadpool's Secret Secret Wars(2015) using nzb.su [api]
31-Aug-2015 05:14:09 - DEBUG   :: SEARCH : using Newznab host of : OMG
31-Aug-2015 05:14:09 - INFO    :: SEARCH : Shhh be very quiet...I'm looking for Deadpool's Secret Secret Wars issue: 4 (2015) using OMG (newznab)
31-Aug-2015 05:14:09 - DEBUG   :: SEARCH : calpha/cnumber: None / None
31-Aug-2015 05:14:09 - DEBUG   :: SEARCH : RSS Check: None
31-Aug-2015 05:14:09 - DEBUG   :: SEARCH : nzbprov: newznab
31-Aug-2015 05:14:09 - DEBUG   :: SEARCH : comicid: 82102
31-Aug-2015 05:14:09 - DEBUG   :: SEARCH : search-url: http://api.omgwtfnzbs.org/api?t=search&q=deadpool's%20secret%20secret%20wars%20004&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
31-Aug-2015 05:14:09 - INFO    :: SEARCH : pausing for 60 seconds before continuing to avoid hammering
31-Aug-2015 05:15:09 - WARNING :: SEARCH : Error fetching data from newznab: < urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

Looking at my VIP information on the sites, I'm clocking up API hits but no grabs.

I'm running the development branch with Python 2.7.10 - have had a pretty thorough dig around these issues and the forum, so apologies if I'm missing something.

**Comment by evilhero** [comment] 2015-08-31 14:42
Make sure you're running mylar against python 2.7.10 - sometimes if you have more than one version installed of python it takes a different value (on the the first tab of the mylar configuration page it will indicate the version of python it's running against). The handshake error is usually an indication of running a non-compliant version of python (<2.7.7)

Also, your api url for OMG is using a non-https url address.

**Comment by DaveBrackets** [comment] 2015-08-31 14:59
From the config screen:

Mylar Version: development
-- git build 9af9913819a55818d3fabcad9607a536d824f7c5.
Python Version : 2.7.10

From the command prompt:
OpenSSL 1.0.2a 19 Mar 2015

(is there any way to tell whether Mylar is successfully using that version of OpenSSL? I installed that manually into Python as part of my own troubleshooting...)

**Comment by evilhero** [comment] 2015-08-31 17:46
Unfortunately I don't have access to nzb.su to verify if it's a problem with them, or how mylar is retrieving items from there (it was working previously so if it's not,  then something has changed somewhere)

Is OMG working now that you updated the url? 

Remember that after any configuration change/error, you need to restart mylar in order to clear out the errors properly.

**Comment by DaveBrackets** [comment] 2015-08-31 18:27
URL updated, restarted Mylar - no better:

31-Aug-2015 19:16:42 - INFO    :: Thread-12 : Shhh be very quiet...I'm looking for Secret Six issue: 5 (2015) using OMG (newznab)
31-Aug-2015 19:16:42 - DEBUG   :: Thread-12 : calpha/cnumber: None / None
31-Aug-2015 19:16:42 - DEBUG   :: Thread-12 : RSS Check: None
31-Aug-2015 19:16:42 - DEBUG   :: Thread-12 : nzbprov: newznab
31-Aug-2015 19:16:42 - DEBUG   :: Thread-12 : comicid: 78534
31-Aug-2015 19:16:42 - DEBUG   :: Thread-12 : search-url: https://api.omgwtfnzbs.org/api?t=search&q=secret%20six%20005&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
31-Aug-2015 19:16:42 - INFO    :: Thread-12 : pausing for 60 seconds before continuing to avoid hammering
31-Aug-2015 19:17:43 - WARNING :: Thread-12 : Error fetching data from newznab: < urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

I haven't got HTTPS enabled in Mylar, but I never have had and it didn't seem to make any difference previously...

**Comment by DaveBrackets** [comment] 2015-08-31 20:00
...okay, can't work out if I should be facepalming right now. In case this is useful information:

As I mentioned above, I'm running Mylar on my home server. I don't do any web browsing on it, it's a home server. 

Reading around the issue it seemed to me that this is something to do with the change to SSL in Python 2.7.9 and higher, which leads me down a path of certificates and similar that I don't know how to follow. So, in desperation, I came up with a manual API call for the OMG and Su APIs and whacked them into the server's browser - and now it's working. I'm guessing that made it download the certificates? Or something?

As I say - no idea whether this is something I should be ashamed for not thinking of earlier...as you can probably tell, my technical knowledge doesn't go all that far! But screw it, I'm happy.

Well - I say "working" - the OMG one is now throwing a 404 on the search URL, which looking at their documentation I think is because they format their API calls differently. I can go into detail, or is the etiquette to start a new issue for that?

**Comment by evilhero** [comment] 2015-08-31 20:57
TBH I'm not sure why that would cause it to work, unless it was trying to use some stale cookies  (which the api calls don't even use a browser). I'm glad it's working for ya, I honestly wish I knew the cause and why doing what you did caused it to work (aside from cookies,  which I don't think would've factored in but who knows).

As far as the OMG api differentiation, if you could create a new issue with all the details and possibly provide the formatting for the search api call and download nzb call for OMG it would help and save a lot of time.

Otherwise, I'd have to try and find that stuff out myself and without an account it makes things abit difficult obviously. 

The information for both of these calls should be documented in their api documentation I would expect.

**Comment by DaveBrackets** [comment] 2015-08-31 21:58
I have two guesses, but I wouldn't describe them as anything more than that!

1) Reading around the Python issue, it seems like it checks a central certificate store maintained by your OS rather than keeping its own store. So I wonder if by visiting the sites I got the certificates, which got put into that central store.

2) Windows Home Server is a wacky, heavily-restricted OS. Maybe there was some layer of protection preventing the API calls that was broken when I went through the browser to get there.

If I had to put my money anywhere, I'd put it on (1). But it's a guess.

**Comment by TBhimdi** [comment] 2015-09-05 23:41
I'm having the exact same issue, except my Mylar (running on Windows 8.1 for a few months now) is checking NZBMegaSearch on my VPS (hosted via HTTPS with a self-signed certificate).

Here's the error from the log:

```
05-Sep-2015 09:57:00 - WARNING :: SEARCH : Error fetching data from newznab: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```

Here's my mylar:

```
Mylar Version: development
-- git build 9af9913819a55818d3fabcad9607a536d824f7c5.
Python Version : 2.7.10
```

And my Python:
```
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> print(ssl.OPENSSL_VERSION)
OpenSSL 1.0.2a 19 Mar 2015
```

**Comment by evilhero** [comment] 2015-09-06 02:45
Apparently with windows OS,  if you encounter this type of error you might need to import the certificate into the box that's running mylar. Pretty much what DaveBrackets mentioned about being a central repository and not ever site is included by default (especially self-signed). 

From a blurb somewhere:
```
Python uses certificates from 'system ssl certificate store' to certify https connections, if there are  not any appropriate ssl cert in the store errors can occur like this. You need to download the ssl certificate (Open your https link in browser and click lock icon in address bar > More Information > View Certificate > Details > Export) and install it on your system as stated this link:
http://windows.microsoft.com/en-us/windows/import-export-certificates-private-keys#1TC=windows-7
```

**Comment by TBhimdi** [comment] 2015-09-07 00:42
So I switched the Mylar Newznab Host to point to my VPS using a domain that has a valid SSL cert (so no longer self-signed) and no more Python error, but am now getting this new error (it appears to be a Mylar error, but no idea if it's related to SSL or not):

```
06-Sep-2015 20:33:33 - DEBUG   :: Thread-12 : search-url: https://example.com:5000/api?t=search&q=angel%20%20faith%20season%2010%20018&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
06-Sep-2015 20:33:33 - INFO    :: Thread-12 : pausing for 60 seconds before continuing to avoid hammering
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : checking search result: Angel & Faith Season 10 018 (2015) (Digital) (Cypher 2.0-Empire)
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : size given as: 22.2 MB
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : Wed, 02 Sep 2015 19:13:17 is after store date of 2015-09-02
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : Entry: Angel & Faith Season 10 018 (2015) (Digital) (Cypher 2.0-Empire)
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : Cleantitle: angel and faith season 10 018 (2015) (digital) (cypher 2 0-empire)
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : Cleantitle: angel and faith season 10 018 (2015) (digital) (cypher 2 0-empire)
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : 0. Bracket Word: angel and faith season 10 018 
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : Comic: angel and faith season 10 018 
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : UseFuzzy is  : None
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : ComVersChk : 0
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : Series version detected as V1 (only series in existance with that title). Bypassing Year/Volume check
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : 1. Bracket Word: 2015
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : year detected: 2015
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : year looking for: 2015
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : 2015 - right years match baby!
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : 3. Bracket Word: digital
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : digital edition detected
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : 5. Bracket Word: cypher 2 0-empire
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : Scanner detected: cypher 2 0-empire
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : original nzb comic and issue: angel and faith season 10 018 
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : adjusted nzb comic and issue: angel and faith season 10 018 
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : chg_comic:angel and faith season 10
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : chg_comic: ANGELANDFAITHSEASON10
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : findcomic_chksplit: ANGELANDFAITHSEASON10
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : series contains numerics...adjusting..
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : adjusting from: angel and faith season 10 018  to: 018
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : ['angel', 'and', 'faith', 'season', '10', '018'] nzb series word count: 5
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : ['angel', 'and', 'faith', 'season', '10'] watchlist word count: 5
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : splitst : 5
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : len-watchcomic : 5
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : length match..proceeding
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : search-length: 5
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : Watchlist-length: 5
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : splitit: angel
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : scount : 0
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : 0 Comparing: angel .to. angel
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : word matched on : angel
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : splitit: and
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : scount : 1
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : 1 Comparing: and .to. and
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : word matched on : and
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : splitit: faith
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : scount : 2
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : 2 Comparing: faith .to. faith
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : word matched on : faith
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : splitit: season
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : scount : 3
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : 3 Comparing: season .to. season
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : word matched on : season
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : splitit: 10
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : scount : 4
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : 4 Comparing: 10 .to. 10
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : word matched on : 10
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : scount:5
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : splitit-len:5
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : Match to series : 100.0 %.
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : it's a go captain... - we matched 100.0%!
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : this should be a match!
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : issue we are looking for is : 18
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : integer value of issue we are looking for : 18000
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : issue we found for is : 018
06-Sep-2015 20:34:41 - DEBUG   :: Thread-12 : integer value of issue we have found : 18000
06-Sep-2015 20:34:41 - ERROR   :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "C:\Util\daemon\mylar\mylar\logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "C:\Util\Devel\python\python-2.7.10.amd64\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Util\daemon\mylar\mylar\webserve.py", line 1303, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
  File "C:\Util\daemon\mylar\mylar\search.py", line 242, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "C:\Util\daemon\mylar\mylar\search.py", line 1362, in NZB_SEARCH
    nzbname = nzbname_create(nzbprov, info=comicinfo, title=entry['title'])
  File "C:\Util\daemon\mylar\mylar\search.py", line 1675, in nzbname_create
    logger.fdebug("nzbname used for post-processing:" + nzbname)
UnboundLocalError: local variable 'nzbname' referenced before assignment
```

**Comment by evilhero** [comment] 2015-09-07 02:23
That's due to a blank newznab entry I believe, although it should have at least indicated the provider somewhere in the logs  ( probably just prior to the start of your log ).

Check you config.ini and ensure that there aren't isn't a blank newznab entry somewhere in the extra_newznabs line (make sure that mylar isn't running). 

The other possibility is that you didn't provide a name for the newznab entry and left it blank,  although that would have gotten logged differently I'd imagine.

**Comment by TBhimdi** [comment] 2015-09-07 02:33
I updated my previous comment with the preceding lines.

As for the "extra_newznabs" line, I only have one in my config.ini and this is it:

```
extra_newznabs = NZBMegasearcH, https://example.com:5000, xxxxxxxxxxx, "", 1
```

The Newznab UID is blank in my settings because it's "only needed for RSS feed".

**Comment by evilhero** [comment] 2015-09-07 02:49
Hmm ok there's something amiss.  What does the provider _ order line in the config.ini show? 

Is there an extra entry/blank entry in that line?

**Comment by TBhimdi** [comment] 2015-09-07 13:11
```
provider_order = N, o, n, e, 2, NZBMegasearcH
```

**Comment by evilhero** [comment] 2015-09-07 13:13
Whoa that's messed up.

Shutdown Mylar,  edit the config.ini and delete the entire provider_order line. Save it, and start Mylar and it will regenerate it properly and fix everything.

**Comment by TBhimdi** [comment] 2015-09-07 13:20
Ha, OK. Here's the new line after regeneration:

```
provider_order = 0, NZBMegasearcH
```

And here's the error I get (same error as before it appears):

```
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : ComicID:42986
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : mode:want
07-Sep-2015 09:16:11 - INFO    :: Thread-12 : Initiating manual search for Superman issue: 43
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : Publisher is : DC Comics
07-Sep-2015 09:16:11 - INFO    :: Thread-12 : Issue Title given as : before truth part 3
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : Checking for torrent enabled.
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : newznab name:NZBMegasearcH @ https://example.com:5000
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : nzbprovider(s): ['newznab:NZBMegasearcH']
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : there are : 0 torrent providers you have selected.
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : there are : 1 nzb providers you have selected.
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : Usenet Retention : 2000 days
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : found provider in existing enabled providers.
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : checking against nzb provider: newznab:NZBMegasearcH
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : newznab match against: newznab:NZBMegasearcH
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : sucessfully matched - appending to provider.order sequence
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : provider order sequence is now to start with NZBMegasearcH at spot #0
07-Sep-2015 09:16:11 - INFO    :: Thread-12 : search provider order is ['newznab:NZBMegasearcH']
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : Initiating Search via : api
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : using Newznab host of : NZBMegasearcH
07-Sep-2015 09:16:11 - INFO    :: Thread-12 : Shhh be very quiet...I'm looking for Superman issue: 43 (2015) using NZBMegasearcH (newznab)
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : calpha/cnumber: None / None
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : RSS Check: None
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : nzbprov: newznab
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : comicid: 42986
07-Sep-2015 09:16:11 - DEBUG   :: Thread-12 : search-url: https://example.com:5000/api?t=search&q=superman%20043&o=xml&cat=7030&apikey=xUDONTNEEDTOKNOWTHISx
07-Sep-2015 09:16:11 - INFO    :: Thread-12 : pausing for 60 seconds before continuing to avoid hammering
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : checking search result: Superman [1995-13] Man Of Steel 043
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : size given as: 3.0 MB
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : Sat, 21 Jun 2014 15:58:30 is before store date of 2015-08-26. Ignoring search result as this is not the right issue.
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : checking search result: Superman's Girlfriend Lois Lane 043
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : size given as: 7.6 MB
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : Sat, 21 Jun 2014 16:47:30 is before store date of 2015-08-26. Ignoring search result as this is not the right issue.
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : checking search result: Superman's pal Jimmy Olsen 043
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : size given as: 16.4 MB
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : Sat, 21 Jun 2014 16:47:38 is before store date of 2015-08-26. Ignoring search result as this is not the right issue.
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : checking search result: Adventures.Of.Superman.043.2014-UNKNOWN
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : size given as: 15.5 MB
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : Tue, 25 Feb 2014 20:53:55 is before store date of 2015-08-26. Ignoring search result as this is not the right issue.
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : checking search result: Superman Batman 043 (2008) (FB-DCP
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : size given as: 16.2 MB
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : Tue, 29 Jul 2014 02:20:40 is before store date of 2015-08-26. Ignoring search result as this is not the right issue.
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : checking search result: Superman 043 (2015) (Webrip) (The Last Kryptonian-DCP)
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : size given as: 36.7 MB
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : Thu, 27 Aug 2015 22:35:34 is after store date of 2015-08-26
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : Entry: Superman 043 (2015) (Webrip) (The Last Kryptonian-DCP)
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : Cleantitle: superman 043 (2015) (webrip) (the last kryptonian-dcp)
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : Cleantitle: superman 043 (2015) (webrip) (the last kryptonian-dcp)
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : 0. Bracket Word: superman 043 
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : Comic: superman 043 
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : UseFuzzy is  : None
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : ComVersChk : 0
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : Series version detected as V1 (only series in existance with that title). Bypassing Year/Volume check
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : 1. Bracket Word: 2015
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : year detected: 2015
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : year looking for: 2015
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : 2015 - right years match baby!
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : 3. Bracket Word: webrip
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : 5. Bracket Word: the last kryptonian-dcp
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : Scanner detected: the last kryptonian-dcp
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : original nzb comic and issue: superman 043 
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : adjusted nzb comic and issue: superman 043 
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : adjusting from: superman 043  to: 043
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : ['superman', '043'] nzb series word count: 1
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : ['superman'] watchlist word count: 1
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : splitst : 1
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : len-watchcomic : 1
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : length match..proceeding
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : search-length: 1
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : Watchlist-length: 1
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : splitit: superman
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : scount : 0
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : 0 Comparing: superman .to. superman
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : word matched on : superman
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : scount:1
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : splitit-len:1
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : Match to series : 100.0 %.
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : it's a go captain... - we matched 100.0%!
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : this should be a match!
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : issue we are looking for is : 43
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : integer value of issue we are looking for : 43000
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : issue we found for is : 043
07-Sep-2015 09:17:20 - DEBUG   :: Thread-12 : integer value of issue we have found : 43000
07-Sep-2015 09:17:20 - ERROR   :: Thread-12 : Uncaught exception: Traceback (most recent call last):
  File "C:\Util\daemon\mylar\mylar\logger.py", line 159, in new_run
    old_run(*args, **kwargs)
  File "C:\Util\Devel\python\python-2.7.10.amd64\lib\threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Util\daemon\mylar\mylar\webserve.py", line 1303, in queueissue
    foundcom, prov = search.search_init(ComicName, ComicIssue, ComicYear, SeriesYear, Publisher, issues['IssueDate'], storedate, IssueID, AlternateSearch, UseAFuzzy, ComicVersion, mode=mode, ComicID=ComicID, manualsearch=manualsearch, filesafe=ComicName_Filesafe)
  File "C:\Util\daemon\mylar\mylar\search.py", line 242, in search_init
    findit = NZB_SEARCH(ComicName, IssueNumber, ComicYear, SeriesYear, Publisher, IssueDate, StoreDate, searchprov, prov_count, IssDateFix, IssueID, UseFuzzy, newznab_host, ComicVersion=ComicVersion, SARC=SARC, IssueArcID=IssueArcID, ComicID=ComicID, issuetitle=issuetitle, unaltered_ComicName=unaltered_ComicName)
  File "C:\Util\daemon\mylar\mylar\search.py", line 1362, in NZB_SEARCH
    nzbname = nzbname_create(nzbprov, info=comicinfo, title=entry['title'])
  File "C:\Util\daemon\mylar\mylar\search.py", line 1675, in nzbname_create
    logger.fdebug("nzbname used for post-processing:" + nzbname)
UnboundLocalError: local variable 'nzbname' referenced before assignment
```

**Comment by evilhero** [comment] 2015-09-07 13:27
Ugh that shouldn't be happening - do you have the blackhole option enabled within mylar for some reason?

**Comment by TBhimdi** [comment] 2015-09-07 13:30
Correct, I'm using blackhole. I was having Sabnzbd issues with my VPS (and open ports on my end and API issues, etc) and since I already had a synced folder between my PC and my VPS, blackhole works perfectly (I had it setup for other uses anyway). The folder syncs the nzb file between my PC and VPS and everything is downloaded like it should.

**Comment by evilhero** [comment] 2015-09-07 13:40
Ok so I can see now what's happening. Mylar tests to see if the blackhole location specified exists - I'm going to assume that the blackhole location is on a machine other than the one mylar resides on? Or if it exists, then mylar can't find the blackhole location path provided for it. 

Can you confirm the blackhole path and that it exists or is reachable via the machine mylar is running on?

**Comment by TBhimdi** [comment] 2015-09-07 14:00
AH HA! That was the problem. A couple weeks ago I did some directory reshuffling and apparently had a typo in the directory name in that process (human error), thus Mylar didn't detect the directory correctly.

Sorry about the phantom issue, looks like it's all fixed now.

**Closed** 2015-10-07 15:04 UTC
